// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/Data.sv
// Created: 2026-06-15 17:31:49
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Data
// Source Path: introOFDMTransmitter/OFDM Transmitter/Grid Contents/Data
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Data
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic isData,
             input logic frameStart,
             input logic txPayload_0  /* ufix1 */,
             input logic txPayload_1  /* ufix1 */,
             input logic txPayloadValid,
             output logic data_0  /* boolean */,
             output logic data_1  /* boolean */,
             output logic validOut,
             output logic txPayloadReady);


  logic FWFT_FIFO_ready;
  logic NOT1_out1;
  logic Unit_Delay_Enabled_Synchronous_out1;
  logic AND1_out1;
  logic FWFT_FIFO_dataOut_0;
  logic FWFT_FIFO_dataOut_1;
  logic[1:0] FWFT_FIFO_dataOut;  /* boolean [2] */
  logic [5:0] Delay4_reg;  /* ufix1 [6] */
  logic[1:0] Delay4_out1;  /* boolean [2] */
  logic [2:0] Delay2_reg;  /* ufix1 [3] */
  logic Delay2_out1;


  assign NOT1_out1 =  ~ FWFT_FIFO_ready;

  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 1'b0;
      end
      else begin
        if (enb && frameStart) begin
          Unit_Delay_Enabled_Synchronous_out1 <= NOT1_out1;
        end
      end
    end

  assign AND1_out1 = Unit_Delay_Enabled_Synchronous_out1 & isData;

  FWFT_FIFO u_FWFT_FIFO (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .dataIn_0(txPayload_0),  /* ufix1 */
                         .dataIn_1(txPayload_1),  /* ufix1 */
                         .push(txPayloadValid),
                         .pop(AND1_out1),
                         .dataOut_0(FWFT_FIFO_dataOut_0),  /* boolean */
                         .dataOut_1(FWFT_FIFO_dataOut_1),  /* boolean */
                         .ready(FWFT_FIFO_ready)
                         );

  assign FWFT_FIFO_dataOut[0] = FWFT_FIFO_dataOut_0;
  assign FWFT_FIFO_dataOut[1] = FWFT_FIFO_dataOut_1;

  always_ff @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_reg <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          Delay4_reg[32'sd1:32'sd0] <= FWFT_FIFO_dataOut[32'sd1:32'sd0];
          Delay4_reg[32'sd5:32'sd2] <= Delay4_reg[32'sd3:32'sd0];
        end
      end
    end

  assign Delay4_out1[32'sd1:32'sd0] = Delay4_reg[32'sd5:32'sd4];

  assign data_0 = Delay4_out1[0];

  assign data_1 = Delay4_out1[1];

  always_ff @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_reg <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          Delay2_reg[0] <= AND1_out1;
          Delay2_reg[32'sd2:32'sd1] <= Delay2_reg[32'sd1:32'sd0];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[2];

  assign validOut = Delay2_out1;

  assign txPayloadReady = FWFT_FIFO_ready;

endmodule  // Data

