// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/fwft_logic.sv
// Created: 2026-06-20 03:33:58
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: fwft_logic
// Source Path: introOFDMTransmitter/OFDM Transmitter/Grid Contents/Data/FWFT FIFO/fwft_logic
// Hierarchy Level: 4
// Model version: 10.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module fwft_logic
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [1:0] data_i  /* ufix2 */,
             input logic empty_i,
             input logic rd_ack,
             input logic [17:0] num_i  /* ufix18 */,
             output logic [1:0] data_o  /* ufix2 */,
             output logic [17:0] num_o  /* ufix18 */,
             output logic pop_o);


  logic Logical_Operator18_out1;
  logic out_valid;
  logic Logical_Operator8_out1;
  logic Logical_Operator7_out1;
  logic cache_valid;
  logic out_wr_en;
  logic Logical_Operator5_out1;
  logic cache_wr_en;
  logic Logical_Operator1_out1;
  logic fifo_valid;
  logic Logical_Operator21_out1;
  logic Logical_Operator20_out1;
  logic Logical_Operator22_out1;
  logic pop;
  logic Logical_Operator3_out1;
  logic [1:0] fifo_data;  /* ufix2 */
  logic [1:0] cache_data;  /* ufix2 */
  logic [1:0] Switch_out1;  /* ufix2 */
  logic [1:0] out_data;  /* ufix2 */
  logic [17:0] num_out_calc_num_out;  /* ufix18 */


  assign Logical_Operator18_out1 =  ~ empty_i;

  assign Logical_Operator8_out1 =  ~ out_valid;

  assign Logical_Operator7_out1 = rd_ack | Logical_Operator8_out1;

  assign Logical_Operator5_out1 =  ~ (cache_valid ^ out_wr_en);

  assign Logical_Operator1_out1 = cache_wr_en | out_wr_en;

  sr_latch2 u_sr_latch2 (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .S(out_wr_en),
                         .R(rd_ack),
                         .Q(out_valid)
                         );

  assign Logical_Operator21_out1 = fifo_valid & out_valid;

  assign Logical_Operator20_out1 = cache_valid & Logical_Operator21_out1;

  assign Logical_Operator22_out1 =  ~ Logical_Operator20_out1;

  assign pop = Logical_Operator18_out1 & Logical_Operator22_out1;

  sr_latch1 u_sr_latch1 (.clk(clk),
                         .reset(reset),
                         .enb(enb),
                         .S(pop),
                         .R(Logical_Operator1_out1),
                         .Q(fifo_valid)
                         );

  assign cache_wr_en = fifo_valid & Logical_Operator5_out1;

  sr_latch u_sr_latch (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .S(cache_wr_en),
                       .R(out_wr_en),
                       .Q(cache_valid)
                       );

  assign Logical_Operator3_out1 = cache_valid | fifo_valid;

  assign out_wr_en = Logical_Operator3_out1 & Logical_Operator7_out1;

  assign fifo_data = data_i;

  always_ff @(posedge clk)
    begin : cache_reg_process
      if (reset == 1'b1) begin
        cache_data <= 2'b00;
      end
      else begin
        if (enb && cache_wr_en) begin
          cache_data <= fifo_data;
        end
      end
    end

  assign Switch_out1 = (cache_valid == 1'b0 ? fifo_data :
              cache_data);

  always_ff @(posedge clk)
    begin : out_reg_process
      if (reset == 1'b1) begin
        out_data <= 2'b00;
      end
      else begin
        if (enb && out_wr_en) begin
          out_data <= Switch_out1;
        end
      end
    end

  assign data_o = out_data;

  num_out_calc u_num_out_calc (.num_in(num_i),  /* ufix18 */
                               .cache_valid(cache_valid),
                               .fifo_valid(fifo_valid),
                               .out_valid(out_valid),
                               .num_out(num_out_calc_num_out)  /* ufix18 */
                               );

  assign num_o = num_out_calc_num_out;

  assign pop_o = pop;

endmodule  // fwft_logic

