// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/OFDM_Mod_Scaling.sv
// Created: 2026-06-20 03:33:58
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Transmitter_pkg::* ;

// -------------------------------------------------------------
// 
// Module: OFDM_Mod_Scaling
// Source Path: introOFDMTransmitter/OFDM Transmitter/OFDM Mod Scaling
// Hierarchy Level: 1
// Model version: 10.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OFDM_Mod_Scaling
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [23:0] dataIn_re  /* sfix24_En15 */,
             input logic signed [23:0] dataIn_im  /* sfix24_En15 */,
             input logic validIn,
             output logic signed [15:0] dataOut_re  /* sfix16_En15 */,
             output logic signed [15:0] dataOut_im  /* sfix16_En15 */,
             output logic validOut);


  logic signed [23:0] Delay_out1_re;  /* sfix24_En15 */
  logic signed [23:0] Delay_out1_im;  /* sfix24_En15 */
  logic signed [42:0] Gain_mul_temp;  /* sfix43_En38 */
  logic signed [41:0] Gain_cast;  /* sfix42_En38 */
  logic signed [42:0] Gain_mul_temp_1;  /* sfix43_En38 */
  logic signed [41:0] Gain_cast_1;  /* sfix42_En38 */
  logic signed [15:0] Gain_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Gain_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay1_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay1_out1_im;  /* sfix16_En15 */
  logic [1:0] Delay2_reg;  /* ufix1 [2] */
  logic Delay2_out1;


  always_ff @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1_re <= 24'sb000000000000000000000000;
        Delay_out1_im <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1_re <= dataIn_re;
          Delay_out1_im <= dataIn_im;
        end
      end
    end

  assign Gain_mul_temp = 19'sb0100001100110011010 * Delay_out1_re;
  assign Gain_cast = Gain_mul_temp[41:0];
  assign Gain_out1_re = Gain_cast[38:23] + $signed({1'b0, Gain_cast[22] & (( ~ Gain_cast[41]) | (|Gain_cast[21:0]))});
  assign Gain_mul_temp_1 = 19'sb0100001100110011010 * Delay_out1_im;
  assign Gain_cast_1 = Gain_mul_temp_1[41:0];
  assign Gain_out1_im = Gain_cast_1[38:23] + $signed({1'b0, Gain_cast_1[22] & (( ~ Gain_cast_1[41]) | (|Gain_cast_1[21:0]))});

  always_ff @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_re <= Gain_out1_re;
          Delay1_out1_im <= Gain_out1_im;
        end
      end
    end

  assign dataOut_re = Delay1_out1_re;

  assign dataOut_im = Delay1_out1_im;

  always_ff @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_reg <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          Delay2_reg[0] <= validIn;
          Delay2_reg[1] <= Delay2_reg[0];
        end
      end
    end

  assign Delay2_out1 = Delay2_reg[1];

  assign validOut = Delay2_out1;

endmodule  // OFDM_Mod_Scaling

