// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/QPSK_Modulator.sv
// Created: 2026-06-22 13:23:20
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Transmitter_pkg::* ;

// -------------------------------------------------------------
// 
// Module: QPSK_Modulator
// Source Path: introOFDMTransmitter/OFDM Transmitter/Grid Contents/Symbol Modulation/QPSK Modulator
// Hierarchy Level: 3
// Model version: 10.4
// 
// Generalized Symbol Modulator
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module QPSK_Modulator
          #(  parameter vector_of_signed_logic_16 TablePropDataOutIm_data [0:3] = '{23170, -23171, 23170, -23171}  /* sfix16 [4] */,
              parameter vector_of_signed_logic_16 TablePropDataOutRe_data [0:3] = '{23170, 23170, -23171, -23171}  /* sfix16 [4] */)
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic in0_0  /* boolean */,
             input logic in0_1  /* boolean */,
             input logic in1,
             output logic signed [15:0] out0_re  /* sfix16_En15 */,
             output logic signed [15:0] out0_im  /* sfix16_En15 */,
             output logic out1);


  logic ConstantZeroForRstProp;  /* ufix1 */
  logic validInDelay1;  /* ufix1 */
  logic idxLUTPropValid;  /* ufix1 */
  logic validOut;
  logic switch_compare_1;
  logic signed [15:0] ComplxZeroConst_re;  /* sfix16_En15 */
  logic signed [15:0] ComplxZeroConst_im;  /* sfix16_En15 */
  logic[1:0] dataIn;  /* boolean [2] */
  logic [1:0] dataInVecDelay1;  /* ufix1 [2] */
  logic [1:0] idxNBPSProp;  /* ufix2 */
  logic [1:0] dataLutIdx;  /* ufix2 */
  logic signed [15:0] propDataOutSymModRe;  /* sfix16_En15 */
  logic signed [15:0] propDataOutSymModIm;  /* sfix16_En15 */
  logic signed [15:0] dataOutSymModD1_re;  /* sfix16_En15 */
  logic signed [15:0] dataOutSymModD1_im;  /* sfix16_En15 */
  logic signed [15:0] dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] dataOut_im;  /* sfix16_En15 */

  initial begin
    dataOutSymModD1_re = 16'sb0000000000000000;
    dataOutSymModD1_im = 16'sb0000000000000000;
  end

  assign ConstantZeroForRstProp = 1'b0;

  always_ff @(posedge clk)
    begin : delay_validInProp_process
      if (reset == 1'b1) begin
        validInDelay1 <= 1'b0;
      end
      else begin
        if (enb) begin
          if (ConstantZeroForRstProp == 1'b1) begin
            validInDelay1 <= 1'b0;
          end
          else begin
            validInDelay1 <= in1;
          end
        end
      end
    end

  always_ff @(posedge clk)
    begin : delay2ValidInProp_process
      if (reset == 1'b1) begin
        idxLUTPropValid <= 1'b0;
      end
      else begin
        if (enb) begin
          if (ConstantZeroForRstProp == 1'b1) begin
            idxLUTPropValid <= 1'b0;
          end
          else begin
            idxLUTPropValid <= validInDelay1;
          end
        end
      end
    end

  always_ff @(posedge clk)
    begin : delay_validOutProp_process
      if (reset == 1'b1) begin
        validOut <= 1'b0;
      end
      else begin
        if (enb) begin
          if (ConstantZeroForRstProp == 1'b1) begin
            validOut <= 1'b0;
          end
          else begin
            validOut <= idxLUTPropValid;
          end
        end
      end
    end

  assign switch_compare_1 = validOut > 1'b0;

  assign ComplxZeroConst_re = 16'sb0000000000000000;
  assign ComplxZeroConst_im = 16'sb0000000000000000;

  assign dataIn[0] = in0_0;
  assign dataIn[1] = in0_1;

  always_ff @(posedge clk)
    begin : reg_rsvd_process
      if (reset == 1'b1) begin
        dataInVecDelay1 <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          dataInVecDelay1 <= dataIn;
        end
      end
    end

  assign idxNBPSProp = {dataInVecDelay1[0], dataInVecDelay1[1]};

  always_ff @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        dataLutIdx <= 2'b00;
      end
      else begin
        if (enb) begin
          dataLutIdx <= idxNBPSProp;
        end
      end
    end

  assign propDataOutSymModRe = TablePropDataOutRe_data[dataLutIdx];

  assign propDataOutSymModIm = TablePropDataOutIm_data[dataLutIdx];

  always @(posedge clk)
    begin : delay_dataOutSymMod_process
      if (enb) begin
        dataOutSymModD1_re <= propDataOutSymModRe;
        dataOutSymModD1_im <= propDataOutSymModIm;
      end
    end

  assign dataOut_re = (switch_compare_1 == 1'b0 ? ComplxZeroConst_re :
              dataOutSymModD1_re);
  assign dataOut_im = (switch_compare_1 == 1'b0 ? ComplxZeroConst_im :
              dataOutSymModD1_im);

  assign out0_re = dataOut_re;

  assign out0_im = dataOut_im;

  assign out1 = validOut;

endmodule  // QPSK_Modulator

