// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/RADIX22FFT_CTRL1_1.sv
// Created: 2026-06-20 03:33:58
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Transmitter_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_CTRL1_1
// Source Path: introOFDMTransmitter/OFDM Transmitter/OFDM Modulator/dsphdl.IFFT/RADIX22FFT_CTRL1_1
// Hierarchy Level: 3
// Model version: 10.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_CTRL1_1
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic dinXTwdl_1_1_vld,
             input logic dinXTwdl_1_1_vld_1,
             output logic [6:0] rd_1_Addr  /* ufix7 */,
             output logic rd_1_Enb,
             output logic proc_1_enb);


  logic [6:0] SDFController_wrCount;  /* ufix7 */
  logic [1:0] SDFController_wrState;  /* ufix2 */
  logic [1:0] SDFController_rdState;  /* ufix2 */
  logic [6:0] SDFController_rdAddr_reg;  /* ufix7 */
  logic SDFController_procEnb_reg;
  logic [1:0] SDFController_multjState;  /* ufix2 */
  logic SDFController_multiply_J_reg;
  logic [6:0] SDFController_wrCount_next;  /* ufix7 */
  logic [1:0] SDFController_wrState_next;  /* ufix2 */
  logic [1:0] SDFController_rdState_next;  /* ufix2 */
  logic [6:0] SDFController_rdAddr_reg_next;  /* ufix7 */
  logic SDFController_procEnb_reg_next;
  logic [1:0] SDFController_multjState_next;  /* ufix2 */
  logic SDFController_multiply_J_reg_next;
  logic [6:0] rd_1_Addr_1;  /* ufix7 */
  logic rd_1_Enb_1;
  logic proc_1_enb_1;
  logic multiply_1_J;


  // SDFController
  always_ff @(posedge clk)
    begin : SDFController_process
      if (reset == 1'b1) begin
        SDFController_wrCount <= 7'b0000000;
        SDFController_rdAddr_reg <= 7'b0000000;
        SDFController_wrState <= 2'b00;
        SDFController_rdState <= 2'b00;
        SDFController_multjState <= 2'b00;
        SDFController_procEnb_reg <= 1'b0;
        SDFController_multiply_J_reg <= 1'b0;
      end
      else begin
        if (enb) begin
          SDFController_wrCount <= SDFController_wrCount_next;
          SDFController_wrState <= SDFController_wrState_next;
          SDFController_rdState <= SDFController_rdState_next;
          SDFController_rdAddr_reg <= SDFController_rdAddr_reg_next;
          SDFController_procEnb_reg <= SDFController_procEnb_reg_next;
          SDFController_multjState <= SDFController_multjState_next;
          SDFController_multiply_J_reg <= SDFController_multiply_J_reg_next;
        end
      end
    end

  always_comb begin
    SDFController_wrCount_next = SDFController_wrCount;
    SDFController_rdState_next = SDFController_rdState;
    SDFController_rdAddr_reg_next = SDFController_rdAddr_reg;
    SDFController_procEnb_reg_next = SDFController_procEnb_reg;
    SDFController_multjState_next = SDFController_multjState;
    case ( SDFController_multjState)
      2'b00 :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b10) begin
            SDFController_multjState_next = 2'b10;
          end
        end
      2'b10 :
        begin
          SDFController_multiply_J_reg_next = 1'b0;
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
        end
      2'b11 :
        begin
          if (SDFController_rdState == 2'b01) begin
            SDFController_multjState_next = 2'b11;
            SDFController_multiply_J_reg_next = 1'b1;
          end
          else begin
            SDFController_multiply_J_reg_next = 1'b0;
            SDFController_multjState_next = 2'b00;
          end
        end
      default :
        begin
          SDFController_multjState_next = 2'b00;
          SDFController_multiply_J_reg_next = 1'b0;
        end
    endcase
    case ( SDFController_rdState)
      2'b00 :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 7'b0000000;
          rd_1_Enb_1 = 1'b0;
          if (dinXTwdl_1_1_vld && (SDFController_wrCount == 7'b1111111)) begin
            SDFController_rdState_next = 2'b01;
          end
        end
      2'b01 :
        begin
          SDFController_rdState_next = 2'b01;
          rd_1_Enb_1 = dinXTwdl_1_1_vld_1;
          if (dinXTwdl_1_1_vld_1) begin
            if (SDFController_rdAddr_reg == 7'b1111111) begin
              SDFController_rdState_next = 2'b10;
            end
            SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 7'b0000001;
          end
        end
      2'b10 :
        begin
          rd_1_Enb_1 = 1'b1;
          if (SDFController_rdAddr_reg == 7'b1111111) begin
            if (dinXTwdl_1_1_vld && (SDFController_wrCount == 7'b1111111)) begin
              SDFController_rdState_next = 2'b01;
            end
            else begin
              SDFController_rdState_next = 2'b00;
            end
          end
          SDFController_rdAddr_reg_next = SDFController_rdAddr_reg + 7'b0000001;
        end
      default :
        begin
          SDFController_rdState_next = 2'b00;
          SDFController_rdAddr_reg_next = 7'b0000000;
          rd_1_Enb_1 = 1'b0;
        end
    endcase
    case ( SDFController_wrState)
      2'b00 :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 7'b0000000;
          SDFController_procEnb_reg_next = 1'b0;
          if (dinXTwdl_1_1_vld) begin
            SDFController_wrState_next = 2'b01;
            SDFController_wrCount_next = 7'b0000001;
          end
        end
      2'b01 :
        begin
          SDFController_wrState_next = 2'b01;
          SDFController_procEnb_reg_next = 1'b0;
          if (dinXTwdl_1_1_vld) begin
            if (SDFController_wrCount == 7'b1111111) begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            else begin
              SDFController_wrState_next = 2'b01;
            end
            SDFController_wrCount_next = SDFController_wrCount + 7'b0000001;
          end
        end
      2'b10 :
        begin
          SDFController_wrState_next = 2'b10;
          if (dinXTwdl_1_1_vld) begin
            if (SDFController_wrCount == 7'b1111111) begin
              SDFController_wrState_next = 2'b01;
              SDFController_procEnb_reg_next = 1'b0;
            end
            else begin
              SDFController_wrState_next = 2'b10;
              SDFController_procEnb_reg_next = 1'b1;
            end
            SDFController_wrCount_next = SDFController_wrCount + 7'b0000001;
          end
        end
      default :
        begin
          SDFController_wrState_next = 2'b00;
          SDFController_wrCount_next = 7'b1111111;
          SDFController_procEnb_reg_next = 1'b0;
        end
    endcase
    rd_1_Addr_1 = SDFController_rdAddr_reg;
    proc_1_enb_1 = SDFController_procEnb_reg;
    multiply_1_J = SDFController_multiply_J_reg;
  end

  assign rd_1_Addr = rd_1_Addr_1;

  assign rd_1_Enb = rd_1_Enb_1;

  assign proc_1_enb = proc_1_enb_1;

endmodule  // RADIX22FFT_CTRL1_1

