// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/RADIX22FFT_SDF1_7.sv
// Created: 2026-06-20 03:33:58
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Transmitter_pkg::* ;

// -------------------------------------------------------------
// 
// Module: RADIX22FFT_SDF1_7
// Source Path: introOFDMTransmitter/OFDM Transmitter/OFDM Modulator/dsphdl.IFFT/RADIX22FFT_SDF1_7
// Hierarchy Level: 3
// Model version: 10.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module RADIX22FFT_SDF1_7
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [21:0] din_7_1_re_dly  /* sfix22_En15 */,
             input logic signed [21:0] din_7_1_im_dly  /* sfix22_En15 */,
             input logic din_7_vld_dly,
             input logic rd_7_Addr  /* ufix1 */,
             input logic rd_7_Enb,
             input logic signed [15:0] twdl_7_1_re  /* sfix16_En14 */,
             input logic signed [15:0] twdl_7_1_im  /* sfix16_En14 */,
             input logic proc_7_enb,
             output logic signed [22:0] dout_7_1_re  /* sfix23_En15 */,
             output logic signed [22:0] dout_7_1_im  /* sfix23_En15 */,
             output logic dout_7_1_vld,
             output logic dinXTwdl_7_1_vld);


  logic signed [22:0] din_re;  /* sfix23_En15 */
  logic signed [22:0] din_im;  /* sfix23_En15 */
  logic signed [22:0] dinXTwdl_re;  /* sfix23_En15 */
  logic signed [22:0] dinXTwdl_im;  /* sfix23_En15 */
  logic x_vld;
  logic signed [22:0] wrData_re;  /* sfix23_En15 */
  logic signed [22:0] wrData_im;  /* sfix23_En15 */
  logic wrAddr;  /* ufix1 */
  logic wrEnb;
  logic signed [22:0] twoLocationReg_0_MEM_re_0;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_0;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_re_1;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_im_1;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_re_reg;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_dout_im_reg;  /* sfix23 */
  logic signed [22:0] twoLocationReg_0_MEM_re_0_next;  /* sfix23_En15 */
  logic signed [22:0] twoLocationReg_0_MEM_im_0_next;  /* sfix23_En15 */
  logic signed [22:0] twoLocationReg_0_MEM_re_1_next;  /* sfix23_En15 */
  logic signed [22:0] twoLocationReg_0_MEM_im_1_next;  /* sfix23_En15 */
  logic signed [22:0] twoLocationReg_0_dout_re_reg_next;  /* sfix23_En15 */
  logic signed [22:0] twoLocationReg_0_dout_im_reg_next;  /* sfix23_En15 */
  logic signed [22:0] x_re;  /* sfix23_En15 */
  logic signed [22:0] x_im;  /* sfix23_En15 */
  logic signed [23:0] Radix22ButterflyG1_btf1_re_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG1_btf1_im_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG1_btf2_re_reg;  /* sfix24 */
  logic signed [23:0] Radix22ButterflyG1_btf2_im_reg;  /* sfix24 */
  logic signed [22:0] Radix22ButterflyG1_x_re_dly1;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG1_x_im_dly1;  /* sfix23 */
  logic Radix22ButterflyG1_x_vld_dly1;
  logic signed [22:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  /* sfix23 */
  logic signed [22:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  /* sfix23 */
  logic Radix22ButterflyG1_dinXtwdl_vld_dly1;
  logic Radix22ButterflyG1_dinXtwdl_vld_dly2;
  logic signed [23:0] Radix22ButterflyG1_btf1_re_reg_next;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_btf1_im_reg_next;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_btf2_re_reg_next;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_btf2_im_reg_next;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_add_cast;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_add_cast_1;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_sub_cast;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_sub_cast_1;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_add_cast_2;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_add_cast_3;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_sub_cast_2;  /* sfix24_En15 */
  logic signed [23:0] Radix22ButterflyG1_sub_cast_3;  /* sfix24_En15 */
  logic signed [22:0] xf_re;  /* sfix23_En15 */
  logic signed [22:0] xf_im;  /* sfix23_En15 */
  logic xf_vld;
  logic signed [22:0] dinXTwdlf_re;  /* sfix23_En15 */
  logic signed [22:0] dinXTwdlf_im;  /* sfix23_En15 */
  logic dinxTwdlf_vld;
  logic signed [22:0] btf1_re;  /* sfix23_En15 */
  logic signed [22:0] btf1_im;  /* sfix23_En15 */
  logic signed [22:0] btf2_re;  /* sfix23_En15 */
  logic signed [22:0] btf2_im;  /* sfix23_En15 */
  logic btf_vld;


  assign din_re = {din_7_1_re_dly[21], din_7_1_re_dly};

  assign din_im = {din_7_1_im_dly[21], din_7_1_im_dly};

  Complex4Multiply_block1 u_MUL4 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .din_re(din_re),  /* sfix23_En15 */
                                  .din_im(din_im),  /* sfix23_En15 */
                                  .din_7_vld_dly(din_7_vld_dly),
                                  .twdl_7_1_re(twdl_7_1_re),  /* sfix16_En14 */
                                  .twdl_7_1_im(twdl_7_1_im),  /* sfix16_En14 */
                                  .dinXTwdl_re(dinXTwdl_re),  /* sfix23_En15 */
                                  .dinXTwdl_im(dinXTwdl_im),  /* sfix23_En15 */
                                  .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                  );

  always_ff @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_7_Enb;
        end
      end
    end

  // twoLocationReg_0
  always_ff @(posedge clk)
    begin : twoLocationReg_0_process
      if (reset == 1'b1) begin
        twoLocationReg_0_MEM_re_0 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_im_0 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_re_1 <= 23'sb00000000000000000000000;
        twoLocationReg_0_MEM_im_1 <= 23'sb00000000000000000000000;
        twoLocationReg_0_dout_re_reg <= 23'sb00000000000000000000000;
        twoLocationReg_0_dout_im_reg <= 23'sb00000000000000000000000;
      end
      else begin
        if (enb) begin
          twoLocationReg_0_MEM_re_0 <= twoLocationReg_0_MEM_re_0_next;
          twoLocationReg_0_MEM_im_0 <= twoLocationReg_0_MEM_im_0_next;
          twoLocationReg_0_MEM_re_1 <= twoLocationReg_0_MEM_re_1_next;
          twoLocationReg_0_MEM_im_1 <= twoLocationReg_0_MEM_im_1_next;
          twoLocationReg_0_dout_re_reg <= twoLocationReg_0_dout_re_reg_next;
          twoLocationReg_0_dout_im_reg <= twoLocationReg_0_dout_im_reg_next;
        end
      end
    end

  always_comb begin
    twoLocationReg_0_MEM_re_0_next = twoLocationReg_0_MEM_re_0;
    twoLocationReg_0_MEM_im_0_next = twoLocationReg_0_MEM_im_0;
    twoLocationReg_0_MEM_re_1_next = twoLocationReg_0_MEM_re_1;
    twoLocationReg_0_MEM_im_1_next = twoLocationReg_0_MEM_im_1;
    if (rd_7_Addr == 1'b1) begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_1;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_1;
    end
    else begin
      twoLocationReg_0_dout_re_reg_next = twoLocationReg_0_MEM_re_0;
      twoLocationReg_0_dout_im_reg_next = twoLocationReg_0_MEM_im_0;
    end
    if (wrEnb) begin
      if (wrAddr == 1'b1) begin
        twoLocationReg_0_MEM_re_1_next = wrData_re;
        twoLocationReg_0_MEM_im_1_next = wrData_im;
      end
      else begin
        twoLocationReg_0_MEM_re_0_next = wrData_re;
        twoLocationReg_0_MEM_im_0_next = wrData_im;
      end
    end
    x_re = twoLocationReg_0_dout_re_reg;
    x_im = twoLocationReg_0_dout_im_reg;
  end

  // Radix22ButterflyG1
  always_ff @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 24'sb000000000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 23'sb00000000000000000000000;
        xf_im <= 23'sb00000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 23'sb00000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_7_enb && dinXTwdl_7_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_7_enb) && dinXTwdl_7_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[22], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[22], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[22], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[22], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[22], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[22], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[22], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[22], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[22:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[22:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[22:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[22:0];

  SDFCommutator7 u_SDFCOMMUTATOR_7 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_7_vld_dly(din_7_vld_dly),
                                    .xf_re(xf_re),  /* sfix23_En15 */
                                    .xf_im(xf_im),  /* sfix23_En15 */
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  /* sfix23_En15 */
                                    .dinXTwdlf_im(dinXTwdlf_im),  /* sfix23_En15 */
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  /* sfix23_En15 */
                                    .btf1_im(btf1_im),  /* sfix23_En15 */
                                    .btf2_re(btf2_re),  /* sfix23_En15 */
                                    .btf2_im(btf2_im),  /* sfix23_En15 */
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  /* sfix23_En15 */
                                    .wrData_im(wrData_im),  /* sfix23_En15 */
                                    .wrAddr(wrAddr),  /* ufix1 */
                                    .wrEnb(wrEnb),
                                    .dout_7_1_re(dout_7_1_re),  /* sfix23_En15 */
                                    .dout_7_1_im(dout_7_1_im),  /* sfix23_En15 */
                                    .dout_7_1_vld(dout_7_1_vld)
                                    );

endmodule  // RADIX22FFT_SDF1_7

