// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_tx/introOFDMTransmitter/Resource_Element_Type.sv
// Created: 2026-06-20 03:33:58
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Transmitter_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Resource_Element_Type
// Source Path: introOFDMTransmitter/OFDM Transmitter/Grid Structure/Resource Element Type
// Hierarchy Level: 2
// Model version: 10.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Resource_Element_Type
          (  input logic [7:0] scNum  /* uint8 */,
             input logic [7:0] symNum  /* uint8 */,
             input logic validIn,
             output logic isSyncSeq,
             output logic isRef,
             output logic isData);


  logic Compare_To_Constant2_out1;
  logic [7:0] Constant_out1;  /* uint8 */
  logic Relational_Operator_out1;
  logic [7:0] Constant2_out1;  /* uint8 */
  logic Relational_Operator1_out1;
  logic AND3_out1;
  logic [1:0] Bit_Slice_out1;  /* ufix2 */
  logic Compare_To_Constant_out1;
  logic NOT_out1;
  logic AND1_out1;
  logic Compare_To_Constant1_out1;
  logic AND2_out1;


  assign Compare_To_Constant2_out1 = symNum == 8'b00000000;

  assign Constant_out1 = 8'b00110010;

  assign Relational_Operator_out1 = scNum >= Constant_out1;

  assign Constant2_out1 = 8'b10110000;

  assign Relational_Operator1_out1 = scNum <= Constant2_out1;

  assign AND3_out1 = Relational_Operator1_out1 & (Relational_Operator_out1 & (validIn & Compare_To_Constant2_out1));

  assign isSyncSeq = AND3_out1;

  assign Bit_Slice_out1 = symNum[1:0];

  assign Compare_To_Constant_out1 = Bit_Slice_out1 == 2'b01;

  assign NOT_out1 =  ~ Compare_To_Constant2_out1;

  assign AND1_out1 = NOT_out1 & (validIn & Compare_To_Constant_out1);

  assign isRef = AND1_out1;

  assign Compare_To_Constant1_out1 = Bit_Slice_out1 != 2'b01;

  assign AND2_out1 = NOT_out1 & (validIn & Compare_To_Constant1_out1);

  assign isData = AND2_out1;

endmodule  // Resource_Element_Type

