//
// Copyright 2026 <author>
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// Module: rfnoc_block_ofdm_tx_sl_tb
//
// Description: Testbench for the ofdm_tx_sl RFNoC block.
//

`default_nettype none


module rfnoc_block_ofdm_tx_sl_tb;

  `include "test_exec.svh"

  import PkgTestExec::*;
  import rfnoc_chdr_utils_pkg::*;
  import PkgChdrData::*;
  import PkgRfnocBlockCtrlBfm::*;
  import PkgRfnocItemUtils::*;

  //---------------------------------------------------------------------------
  // Testbench Configuration
  //---------------------------------------------------------------------------

  localparam [31:0] NOC_ID          = 32'hFF2494FF;
  localparam [ 9:0] THIS_PORTID     = 10'h123;
  localparam int    CHDR_W          = 64;    // CHDR size in bits
  localparam int    MTU             = 10;    // Log2 of max transmission unit in CHDR words
  localparam int    NUM_PORTS_I     = 1;
  localparam int    NUM_PORTS_O     = 1;
  localparam int    ITEM_W          = 32;    // Sample size in bits
  localparam int    SPP             = 64;    // Samples per packet
  localparam int    PKT_SIZE_BYTES  = SPP * (ITEM_W/8);
  localparam int    STALL_PROB      = 25;    // Default BFM stall probability
  // Clock periods match the X440 X4_200 hardware image:
  //   rfnoc_chdr_clk : CHDR_CLK_RATE = 200 MHz       (x4xx.sv)
  //   rfnoc_ctrl_clk : clk40         = 40 MHz        (x4xx.sv)
  //   ce_clk         : clk200*4/3    = 266.667 MHz   (x4xx.sv ce_clk_gen, fixed,
  //                    independent of the 250 MHz master clock rate). The block
  //                    derives a 250 MHz clock (ce_250) from ce_clk with an
  //                    internal MMCM and runs the OFDM core + data path in that
  //                    250 MHz domain, so ce_clk only feeds the MMCM here.
  localparam real   CHDR_CLK_PER    = 5.0;    // 200 MHz
  localparam real   CTRL_CLK_PER    = 25.0;   // 40 MHz
  localparam real   CE_CLK_PER      = 3.75;   // 266.667 MHz

  // Client register map (matches rfnoc_block_ofdm_tx_sl.sv). These are raw
  // CtrlPort addresses; the BFM passes the address straight through to
  // m_ctrlport_req_addr, which the block decodes against these literals.
  localparam int    REG_TX_PAYLOAD_READY_ADDR = 0;  // RO: txPayload input ready
  localparam int    REG_ENABLE_ADDR           = 1;  // RW: OFDM transmitter enable

  // Stimulus configuration
  //
  // The txPayload input port carries one int8 sample per byte, but only the
  // two LSBs are used by the block (bit[0] -> txPayload_0, bit[1] -> txPayload_1,
  // i.e. the QPSK I/Q bits). We feed NUM_TX_SAMPS samples, gating on the
  // txPayloadReady status register, then assert "enable" so the block starts
  // emitting modulated sc16 samples on its output port.
  localparam int    NUM_TX_SAMPS    = 40812;  // int8 payload samples to feed
  localparam int    NUM_RX_SAMPS    = 76800;  // sc16 output samples to capture

  // Golden-reference comparison. The expected sc16 output and the matching
  // payload stimulus are generated by the MATLAB reference (runIntroOFDMML.m,
  // variable txWaveformML) and exported as hex (one value per line):
  //   - INPUT_FILE:    one payload sample per line, "%02X" (bit0->txPayload_0,
  //                    bit1->txPayload_1, i.e. the QPSK I/Q bits).
  //   - EXPECTED_FILE: one sc16 output word per line, "%08X" = {I[31:16],Q[15:0]},
  //                    Q1.15 fixed point (1.0 -> 32768).
  // The MATLAB and FPGA datapaths are not bit-exact, so each captured I/Q value
  // is allowed to deviate by TOL_LSB. The spec is +-0.001 in the normalized
  // double domain, which is 0.001*32768 ~= 32.77 LSBs in Q1.15 -> 33.
  // xsim's run directory is deep inside the Vivado sim project, so reference the
  // vectors (which live next to this testbench) by absolute path.
  localparam string VEC_DIR =
    "/home/peter/git/oot_tum/rfnoc-oot_tum/rfnoc/fpga/oot_tum/rfnoc_block_ofdm_tx_sl/";
  localparam string INPUT_FILE      = {VEC_DIR, "ofdm_tx_input.hex"};
  localparam string EXPECTED_FILE   = {VEC_DIR, "ofdm_tx_expected.hex"};
  localparam int    TOL_LSB         = 33;

  // Spectral-windowing overlap length, in output samples. The OFDM modulator
  // tapers each symbol with a raised-cosine window and overlap-adds the
  // ramp-down tail of the previous symbol onto the ramp-up head of the next
  // (WindowingSysObj, 9-deep overlap buffers). Consequently the first
  // WINDOW_OVERLAP samples of any frame whose predecessor was not flushed carry
  // a (ramp_down * previous-frame tail) term. This is mathematically correct
  // continuous windowed-OFDM behavior; the standalone MATLAB golden assumes a
  // zero history, which only the first post-reset frame satisfies. For a frame
  // that follows another (e.g. frame 2 across a payload gap) we therefore skip
  // these leading overlap samples in the golden comparison.
  localparam int    WINDOW_OVERLAP  = 9;

  // Memories loaded from the MATLAB reference files.
  logic [ 7:0] input_mem    [NUM_TX_SAMPS];
  logic [31:0] expected_mem [NUM_RX_SAMPS];

  //---------------------------------------------------------------------------
  // Clocks and Resets
  //---------------------------------------------------------------------------

  bit rfnoc_chdr_clk;
  bit rfnoc_ctrl_clk;
  bit ce_clk;

  sim_clock_gen #(CHDR_CLK_PER) rfnoc_chdr_clk_gen (.clk(rfnoc_chdr_clk), .rst());
  sim_clock_gen #(CTRL_CLK_PER) rfnoc_ctrl_clk_gen (.clk(rfnoc_ctrl_clk), .rst());
  sim_clock_gen #(CE_CLK_PER) ce_clk_gen (.clk(ce_clk), .rst());

  //---------------------------------------------------------------------------
  // Continuous Radio Sink Model (hardware-faithful capture path)
  //---------------------------------------------------------------------------
  //
  // The default capture path (recv_items via the slave BFM) reads only on
  // tvalid && tready, so it *compacts* the stream and can never see a starved
  // radio. On hardware (transceiver.py) the block output is transmitted by the
  // radio's TX, which runs at a *fixed* 250 MHz and consumes one sample every
  // cycle whether or not the block has produced one. When the radio's TX FIFO
  // empties it underflows and transmits stale/garbage (not the block's data),
  // which is exactly the corruption transceiver.py observes.
  //
  // This model reproduces that sink:
  //   * RADIO_CLK runs at 250 MHz (the radio sample clock; note ce_clk is
  //     266.667 MHz, so the radio is the slower, rate-setting consumer).
  //   * radio_fifo models the radio TX buffer. The feeder pushes block output
  //     into it and *blocks when it is full*, so the radio rate backpressures
  //     the block exactly like CHDR flow control does on hardware.
  //   * Every radio cycle the radio pops one sample; on empty it records an
  //     underflow (a non-zero garbage marker, as hardware does) instead.
  //
  // A correctly-rate-matched block keeps the FIFO non-empty after priming, so
  // the radio sees zero mid-stream underflows and captures golden in order. A
  // block that cannot sustain 250 MHz starves the radio and the capture is
  // corrupted -- the hardware failure.
  localparam real RADIO_CLK_PER       = 4.0;     // 250 MHz radio sample clock
  localparam int  RADIO_TX_FIFO_DEPTH = 8192;    // modeled radio TX buffer depth
  localparam logic [31:0] RADIO_UNDERFLOW_FILL = 32'hDEAD_DEAD;  // non-zero, like HW

  bit radio_clk;
  sim_clock_gen #(RADIO_CLK_PER) radio_clk_gen (.clk(radio_clk), .rst());

  logic [31:0] radio_fifo [$];   // radio TX FIFO (block writes, radio drains)
  logic [31:0] radio_cap  [$];   // what the radio transmits each cycle (with fills)
  bit          radio_run = 1'b0; // start draining once the FIFO has primed
  int          radio_underflows_mid = 0;  // underflow cycles after priming
  logic [31:0] radio_last = 32'b0;

  // Radio TX: one sample per 250 MHz cycle, underflow-fill on empty.
  always @(posedge radio_clk) begin
    if (radio_run) begin
      if (radio_fifo.size() > 0) begin
        radio_last = radio_fifo.pop_front();
        radio_cap.push_back(radio_last);
      end else begin
        radio_cap.push_back(RADIO_UNDERFLOW_FILL);
        radio_underflows_mid++;
      end
    end
  end

  //---------------------------------------------------------------------------
  // OFDM demodulator (subcarrier-integrity self-check)
  //---------------------------------------------------------------------------
  //
  // The golden-reference tests prove the datapath against a *fixed* MATLAB
  // payload. Constant or period-4 payloads are immune to dropped / duplicated /
  // mis-timed payload reads (every byte is identical, or repeats every 4), so
  // they can pass even when the payload->subcarrier delivery is broken -- which
  // is exactly the failure seen on hardware (data subcarriers carry the correct
  // power on the correct bins but *random* bits). This demodulator lets a test
  // feed an *arbitrary* payload and verify, per subcarrier, that the modulated
  // QPSK bits equal the bits that were fed -- no golden file required.
  //
  // Recovered convention (reverse-engineered from the golden input/output pair
  // and validated to decode golden -> input at 100%): drop the 64-sample CP,
  // take the 256-pt DFT, read the 228 data bins in fft-shifted order (negative
  // freqs 142..255, then positive freqs 0..113); per bin b0 = (Re < 0), b1 =
  // (Im < 0), payload byte = {b1, b0}. I is the upper sc16 half, Q the lower.
  localparam int  FFT_LEN_C   = 256;
  localparam int  CP_LEN_C    = 64;
  localparam int  SPS_C       = FFT_LEN_C + CP_LEN_C;  // 320
  localparam int  N_DATA_BINS = 228;
  localparam real TWO_PI      = 6.28318530717958647692;
  // How many data symbols the demod check covers. A payload-delivery bug shows
  // in the first data symbols (and accumulates), so a prefix suffices and keeps
  // the DFT cost down; raise toward 179 (all data symbols/frame) for an
  // exhaustive check.
  localparam int  DEMOD_SYMS_TO_CHECK = 40;

  real demod_cos [FFT_LEN_C];
  real demod_sin [FFT_LEN_C];
  int  demod_bins [N_DATA_BINS];
  logic [31:0] demod_cap [$];   // captured sc16 output for the demod check

  initial begin : init_demod_tables
    int idx;
    for (int m = 0; m < FFT_LEN_C; m++) begin
      demod_cos[m] = $cos(TWO_PI * m / FFT_LEN_C);
      demod_sin[m] = $sin(TWO_PI * m / FFT_LEN_C);
    end
    idx = 0;
    for (int k = 142; k < 256; k++) demod_bins[idx++] = k;  // negative freqs
    for (int k = 0;   k < 114; k++) demod_bins[idx++] = k;  // positive freqs
  end

  //---------------------------------------------------------------------------
  // Bus Functional Models
  //---------------------------------------------------------------------------

  // Backend Interface
  RfnocBackendIf backend (rfnoc_chdr_clk, rfnoc_ctrl_clk);

  // AXIS-Ctrl Interface
  AxiStreamIf #(32) m_ctrl (rfnoc_ctrl_clk, 1'b0);
  AxiStreamIf #(32) s_ctrl (rfnoc_ctrl_clk, 1'b0);

  // AXIS-CHDR Interfaces
  AxiStreamIf #(CHDR_W) m_chdr [NUM_PORTS_I] (rfnoc_chdr_clk, 1'b0);
  AxiStreamIf #(CHDR_W) s_chdr [NUM_PORTS_O] (rfnoc_chdr_clk, 1'b0);

  // Block Controller BFM
  RfnocBlockCtrlBfm #(CHDR_W, ITEM_W) blk_ctrl = new(backend, m_ctrl, s_ctrl);

  // CHDR word and item/sample data types
  typedef ChdrData #(CHDR_W, ITEM_W)::chdr_word_t chdr_word_t;
  typedef ChdrData #(CHDR_W, ITEM_W)::item_t      item_t;

  // Connect block controller to BFMs
  for (genvar i = 0; i < NUM_PORTS_I; i++) begin : gen_bfm_input_connections
    initial begin
      blk_ctrl.connect_master_data_port(i, m_chdr[i], PKT_SIZE_BYTES);
      blk_ctrl.set_master_stall_prob(i, STALL_PROB);
    end
  end
  for (genvar i = 0; i < NUM_PORTS_O; i++) begin : gen_bfm_output_connections
    initial begin
      blk_ctrl.connect_slave_data_port(i, s_chdr[i]);
      blk_ctrl.set_slave_stall_prob(i, STALL_PROB);
    end
  end

  //---------------------------------------------------------------------------
  // Device Under Test (DUT)
  //---------------------------------------------------------------------------

  // DUT Slave (Input) Port Signals
  logic [CHDR_W*NUM_PORTS_I-1:0] s_rfnoc_chdr_tdata;
  logic [       NUM_PORTS_I-1:0] s_rfnoc_chdr_tlast;
  logic [       NUM_PORTS_I-1:0] s_rfnoc_chdr_tvalid;
  logic [       NUM_PORTS_I-1:0] s_rfnoc_chdr_tready;

  // DUT Master (Output) Port Signals
  logic [CHDR_W*NUM_PORTS_O-1:0] m_rfnoc_chdr_tdata;
  logic [       NUM_PORTS_O-1:0] m_rfnoc_chdr_tlast;
  logic [       NUM_PORTS_O-1:0] m_rfnoc_chdr_tvalid;
  logic [       NUM_PORTS_O-1:0] m_rfnoc_chdr_tready;

  // Map the array of BFMs to a flat vector for the DUT connections
  for (genvar i = 0; i < NUM_PORTS_I; i++) begin : gen_dut_input_connections
    // Connect BFM master to DUT slave port
    assign s_rfnoc_chdr_tdata[CHDR_W*i+:CHDR_W] = m_chdr[i].tdata;
    assign s_rfnoc_chdr_tlast[i]                = m_chdr[i].tlast;
    assign s_rfnoc_chdr_tvalid[i]               = m_chdr[i].tvalid;
    assign m_chdr[i].tready                     = s_rfnoc_chdr_tready[i];
  end
  for (genvar i = 0; i < NUM_PORTS_O; i++) begin : gen_dut_output_connections
    // Connect BFM slave to DUT master port
    assign s_chdr[i].tdata        = m_rfnoc_chdr_tdata[CHDR_W*i+:CHDR_W];
    assign s_chdr[i].tlast        = m_rfnoc_chdr_tlast[i];
    assign s_chdr[i].tvalid       = m_rfnoc_chdr_tvalid[i];
    assign m_rfnoc_chdr_tready[i] = s_chdr[i].tready;
  end

  rfnoc_block_ofdm_tx_sl #(
    .THIS_PORTID         (THIS_PORTID),
    .CHDR_W              (CHDR_W),
    .MTU                 (MTU)
  ) dut (
    .rfnoc_chdr_clk      (rfnoc_chdr_clk),
    .rfnoc_ctrl_clk      (rfnoc_ctrl_clk),
    .ce_clk              (ce_clk),
    // 250 MHz data-path clock generated inside the block (MMCM output). Left
    // open here; the block drives it.
    .ce_250_clk          (),
    .rfnoc_core_config   (backend.cfg),
    .rfnoc_core_status   (backend.sts),
    .s_rfnoc_chdr_tdata  (s_rfnoc_chdr_tdata),
    .s_rfnoc_chdr_tlast  (s_rfnoc_chdr_tlast),
    .s_rfnoc_chdr_tvalid (s_rfnoc_chdr_tvalid),
    .s_rfnoc_chdr_tready (s_rfnoc_chdr_tready),
    .m_rfnoc_chdr_tdata  (m_rfnoc_chdr_tdata),
    .m_rfnoc_chdr_tlast  (m_rfnoc_chdr_tlast),
    .m_rfnoc_chdr_tvalid (m_rfnoc_chdr_tvalid),
    .m_rfnoc_chdr_tready (m_rfnoc_chdr_tready),
    .s_rfnoc_ctrl_tdata  (m_ctrl.tdata),
    .s_rfnoc_ctrl_tlast  (m_ctrl.tlast),
    .s_rfnoc_ctrl_tvalid (m_ctrl.tvalid),
    .s_rfnoc_ctrl_tready (m_ctrl.tready),
    .m_rfnoc_ctrl_tdata  (s_ctrl.tdata),
    .m_rfnoc_ctrl_tlast  (s_ctrl.tlast),
    .m_rfnoc_ctrl_tvalid (s_ctrl.tvalid),
    .m_rfnoc_ctrl_tready (s_ctrl.tready)
  );

  //---------------------------------------------------------------------------
  // Clock Sanity Check
  //---------------------------------------------------------------------------

  // Count edges on each framework clock over a 1 us window. Expected over 1 us:
  // chdr (5 ns) -> 200, ctrl (25 ns) -> 40, ce (3.75 ns) -> ~266 (ce_clk feeds
  // the block's MMCM, which derives the 250 MHz data-path clock). A zero would
  // mean that clock is dead.
  initial begin : clk_check
    int n_chdr, n_ctrl, n_ce;
    n_chdr = 0; n_ctrl = 0; n_ce = 0;
    fork
      forever @(posedge rfnoc_chdr_clk) n_chdr++;
      forever @(posedge rfnoc_ctrl_clk) n_ctrl++;
      forever @(posedge ce_clk)         n_ce++;
    join_none
    #1000;
    $display("CLOCKCHK @1us: chdr=%0d (exp ~200) ctrl=%0d (exp ~40) ce=%0d (exp ~266)",
             n_chdr, n_ctrl, n_ce);
    `ASSERT_ERROR(n_chdr > 0 && n_ctrl > 0 && n_ce > 0,
                  "One or more framework clocks is not toggling");
  end

  //---------------------------------------------------------------------------
  // Helper Tasks
  //---------------------------------------------------------------------------

  // Read the txPayloadReady status register (bit 0).
  task automatic get_tx_payload_ready(output bit ready);
    logic [31:0] val;
    blk_ctrl.reg_read(REG_TX_PAYLOAD_READY_ADDR, val);
    ready = val[0];
  endtask : get_tx_payload_ready

  // Feed "nsamps" int8 payload samples into the txPayload input port. The
  // samples are packed one-per-byte into CHDR words (least-significant byte
  // first, so sample N maps to txPayload sample N) and streamed as a series of
  // CHDR packets sized by the master data port's PKT_SIZE_BYTES.
  //
  // Sending is throttled purely by CHDR flow control: the input FIFO drives
  // txPayloadReady, which is the tready of the txPayload AXI-Stream. When the
  // FIFO fills (occupancy >= 40812) txPayloadReady deasserts, tready drops, and
  // the BFM automatically stops sending; once the block is enabled and the FIFO
  // drains, txPayloadReady reasserts and sending resumes. This is the hardware
  // realization of "stop sending when txPayloadReady is false, resume when it
  // becomes true."
  task automatic feed_payload(input byte unsigned samples[], input int nsamps);
    chdr_word_t words[$];
    int         word_idx;
    int         byte_lane;

    // Pack every sample into a flat CHDR-word queue.
    words = {};
    for (int b = 0; b < nsamps; b++) begin
      word_idx  = b / ($bits(chdr_word_t)/8);
      byte_lane = b % ($bits(chdr_word_t)/8);
      if (byte_lane == 0) words.push_back('0);
      words[word_idx][byte_lane*8 +: 8] = samples[b];
    end

    // send_packets splits the data into max-payload-sized packets (set by
    // connect_master_data_port) and honors flow control between them.
    blk_ctrl.send_packets(0, words, nsamps);
  endtask : feed_payload

  // Receive "nsamps" sc16 output samples from the txData output port and compare
  // them against the MATLAB golden reference (expected_mem). Each 32-bit item is
  // {I[31:16], Q[15:0]}. Every I and Q value must be within TOL_LSB of the
  // expected value. Reports peak magnitude, the worst-case deviation, and the
  // number of out-of-tolerance samples, then asserts that none failed.
  //
  // Note: extract the 16-bit I/Q via explicit 16-bit regs + $signed(). A
  // signed'() cast applied directly to a part-select (signed'(rx[i][31:16]))
  // does not sign/zero-extend correctly under xsim and yields garbage.
  //
  // skip_lead: number of leading output samples to receive and count toward
  // nsamps but exclude from the golden tolerance check. Used for a frame that
  // follows another (no flush in between), whose first WINDOW_OVERLAP samples
  // legitimately carry the previous frame's windowing overlap-add tail.
  task automatic capture_output(input int nsamps, input int skip_lead = 0);
    item_t rx[$];
    int    got;
    int    peak;
    int    i_samp;
    int    q_samp;
    int    exp_i;
    int    exp_q;
    int    dev_i;
    int    dev_q;
    int    max_dev;
    int    nfail;
    int    mag;
    logic [15:0] hi16;
    logic [15:0] lo16;

    got     = 0;
    peak    = 0;
    max_dev = 0;
    nfail   = 0;
    while (got < nsamps) begin
      blk_ctrl.recv_items(0, rx);
      foreach (rx[i]) begin
        if (got >= nsamps) break;
        hi16   = rx[i][31:16];
        lo16   = rx[i][15:0];
        i_samp = $signed(hi16);
        q_samp = $signed(lo16);

        // Deviation from the golden reference. Skip the leading overlap samples
        // (skip_lead) for a frame that follows another: their windowing
        // overlap-add tail is correct continuous-TX behavior, not an error.
        if (got >= skip_lead) begin
          hi16  = expected_mem[got][31:16];
          lo16  = expected_mem[got][15:0];
          exp_i = $signed(hi16);
          exp_q = $signed(lo16);
          dev_i = i_samp - exp_i; if (dev_i < 0) dev_i = -dev_i;
          dev_q = q_samp - exp_q; if (dev_q < 0) dev_q = -dev_q;
          if (dev_i > max_dev) max_dev = dev_i;
          if (dev_q > max_dev) max_dev = dev_q;
          if (dev_i > TOL_LSB || dev_q > TOL_LSB) begin
            if (nfail < 20) begin
              $display("  MISMATCH @%0d: got (%0d, %0d) exp (%0d, %0d) dev (%0d, %0d)",
                       got, i_samp, q_samp, exp_i, exp_q, dev_i, dev_q);
            end
            nfail++;
          end
        end

        // Peak magnitude (sanity stat).
        mag = (i_samp < 0) ? -i_samp : i_samp;
        if (((q_samp < 0) ? -q_samp : q_samp) > mag) mag = (q_samp < 0) ? -q_samp : q_samp;
        if (mag > peak) peak = mag;
        got++;
      end
    end
    $display("capture_output: %0d sc16 samples, peak |IQ| = %0d", got, peak);
    $display("capture_output: max deviation = %0d LSB (tol %0d), %0d samples out of tolerance",
             max_dev, TOL_LSB, nfail);
    `ASSERT_ERROR(nfail == 0,
                  "Captured OFDM output deviates from MATLAB reference beyond tolerance");
  endtask : capture_output

  // Drain the block output through the continuous 250 MHz radio sink and
  // compare what the radio "transmits" against the golden reference, mirroring
  // transceiver.py: strip the leading underflow run, then verify the captured
  // samples in order. Mid-stream underflows mean the block starved the radio
  // (the hardware failure); they corrupt the capture and fail the test.
  task automatic capture_output_radio(input int nsamps);
    item_t  rx[$];
    int     pushed;
    int     vi;
    int     got;
    int     nfail;
    int     max_dev;
    int     dev_i;
    int     dev_q;
    int     exp_i;
    int     exp_q;
    int     i_samp;
    int     q_samp;
    logic [15:0] hi16;
    logic [15:0] lo16;
    logic [31:0] w;

    // Producer: pull packets as fast as the block emits them (BFM never the
    // bottleneck) and hand them to the radio FIFO; block when the FIFO is full
    // so the 250 MHz radio rate -- not the BFM -- backpressures the block.
    blk_ctrl.set_slave_stall_prob(0, 0);
    pushed = 0;
    while (pushed < nsamps) begin
      blk_ctrl.recv_items(0, rx);
      foreach (rx[i]) begin
        while (radio_fifo.size() >= RADIO_TX_FIFO_DEPTH) @(posedge radio_clk);
        radio_fifo.push_back(rx[i]);
        pushed++;
        // Prime the radio TX FIFO half full before it starts transmitting, like
        // a real TX that buffers before going on air.
        if (!radio_run && radio_fifo.size() >= RADIO_TX_FIFO_DEPTH/2)
          radio_run = 1'b1;
      end
    end
    // Let the radio drain what is left, then stop it so the trailing empty
    // cycles are not miscounted as underflows.
    while (radio_fifo.size() > 0) @(posedge radio_clk);
    radio_run = 1'b0;

    // Align to golden exactly like transceiver.py: the on-air stream begins with
    // a short startup transient (pipeline fill before the first golden sample),
    // so find where golden sample 0 lands by matching the first few samples,
    // then compare the contiguous overlap that follows.
    vi = -1;
    for (int off = 0; off + 8 < radio_cap.size() && off < 4096; off++) begin
      bit hit = 1'b1;
      for (int k = 0; k < 8; k++) begin
        w   = radio_cap[off+k];
        i_samp = $signed(w[31:16]); q_samp = $signed(w[15:0]);
        exp_i  = $signed(expected_mem[k][31:16]); exp_q = $signed(expected_mem[k][15:0]);
        dev_i = i_samp - exp_i; if (dev_i < 0) dev_i = -dev_i;
        dev_q = q_samp - exp_q; if (dev_q < 0) dev_q = -dev_q;
        if (dev_i > TOL_LSB || dev_q > TOL_LSB) begin hit = 1'b0; break; end
      end
      if (hit) begin vi = off; break; end
    end
    `ASSERT_ERROR(vi >= 0, "Could not align continuous-radio capture to golden");
    $display("capture_output_radio: aligned to golden at capture offset %0d", vi);

    got = 0; nfail = 0; max_dev = 0;
    while (got < nsamps && vi < radio_cap.size()) begin
      w      = radio_cap[vi]; vi++;
      hi16   = w[31:16];  lo16 = w[15:0];
      i_samp = $signed(hi16); q_samp = $signed(lo16);
      hi16   = expected_mem[got][31:16]; lo16 = expected_mem[got][15:0];
      exp_i  = $signed(hi16); exp_q = $signed(lo16);
      dev_i  = i_samp - exp_i; if (dev_i < 0) dev_i = -dev_i;
      dev_q  = q_samp - exp_q; if (dev_q < 0) dev_q = -dev_q;
      if (dev_i > max_dev) max_dev = dev_i;
      if (dev_q > max_dev) max_dev = dev_q;
      if (dev_i > TOL_LSB || dev_q > TOL_LSB) begin
        if (nfail < 20)
          $display("  RADIO MISMATCH @%0d: got (%0d, %0d) exp (%0d, %0d)",
                   got, i_samp, q_samp, exp_i, exp_q);
        nfail++;
      end
      got++;
    end

    $display("capture_output_radio: compared %0d samples, %0d mid-stream radio underflow cycles",
             got, radio_underflows_mid);
    $display("capture_output_radio: max deviation = %0d LSB (tol %0d), %0d/%0d out of tolerance",
             max_dev, TOL_LSB, nfail, got);
    `ASSERT_ERROR(radio_underflows_mid == 0,
                  "Radio underflowed mid-stream: block cannot sustain the 250 MHz radio rate");
    `ASSERT_ERROR(nfail == 0,
                  "Continuous-radio capture deviates from MATLAB reference beyond tolerance");
  endtask : capture_output_radio

  // True for a payload-bearing data symbol (0-based index). Symbol 1 is sync and
  // every 4th symbol from 2 (refOFDMIdx = 2,6,10,...) is a reference symbol; both
  // are payload-independent and carry no payload bits.
  function automatic bit symbol_is_data(input int s0);
    int s1;
    s1 = s0 + 1;
    if (s1 == 1)              return 1'b0;
    if (((s1 - 2) % 4) == 0)  return 1'b0;
    return 1'b1;
  endfunction : symbol_is_data

  // Capture nsamps sc16 output items into demod_cap. Uses the compacted recv path
  // (reads only on tvalid && tready), which is aligned to golden output sample 0
  // exactly like capture_output. Output backpressure is governed by the caller's
  // slave stall probability, so a parallel "adversary" can hammer tready to
  // stress the core's clk_enable freeze/resume path while this collects.
  task automatic capture_collect(input int nsamps);
    item_t rx[$];
    int    got;
    demod_cap = {};
    got = 0;
    while (got < nsamps) begin
      blk_ctrl.recv_items(0, rx);
      foreach (rx[i]) begin
        if (got >= nsamps) break;
        demod_cap.push_back(rx[i]);
        got++;
      end
    end
  endtask : capture_collect

  // Demodulate the first n_data_syms_check data symbols of demod_cap and assert
  // every recovered QPSK bit-pair equals the fed payload byte. align0 is the
  // demod_cap index of golden output sample 0 (0 for the compacted recv path).
  task automatic demod_check_payload(input int align0,
                                     input byte unsigned fed[],
                                     input int n_data_syms_check);
    real xr [FFT_LEN_C];
    real xi [FFT_LEN_C];
    real re_acc;
    real im_acc;
    int  pp;
    int  dsyms;
    int  nfail;
    int  total;
    int  base;
    int  k;
    int  m;
    logic [31:0] w;
    logic [15:0] hi16;
    logic [15:0] lo16;
    byte unsigned rec;
    byte unsigned exp_b;

    pp = 0; dsyms = 0; nfail = 0; total = 0;
    for (int s = 0; s < 240; s++) begin
      if (!symbol_is_data(s)) continue;
      if (dsyms >= n_data_syms_check) begin pp += N_DATA_BINS; continue; end

      // CP-stripped FFT window for this symbol. Use explicit 16-bit regs +
      // $signed() (a $signed cast on a part-select yields garbage under xsim).
      base = align0 + s*SPS_C + CP_LEN_C;
      for (int n = 0; n < FFT_LEN_C; n++) begin
        w     = demod_cap[base + n];
        hi16  = w[31:16];  lo16 = w[15:0];
        xr[n] = $itor($signed(hi16));   // I (upper sc16 half)
        xi[n] = $itor($signed(lo16));   // Q (lower sc16 half)
      end

      // 256-pt DFT at each data bin (e^-j convention, matching numpy fft), QPSK
      // demap, compare to the fed payload byte for this subcarrier.
      for (int i = 0; i < N_DATA_BINS; i++) begin
        k = demod_bins[i];
        re_acc = 0.0; im_acc = 0.0;
        for (int n = 0; n < FFT_LEN_C; n++) begin
          m = (k*n) % FFT_LEN_C;
          re_acc += xr[n]*demod_cos[m] + xi[n]*demod_sin[m];
          im_acc += xi[n]*demod_cos[m] - xr[n]*demod_sin[m];
        end
        rec   = ((re_acc < 0.0) ? 8'd1 : 8'd0) | ((im_acc < 0.0) ? 8'd2 : 8'd0);
        exp_b = fed[pp + i] & 8'h3;
        total++;
        if (rec !== exp_b) begin
          if (nfail < 20)
            $display("  DEMOD MISMATCH data-sym %0d bin %0d: rec=%0d exp=%0d (re=%.0f im=%.0f)",
                     s+1, k, rec, exp_b, re_acc, im_acc);
          nfail++;
        end
      end
      pp += N_DATA_BINS;
      dsyms++;
    end
    $display("demod_check_payload: %0d data symbols, %0d/%0d subcarrier bit-pairs mismatched",
             dsyms, nfail, total);
    `ASSERT_ERROR(nfail == 0,
        "Demodulated subcarrier bits do not match the fed payload (payload-delivery bug)");
  endtask : demod_check_payload

  //---------------------------------------------------------------------------
  // Main Test Process
  //---------------------------------------------------------------------------

  initial begin : tb_main

    // Initialize the test exec object for this testbench
    test.start_tb("rfnoc_block_ofdm_tx_sl_tb", 100ms);

    // Load the MATLAB golden-reference stimulus and expected output.
    $readmemh(INPUT_FILE, input_mem);
    $readmemh(EXPECTED_FILE, expected_mem);

    // Start the BFMs running
    blk_ctrl.run();

    //--------------------------------
    // Wait for the block's 250 MHz data-path clock to come up
    //--------------------------------
    //
    // The block derives its ce_250 data-path clock from ce_clk with an internal
    // MMCM. On hardware the MMCM locks within milliseconds of FPGA
    // configuration -- long before UHD ever talks to the block. In simulation
    // the lock takes a non-trivial amount of modeled time, and the data-path
    // flush in flush_and_reset spans the ce_250 domain, so it cannot complete
    // until the MMCM has locked. Wait for lock here (mirroring the hardware
    // power-up ordering) before exercising any flush/reset.
    // Level-sensitive wait (no fork/disable, so the BFM processes started by
    // run() are untouched). If the clock never comes up, the global start_tb
    // timeout catches it.
    $display("Waiting for ce_250 MMCM to lock...");
    wait (dut.ce_250_locked === 1'b1);
    $display("ce_250 MMCM locked at t=%0t", $time);

    // Coordinated reset after the ce_250 clock is up. The block's chdr<->ce_250
    // CDC FIFOs (in the NoC shell) must be reset on both sides with both clocks
    // running. At power-up the chdr side reset before ce_250_clk existed (it
    // only starts once the MMCM locks), so issue a chdr-path reset here to
    // re-initialize those FIFOs cleanly. On hardware the MMCM is locked long
    // before UHD ever talks to the block, so this ordering is automatic.
    blk_ctrl.reset_chdr();

    //--------------------------------
    // Reset
    //--------------------------------

    test.start_test("Flush block then reset it", 10us);
    blk_ctrl.flush_and_reset();
    test.end_test();

    //--------------------------------
    // Verify Block Info
    //--------------------------------

    test.start_test("Verify Block Info", 2us);
    `ASSERT_ERROR(blk_ctrl.get_noc_id() == NOC_ID, "Incorrect NOC_ID Value");
    `ASSERT_ERROR(blk_ctrl.get_num_data_i() == NUM_PORTS_I, "Incorrect NUM_DATA_I Value");
    `ASSERT_ERROR(blk_ctrl.get_num_data_o() == NUM_PORTS_O, "Incorrect NUM_DATA_O Value");
    `ASSERT_ERROR(blk_ctrl.get_mtu() == MTU, "Incorrect MTU Value");
    test.end_test();

    //--------------------------------
    // Test Sequences
    //--------------------------------

    begin : test_feed_enable_capture
      byte unsigned tx_samples[];
      logic [31:0]  enable_rb;
      bit           ready_rb;

      test.start_test("Feed payload, fill FIFO, enable, capture OFDM output", 50ms);

      // Use the MATLAB reference payload (loaded into input_mem). Only the two
      // LSBs are used by the block (QPSK I/Q bits); the file already encodes
      // bit0 -> txPayload_0, bit1 -> txPayload_1.
      tx_samples = new[NUM_TX_SAMPS];
      foreach (tx_samples[i]) begin
        tx_samples[i] = input_mem[i];
      end

      // Make sure the block starts disabled so the input FIFO can fill without
      // being drained (pops require enable). No output is produced until we
      // enable the transmitter.
      blk_ctrl.reg_write(REG_ENABLE_ADDR, 0);

      // Feed the payload and assert "enable" once the FIFO has filled.
      //
      //  - The producer streams all NUM_TX_SAMPS samples. Once the input FIFO
      //    fills (occupancy >= 40812) txPayloadReady deasserts and the BFM
      //    stalls automatically; the remaining samples flush only after enable
      //    drains the FIFO and txPayloadReady reasserts.
      //  - The enabler waits for the FIFO-full condition (txPayloadReady low),
      //    holds off 50 ce_clk cycles, then writes the enable register so the
      //    block starts modulating and emitting output samples.
      fork
        begin : producer
          feed_payload(tx_samples, NUM_TX_SAMPS);
        end
        begin : enabler
          // Ensure we start from the ready (FIFO not full) state, then wait for
          // the block to report the FIFO is full.
          wait (dut.m_txPayload_axis_tready === 1'b1);
          wait (dut.m_txPayload_axis_tready === 1'b0);
          $display("Input FIFO full (txPayloadReady low); enabling in 50 cycles");
          repeat (50) @(posedge ce_clk);
          blk_ctrl.reg_write(REG_ENABLE_ADDR, 1);
        end
      join

      // Confirm the enable register took effect.
      blk_ctrl.reg_read(REG_ENABLE_ADDR, enable_rb);
      `ASSERT_ERROR(enable_rb[0] == 1'b1, "enable register did not read back as set");

      // Sustained-backpressure regression. The OFDM_Transmitter core has no
      // output-ready port; it can only be stalled via clk_enable. On hardware
      // the radio applies *sustained* (not random) backpressure at 250 MHz while
      // the core runs at ce_clk (266.667 MHz), so a small output FIFO fills and
      // -- if clk_enable is not gated by s_txData_axis_tready -- every overflow
      // silently drops a sample, corrupting the frame from ~symbol 2 onward.
      // The default BFM only stalls randomly (STALL_PROB), which averages out
      // and never sustains "full", so it misses this. Apply the stall here,
      // right after enable, while the core is starting to stream output and the
      // output FIFO is the only buffer: hold the slave tready low long enough to
      // overflow any reasonable FIFO, then resume. With proper backpressure
      // (clk_enable = s_txData_axis_tready) the core just freezes and no samples
      // are lost, so the capture below still matches golden bit-for-bit; with the
      // bug, the dropped samples make capture_output fail mid-frame.
      blk_ctrl.set_slave_stall_prob(0, 100);  // never assert tready: sustained full
      repeat (4096) @(posedge ce_clk);        // >> any plausible output FIFO depth
      blk_ctrl.set_slave_stall_prob(0, STALL_PROB);

      // Completion of feed_payload above already proves the stall resumed (the
      // last samples could only be accepted after enable drained the FIFO). As
      // a final check, wait for txPayloadReady to settle back to true now that
      // all input has been consumed and no more is being pushed.
      do begin
        get_tx_payload_ready(ready_rb);
      end while (!ready_rb);

      // Capture the modulated OFDM output and compare against the reference.
      capture_output(NUM_RX_SAMPS);

      test.end_test();
    end : test_feed_enable_capture

    begin : test_continuous_radio_sink
      byte unsigned tx_samples[];
      bit           ready_rb;

      test.start_test("Feed, enable, capture through continuous 250 MHz radio sink", 80ms);

      tx_samples = new[NUM_TX_SAMPS];
      foreach (tx_samples[i]) tx_samples[i] = input_mem[i];

      // Start from a clean slate: flush any residual frame-1 samples out of the
      // block and BFM so this capture aligns to golden sample 0.
      blk_ctrl.reg_write(REG_ENABLE_ADDR, 0);
      blk_ctrl.flush_and_reset();

      // Reset the radio-sink model state for this run.
      radio_fifo            = {};
      radio_cap             = {};
      radio_run             = 1'b0;
      radio_underflows_mid  = 0;

      fork
        begin : producer2
          feed_payload(tx_samples, NUM_TX_SAMPS);
        end
        begin : enabler2
          wait (dut.m_txPayload_axis_tready === 1'b1);
          wait (dut.m_txPayload_axis_tready === 1'b0);
          repeat (50) @(posedge ce_clk);
          blk_ctrl.reg_write(REG_ENABLE_ADDR, 1);
        end
        begin : sink2
          // Capture the whole frame through the continuous radio sink.
          capture_output_radio(NUM_RX_SAMPS);
        end
      join

      do begin
        get_tx_payload_ready(ready_rb);
      end while (!ready_rb);

      test.end_test();
    end : test_continuous_radio_sink

    begin : test_frame_gating_recovery
      byte unsigned tx_samples[];
      longint       gap_valid_cnt;

      test.start_test("Frame gating: two frames across a payload gap, both golden", 80ms);

      tx_samples = new[NUM_TX_SAMPS];
      foreach (tx_samples[i]) tx_samples[i] = input_mem[i];

      // Clean slate, then enable. The frame-gating FSM holds the core (its
      // 'enable' input, run_frame) low until a full frame of payload is buffered,
      // so enabling before any payload is present is safe -- no output is emitted
      // until a whole frame is queued.
      blk_ctrl.reg_write(REG_ENABLE_ADDR, 0);
      blk_ctrl.flush_and_reset();
      blk_ctrl.reg_write(REG_ENABLE_ADDR, 1);

      // ---- Frame 1 ----
      feed_payload(tx_samples, NUM_TX_SAMPS);
      capture_output(NUM_RX_SAMPS);

      // ---- Deliberate payload gap ----
      // Frame 1 drained the input FIFO, so the gated core must pause at the frame
      // boundary and emit nothing. This is exactly the underrun the gating exists
      // to handle: a free-running core would here start a second frame against an
      // empty FIFO and modulate garbage (the hardware failure). Settle a few
      // cycles to let the final frame-1 sample retire, then assert the core is
      // quiescent for a long window.
      repeat (200) @(posedge dut.axis_data_clk);
      `ASSERT_ERROR(dut.run_frame === 1'b0,
                    "Frame gating: run_frame should be low while no frame is buffered");
      gap_valid_cnt = 0;
      repeat (4000) begin
        @(posedge dut.axis_data_clk);
        if (dut.s_txData_axis_tvalid) gap_valid_cnt++;
      end
      `ASSERT_ERROR(gap_valid_cnt == 0,
                    "Frame gating: core produced output during the payload gap (would be garbage)");

      // ---- Frame 2 ----
      // Feed the same golden payload again: the FSM must resume from a clean
      // frame boundary so frame 2 matches golden, proving the payload and the
      // framer stayed aligned across the gap. Frame 2 follows frame 1 without an
      // intervening flush, so its first WINDOW_OVERLAP samples legitimately
      // carry frame 1's windowing overlap-add tail (correct continuous-TX
      // behavior, verified by probe: the deviation is exactly WINDOW_OVERLAP
      // samples long and decays as the window ramp-down tapers to zero). Skip
      // those in the golden comparison; every later sample must still match.
      feed_payload(tx_samples, NUM_TX_SAMPS);
      capture_output(NUM_RX_SAMPS, WINDOW_OVERLAP);

      test.end_test();
    end : test_frame_gating_recovery

    begin : test_arbitrary_payload_backpressure
      byte unsigned arb[];
      logic [15:0]  lfsr;
      bit           ready_rb;

      test.start_test("Arbitrary payload + adversarial backpressure: demod must match fed bits", 80ms);

      // Build an arbitrary, content-dependent payload (16-bit Galois LFSR, 2
      // payload bits per byte). Unlike the constant/ramp loopback probes, an
      // arbitrary payload is sensitive to any dropped, duplicated, or mis-timed
      // payload read, so the demod check below catches payload-delivery
      // corruption that the golden (and const/ramp) tests can miss -- the
      // hardware failure where data subcarriers carry random bits.
      arb  = new[NUM_TX_SAMPS];
      lfsr = 16'hACE1;
      foreach (arb[i]) begin
        arb[i] = lfsr[1:0];
        lfsr   = lfsr[0] ? ((lfsr >> 1) ^ 16'hB400) : (lfsr >> 1);
      end

      // Clean slate so this frame aligns to golden output sample 0 (sync symbol).
      blk_ctrl.reg_write(REG_ENABLE_ADDR, 0);
      blk_ctrl.flush_and_reset();

      fork
        begin : producer4
          feed_payload(arb, NUM_TX_SAMPS);
        end
        begin : enabler4
          wait (dut.m_txPayload_axis_tready === 1'b1);
          wait (dut.m_txPayload_axis_tready === 1'b0);
          repeat (50) @(posedge ce_clk);
          blk_ctrl.reg_write(REG_ENABLE_ADDR, 1);
        end
        begin : adversary4
          // Hammer output backpressure in long sustained bursts while the core
          // modulates. Sustained "full" keeps the output FIFO full so the core's
          // clk_enable (= s_txData_axis_tready) toggles hard, repeatedly freezing
          // and resuming the core while payload streams in -- the condition under
          // which a payload-read flow-control bug drops/duplicates samples. The
          // default random STALL_PROB averages out and never sustains "full", so
          // it does not exercise this; the one-shot stall in test 1 freezes only
          // once. Here we cycle freeze/resume repeatedly across the frame start.
          repeat (8) begin
            blk_ctrl.set_slave_stall_prob(0, 100);   // never ready: sustained full
            repeat (3000) @(posedge ce_clk);
            blk_ctrl.set_slave_stall_prob(0, STALL_PROB);
            repeat (1000) @(posedge ce_clk);
          end
          blk_ctrl.set_slave_stall_prob(0, STALL_PROB);
        end
        begin : sink4
          capture_collect(NUM_RX_SAMPS);
        end
      join

      do begin
        get_tx_payload_ready(ready_rb);
      end while (!ready_rb);

      // Compacted recv path is aligned to golden output sample 0, so align0 = 0.
      demod_check_payload(0, arb, DEMOD_SYMS_TO_CHECK);

      test.end_test();
    end : test_arbitrary_payload_backpressure

    //--------------------------------
    // Finish Up
    //--------------------------------

    // Display final statistics and results
    test.end_tb();
  end : tb_main

endmodule : rfnoc_block_ofdm_tx_sl_tb


`default_nettype wire
