#!/usr/bin/env python3
#
# Copyright 2026 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
"""Hardware verification for the ofdm_tx_sl RFNoC block.

This is the on-hardware counterpart to the simulation testbench
(rfnoc_block_ofdm_tx_sl_tb.sv). The testbench proves the block in isolation by
feeding a MATLAB golden-reference payload (ofdm_tx_input.hex), capturing the
modulated sc16 output, and comparing it against the golden expected output
(ofdm_tx_expected.hex) within +-TOL_LSB. This script does the same end-to-end
inside the live RFNoC graph, so a pass means the block behaves identically once
instantiated in the real ecosystem (NoC shell, CHDR transport, ctrlport, the
ce/chdr clock-domain crossings, and the radio).

Datapath (radio digital loopback):

    Host (s8) -> Ofdm_tx_sl#0 -> Radio#0 TX --+
                                              | digital loopback (poke 0x1000)
    Host (sc16) <- Radio#0 RX <---------------+

On this bitfile the OFDM block's output port is not wired to a stream endpoint,
so it cannot stream directly to the host ("not connected to an SEP"); the radio
is the only route to host RX. The radio runs at RATE (= master_clock_rate, so
the DUC/DDC ratio is 1 and sc16 words pass through the loopback bit-for-bit).

Two hardware realities shape the capture:

  * Duty cycle: the OFDM core emits valid samples only ~25% of the time, so a
    250 Msps radio sink starves and fills the gaps with zeros. Because the
    radio transmits the block's samples in order (just interleaved with
    underflow zeros), removing the zero runs reconstructs the contiguous OFDM
    stream.
  * Overflow: at 250 Msps (1 GB/s of sc16) the host cannot capture indefinitely
    while also feeding the TX. An overflow *drops* samples, which would corrupt
    the in-order reconstruction -- so we capture continuously and stop at the
    first overflow, keeping only the contiguous, drop-free prefix.

We then reconstruct the valid samples from that clean window, align them to the
golden frame by cross-correlation, and compare the overlapping stretch within
+-TOL_LSB. Feeding the *same* golden payload periodically (period NUM_TX_SAMPS)
makes the output periodic with period NUM_RX_SAMPS, so the captured window is a
contiguous slice of the golden frame regardless of where it starts. The number
of verified samples depends on how large a clean window the transport allows;
raise RECV_BUFFERING to push the overflow point out toward a full frame.

Run with (UHD must be able to find the OOT block controller):
    export UHD_MODULE_PATH=.../librfnoc-oot-blocks.so
    python3 transceiver.py
"""

import os
import sys
import time

import numpy as np
import uhd

from rfnoc_oot_tum import OfdmTxSlBlockControl

try:
    from scipy.signal import correlate as _scipy_correlate
except ImportError:  # scipy is optional; fall back to numpy below.
    _scipy_correlate = None


# --- Configuration ---
DEVICE_ARGS = "addr=10.157.161.243, master_clock_rate=250e6"
RATE = 250e6  # radio sample rate; == master_clock_rate so the DUC/DDC ratio is 1

# Optional transport buffering appended to the RX stream args. Larger host
# buffers push the overflow point out, so a bigger (ideally full-frame) clean
# window can be captured. Leave empty to use UHD defaults; example:
# "num_recv_frames=2048".
RECV_BUFFERING = ""

# Golden-reference vectors, generated by the MATLAB reference and shared with
# the simulation testbench (see rfnoc_block_ofdm_tx_sl_tb.sv). They live next to
# this script.
_HERE = os.path.dirname(os.path.abspath(__file__))
INPUT_HEX = os.path.join(_HERE, "ofdm_tx_input.hex")        # one int8 payload sample/line ("%02X")
EXPECTED_HEX = os.path.join(_HERE, "ofdm_tx_expected.hex")  # one sc16 word/line ("%08X" = {I[31:16],Q[15:0]})

NUM_TX_SAMPS = 40812  # int8 payload samples that make up one input frame
NUM_RX_SAMPS = 76800  # sc16 output samples in one OFDM frame (240 syms * 320)

# Tolerance matches the testbench: spec is +-0.001 in the normalized double
# domain, i.e. 0.001 * 32768 ~= 32.77 LSB in Q1.15 -> 33.
TOL_LSB = 33

# OFDM frame geometry (for plotting / sanity prints only).
FFT_LEN = 256
CP_LEN = 64
N_SYMS = 240
SAMP_PER_SYM = FFT_LEN + CP_LEN  # 320

# Length of captured prefix used to cross-correlate for frame alignment. Kept
# small so that even a modest clean window (a few thousand valid samples) can be
# aligned and verified.
CORR_LEN = 2048

# Minimum number of reconstructed valid samples required to attempt a
# comparison (must exceed CORR_LEN with room for a meaningful overlap).
MIN_VALID = 4096

# Target capture length. At ~25% duty this is ~4 frames' worth of radio samples
# per golden frame; we stop early at the first overflow, so this is just an
# upper bound on how much we try to read.
CAPTURE_SAMPS = 4 * NUM_RX_SAMPS

# Minimum run of consecutive exact-zero sc16 words treated as a radio-underflow
# gap (and removed). The golden frame contains only isolated single-sample
# zeros (genuine OFDM signal zeros), so a generous threshold strips duty-cycle
# gaps while preserving real signal samples.
MIN_GAP = 16

SPP_TX = 1024
SPP_RX = 8192

SHOW_PLOTS = True


def load_input_payload(path):
    """Load the int8 payload stimulus (one byte per line, hex)."""
    vals = np.loadtxt(path, dtype=np.uint8, converters={0: lambda s: int(s, 16)})
    return vals.reshape(-1)


def load_expected_output(path):
    """Load the golden sc16 output as a uint32 array (one "%08X" word per line)."""
    vals = np.loadtxt(path, dtype=np.uint32, converters={0: lambda s: int(s, 16)})
    return vals.reshape(-1)


def split_iq(words):
    """Split sc16-as-uint32 words into signed I (high 16) and Q (low 16).

    Matches the testbench convention: each 32-bit item is {I[31:16], Q[15:0]},
    Q1.15 fixed point. Returns (i, q) as int32 arrays.
    """
    words = np.asarray(words, dtype=np.uint32)
    i = ((words >> 16) & 0xFFFF).astype(np.uint16).view(np.int16).astype(np.int32)
    q = (words & 0xFFFF).astype(np.uint16).view(np.int16).astype(np.int32)
    return i, q


def to_complex(words):
    """sc16-as-uint32 -> complex (I + jQ), I in high half (testbench convention)."""
    i, q = split_iq(words)
    return i.astype(np.float64) + 1j * q.astype(np.float64)


def build_graph():
    """Create the graph and connect Host -> ofdm_tx -> radio (loopback) -> Host."""
    graph = uhd.rfnoc.RfnocGraph(DEVICE_ARGS)

    # txPayload is an 8-bit-per-sample stream (only the two LSBs are used:
    # bit0 -> txPayload_0, bit1 -> txPayload_1), so feed it as s8.
    sa_tx = uhd.usrp.StreamArgs("s8", "s8")
    sa_tx.args = f"spp={SPP_TX}"
    tx_streamer = graph.create_tx_streamer(1, sa_tx)

    # The block emits sc16; capture it as sc16 (delivered into a uint32 buffer).
    sa_rx = uhd.usrp.StreamArgs("sc16", "sc16")
    sa_rx.args = f"spp={SPP_RX}"
    if RECV_BUFFERING:
        sa_rx.args += f",{RECV_BUFFERING}"
    rx_streamer = graph.create_rx_streamer(1, sa_rx)

    ofdm = OfdmTxSlBlockControl(graph.get_block("0/Ofdm_tx_sl#0"))
    radio = uhd.rfnoc.RadioControl(graph.get_block("0/Radio#0"))

    graph.connect(tx_streamer, 0, ofdm.get_unique_id(), 0)
    uhd.rfnoc.connect_through_blocks(
        graph, ofdm.get_unique_id(), 0, radio.get_unique_id(), 0)
    graph.connect(radio.get_unique_id(), 0, rx_streamer, 0)

    graph.commit()

    # Configure the radio AFTER commit so the rate propagates through the full
    # graph (DUC interpolation etc.); at RATE == master_clock_rate the ratio is
    # 1 and samples pass through unchanged.
    radio.set_rate(RATE)
    radio.set_properties(f"spp={SPP_RX}", 0)
    radio.poke32(0x1000, 0)  # loopback OFF for now

    return graph, tx_streamer, rx_streamer, ofdm, radio


def reorder_payload_for_wire(payload):
    """Compensate for the s8 payload byte-lane scramble on the CHDR transport.

    On-hardware ILA capture of m_txPayload (the byte stream into the OFDM core,
    in the ce_250 domain) proved that, within every 64-bit CHDR word (8 s8
    bytes), the byte the host places at position m is delivered to the core at
    position m XOR 5. Decoded, that is a 16-bit byte-swap combined with a 32-bit
    word-swap inside each 64-bit word -- a plain endianness mismatch in how the
    narrow s8 items ride the otherwise sc16/32-bit-oriented transport.

    XOR is involutive, so pre-permuting the host payload by the same XOR-5 makes
    it arrive in linear order. With this applied, the block output matches the
    MATLAB golden frame to +-1 LSB across *all* symbols (sync, reference, AND
    data); without it only the payload-independent sync/reference symbols match.
    The trailing partial word (len % 8 != 0) is left as-is.
    """
    p = np.asarray(payload).reshape(-1)
    src = np.arange(len(p))
    tgt = src ^ 5
    tgt[tgt >= len(p)] = src[tgt >= len(p)]  # guard the trailing partial word
    return p[tgt]


def feed_enable_capture(tx_streamer, rx_streamer, ofdm, radio, payload):
    """Mirror the testbench single-shot sequence exactly.

    The block is free-running, so its continuous output only reproduces the
    golden frame if the payload is fed in lockstep with the framing. Rather than
    rely on that, we replicate the testbench precisely: disable, feed *exactly
    one* golden payload frame (no continuous feeding), then enable and capture
    from the clean start. The block thus emits exactly the golden output frame,
    so the captured window is golden sample 0 onward -- no payload-phase
    ambiguity.

    Capture starts immediately (stream_now) and stops at the first overflow,
    returning the contiguous, drop-free prefix as a uint32 array.
    """
    data_in = reorder_payload_for_wire(payload).reshape(1, -1).astype(np.int8)

    # Start disabled so the input FIFO can fill without being drained (pops
    # require enable), exactly as the TB does.
    ofdm.set_enable(False)
    radio.poke32(0x1000, 1)  # digital loopback ON for the capture
    print(f"Loopback register readback: {radio.peek32(0x1000)} (expected 1)")

    # Feed exactly one golden frame as a single closed burst. With the block
    # disabled the input FIFO fills and holds it (the TB confirms one frame fits
    # and drives txPayloadReady low).
    tx_md = uhd.types.TXMetadata()
    tx_md.has_time_spec = False
    tx_md.start_of_burst = True
    tx_md.end_of_burst = True
    n_fed = tx_streamer.send(data_in, tx_md, timeout=5.0)
    print(f"Fed {n_fed}/{len(payload)} payload samples (single frame)")
    if n_fed < len(payload):
        print("WARNING: could not feed a whole frame before the FIFO filled; "
              "the input FIFO is smaller than one frame on this build")

    # Wait for the FIFO to report full (txPayloadReady low), like the TB's
    # "enabler" process.
    deadline = time.time() + 5.0
    filled = False
    while time.time() < deadline:
        if not ofdm.get_tx_payload_ready():
            filled = True
            break
        time.sleep(0.001)
    print("Input FIFO full (txPayloadReady low)"
          if filled else "FIFO did not report full within 5 s; proceeding anyway")

    # Start capturing immediately, THEN enable, so we catch the frame from its
    # first output sample (it lasts only ~1.2 ms, far sooner than a timed
    # capture would fire). Leading samples before enable are zeros and get
    # stripped as a gap during reconstruction.
    stream_cmd = uhd.types.StreamCMD(uhd.types.StreamMode.num_done)
    stream_cmd.stream_now = True
    stream_cmd.num_samps = CAPTURE_SAMPS
    rx_streamer.issue_stream_cmd(stream_cmd)
    ofdm.set_enable(True)
    print(f"enable readback: {int(ofdm.get_enable())} (expected 1)")

    rx_md = uhd.types.RXMetadata()
    raw_out = np.zeros(CAPTURE_SAMPS, dtype=np.uint32)
    chunk = np.zeros((1, SPP_RX), dtype=np.uint32)
    got = 0
    while got < CAPTURE_SAMPS:
        n = rx_streamer.recv(chunk, rx_md, timeout=10.0)
        err = str(rx_md.error_code).lower()
        if "overflow" in err:
            # Samples were dropped; everything after this point is no longer
            # contiguous, so stop and keep the clean prefix.
            print(f"Overflow after {got} samples; keeping the clean prefix")
            break
        if n == 0:
            print(f"recv=0  error={rx_md.error_code}")
            break
        if "none" not in err:
            print(f"  RX error: {rx_md.error_code}")
        copy = min(n, CAPTURE_SAMPS - got)
        raw_out[got:got + copy] = chunk[0, :copy]
        got += copy

    # Stop the radio streaming (UHD names this enum value "stop_cont"; fall back
    # to "stop_continuous" on older bindings).
    stop_mode = getattr(uhd.types.StreamMode, "stop_cont",
                        getattr(uhd.types.StreamMode, "stop_continuous", None))
    if stop_mode is not None:
        rx_streamer.issue_stream_cmd(uhd.types.StreamCMD(stop_mode))
    print(f"Captured {got}/{CAPTURE_SAMPS} sc16")

    ofdm.set_enable(False)
    radio.poke32(0x1000, 0)
    return raw_out[:got]


def reconstruct_valid(captured):
    """Remove radio-underflow gaps to recover the contiguous OFDM sample stream.

    Drops runs of >= MIN_GAP consecutive exact-zero sc16 words (underflow gaps),
    preserving the isolated zero samples that genuinely occur in the OFDM
    waveform. Returns the reconstructed valid-sample array.
    """
    isz = captured == 0
    starts = np.flatnonzero(np.r_[True, np.diff(isz.astype(np.int8)) != 0])
    runlens = np.diff(np.r_[starts, len(captured)])
    keep = np.ones(len(captured), dtype=bool)
    n_gap = 0
    for s, ln in zip(starts, runlens):
        if isz[s] and ln >= MIN_GAP:
            keep[s:s + ln] = False
            n_gap += ln
    valid = captured[keep]
    print(f"Removed {n_gap} samples in radio-underflow gaps; "
          f"valid stream is {len(valid)}/{len(captured)} samples")
    return valid


def align_by_magnitude(valid, expected):
    """Find where the captured window starts within the (periodic) golden frame.

    Correlates the |sample| envelopes rather than the complex samples, so the
    alignment is immune to any constant rotation, I/Q swap, or frequency offset
    the radio loopback might apply -- it locks on the OFDM envelope structure
    (CP repetition, symbol boundaries) alone. Correlates against the golden
    frame tiled twice to allow a match that wraps past the frame end.

    Returns (offset, overlap_len, lock_ratio). lock_ratio is the correlation
    peak over its median; >~3 indicates a confident lock, ~1 means no real
    alignment was found.
    """
    tiled_mag = np.abs(to_complex(np.tile(expected, 2)))
    tiled_mag -= tiled_mag.mean()
    tmpl_mag = np.abs(to_complex(valid[:CORR_LEN]))
    tmpl_mag -= tmpl_mag.mean()
    if _scipy_correlate is not None:
        corr = _scipy_correlate(tiled_mag, tmpl_mag, mode="valid", method="fft")
    else:
        n = len(tiled_mag) - len(tmpl_mag) + 1
        corr = np.array([np.dot(tiled_mag[k:k + len(tmpl_mag)], tmpl_mag)
                         for k in range(n)])
    region = np.abs(corr[:NUM_RX_SAMPS])
    offset = int(np.argmax(region))
    lock_ratio = float(region[offset] / (np.median(region) + 1e-9))
    overlap_len = min(len(valid), NUM_RX_SAMPS)
    return offset, overlap_len, lock_ratio


def analyze(valid, offset, overlap_len, expected):
    """Characterize the captured stretch against the golden reference.

    The loopback here is digital (DUC/DDC ratio 1), so the captured samples
    should equal the golden output bit-for-bit -- no amplitude/phase calibration
    is warranted. We therefore compare the captured samples *raw* (no gain
    correction) against the golden reference, trying the samples as-is and with
    I and Q swapped (the host sc16 word order is the opposite of the testbench's
    {I[31:16], Q[15:0]}). Returns a dict describing the best (lowest-EVM)
    variant, including the I/Q deviation against the +-TOL_LSB testbench
    criterion.
    """
    got = to_complex(valid[:overlap_len])
    exp = to_complex(np.tile(expected, 2)[offset:offset + overlap_len])
    got_swap = 1j * np.conj(got)  # swap I<->Q: (i + jq) -> (q + ji)

    # Magnitude-only fit: invariant to any rotation / I-Q swap / frequency
    # offset. Low magnitude-EVM with high complex-EVM means the block produces
    # the right OFDM envelope but the loopback rotates the phase (benign);
    # high magnitude-EVM means the captured signal is genuinely not the golden
    # waveform.
    amask = np.abs(exp) > 2000
    if np.any(amask):
        scale = np.sum(np.abs(got[amask]) * np.abs(exp[amask])) / np.sum(np.abs(exp[amask]) ** 2)
        mag_evm = float(np.linalg.norm(np.abs(got[amask]) - scale * np.abs(exp[amask]))
                        / (np.linalg.norm(scale * np.abs(exp[amask])) + 1e-9))
    else:
        mag_evm = float("inf")
    print(f"  magnitude-only EVM = {mag_evm * 100:.2f}%  "
          f"(low => block envelope matches; phase handled separately)")

    # Scale/format diagnostics. Magnitude is immune to rotation and I/Q swap, so
    # if these don't line up the problem is amplitude/format, not phase.
    gi_, gq_ = np.real(got), np.imag(got)
    ei_, eq_ = np.real(exp), np.imag(exp)
    n_sat = int(np.count_nonzero(np.abs(gi_) >= 32767)
                + np.count_nonzero(np.abs(gq_) >= 32767))
    print(f"  captured: rms|.|={np.sqrt(np.mean(np.abs(got) ** 2)):8.1f} "
          f"max|I|={np.abs(gi_).max():6.0f} max|Q|={np.abs(gq_).max():6.0f} "
          f"saturated(>=32767)={n_sat}")
    print(f"  expected: rms|.|={np.sqrt(np.mean(np.abs(exp) ** 2)):8.1f} "
          f"max|I|={np.abs(ei_).max():6.0f} max|Q|={np.abs(eq_).max():6.0f}")
    if np.any(amask):
        print(f"  best single magnitude scale: captured ~= {scale:.4f} * expected")

    best = None
    for name, gz in (("direct", got), ("iq-swap", got_swap)):
        # Raw comparison: no gain/phase correction. EVM is the residual against
        # the golden reference over the strong samples (~0 means bit-exact).
        if np.any(amask):
            evm = float(np.linalg.norm((gz - exp)[amask])
                        / (np.linalg.norm(exp[amask]) + 1e-9))
        else:
            evm = float("inf")
        dev_i = np.abs(np.real(gz) - np.real(exp))
        dev_q = np.abs(np.imag(gz) - np.imag(exp))
        max_dev = float(max(dev_i.max(), dev_q.max()))
        n_fail = int(np.count_nonzero((dev_i > TOL_LSB) | (dev_q > TOL_LSB)))
        info = dict(name=name, evm=evm, max_dev=max_dev, n_fail=n_fail,
                    mag_evm=mag_evm, corrected=gz, exp=exp,
                    dev_i=dev_i, dev_q=dev_q)
        print(f"  [{name:8s}] EVM={evm * 100:6.2f}%  "
              f"max_dev={max_dev:.0f} LSB  n_fail={n_fail}")
        if best is None or evm < best["evm"]:
            best = info
    return best


def plot_expected_output(expected):
    """Plot the golden block output as sfix1,16,15 (Q1.15, max amplitude 1).

    The block emits sc16 in Q1.15 fixed point ({I[31:16], Q[15:0]}, 1.0 ->
    32768). Dividing the signed 16-bit I/Q by 2**15 maps it to the sfix1,16,15
    range [-1, 1). No hardware needed -- this just visualizes the reference.
    """
    import matplotlib.pyplot as plt

    i, q = split_iq(expected)
    I = i.astype(np.float64) / 32768.0  # sfix1,16,15: 1 sign bit, 15 frac bits
    Q = q.astype(np.float64) / 32768.0
    mag = np.hypot(I, Q)
    n = len(I)
    n_show = min(3 * SAMP_PER_SYM, n)

    fig, axes = plt.subplots(4, 1, figsize=(14, 11))
    axes[0].plot(I, lw=0.5)
    axes[0].set_ylabel("I"); axes[0].set_ylim(-1.05, 1.05); axes[0].grid(True)
    axes[0].set_title(f"ofdm_tx golden output (sfix1,16,15) -- {n} sc16 samples")

    axes[1].plot(Q, lw=0.5, color="C1")
    axes[1].set_ylabel("Q"); axes[1].set_ylim(-1.05, 1.05); axes[1].grid(True)

    axes[2].plot(mag, lw=0.5, color="C2")
    axes[2].set_ylabel("|I+jQ|"); axes[2].grid(True)
    axes[2].set_xlabel("sample index")

    axes[3].plot(I[:n_show], lw=0.7, label="I")
    axes[3].plot(Q[:n_show], lw=0.7, label="Q")
    axes[3].set_ylabel("amplitude")
    axes[3].set_xlabel(f"sample index (first {n_show // SAMP_PER_SYM} symbols, "
                       f"FFT+CP = {SAMP_PER_SYM}/symbol)")
    axes[3].set_title("Zoom: first symbols")
    axes[3].legend(loc="upper right"); axes[3].grid(True)

    fig.tight_layout()
    try:
        plt.show(block=True)
    except KeyboardInterrupt:
        pass


def plot(best, overlap_len):
    """Overlay the captured stretch on the golden reference (no gain correction)."""
    import matplotlib.pyplot as plt

    # Convert LSB -> sfix1,16,15 (Q1.15: 1.0 -> 32768), so captured and golden
    # are both on the normalized [-1, 1) amplitude scale.
    gi, gq = np.real(best["corrected"]) / 32768.0, np.imag(best["corrected"]) / 32768.0
    ei, eq = np.real(best["exp"]) / 32768.0, np.imag(best["exp"]) / 32768.0

    fig, axes = plt.subplots(3, 1, figsize=(14, 9))
    axes[0].plot(ei, label="expected I")
    axes[0].plot(gi, "--", label="captured I")
    axes[0].set_title("OFDM TX I (sfix1,16,15, full aligned stretch)")
    axes[0].set_ylabel("I"); axes[0].set_ylim(-1.05, 1.05)
    axes[0].legend(); axes[0].grid(True)

    axes[1].plot(eq, label="expected Q")
    axes[1].plot(gq, "--", label="captured Q")
    axes[1].set_title("OFDM TX Q (sfix1,16,15, full aligned stretch)")
    axes[1].set_ylabel("Q"); axes[1].set_ylim(-1.05, 1.05)
    axes[1].legend(); axes[1].grid(True)

    axes[2].plot(best["dev_i"], label="|dev I|")
    axes[2].plot(best["dev_q"], label="|dev Q|")
    axes[2].axhline(TOL_LSB, color="r", ls=":", label=f"tol {TOL_LSB}")
    axes[2].set_title(f"Deviation, '{best['name']}' variant "
                      f"({overlap_len} aligned samples)")
    axes[2].set_xlabel("Sample index"); axes[2].legend(); axes[2].grid(True)

    fig.tight_layout()
    try:
        plt.show(block=True)
    except KeyboardInterrupt:
        pass


def main():
    """Feed the golden payload, capture the OFDM output, verify against golden."""
    payload = load_input_payload(INPUT_HEX)
    expected = load_expected_output(EXPECTED_HEX)
    print(f"Loaded {len(payload)} payload samples and {len(expected)} expected sc16 words")
    if len(payload) != NUM_TX_SAMPS or len(expected) != NUM_RX_SAMPS:
        print(f"WARNING: vector sizes ({len(payload)}, {len(expected)}) differ from "
              f"expected ({NUM_TX_SAMPS}, {NUM_RX_SAMPS})")

    graph, tx_streamer, rx_streamer, ofdm, radio = build_graph()

    captured = feed_enable_capture(tx_streamer, rx_streamer, ofdm, radio, payload)
    # Persist the raw capture so the captured-vs-golden relationship can be
    # inspected offline (e.g. scale/format debugging) without re-running on HW.
    np.save(os.path.join(_HERE, "captured_raw.npy"), captured)

    valid = reconstruct_valid(captured)
    if len(valid) < MIN_VALID:
        print(f"FAIL: only {len(valid)} valid samples reconstructed (< {MIN_VALID} "
              "needed to verify). Is the block enabled / producing output?")
        sys.exit(1)

    offset, overlap_len, lock_ratio = align_by_magnitude(valid, expected)
    print(f"Envelope aligned at golden-frame offset {offset} "
          f"(lock ratio {lock_ratio:.1f}; >~3 is a confident lock); "
          f"verifying {overlap_len} samples ({overlap_len / SAMP_PER_SYM:.0f} OFDM symbols)")
    if lock_ratio < 3.0:
        print("WARNING: weak envelope lock -- the capture may not be the golden OFDM "
              "waveform at all (check the block is fed the golden payload).")
    if overlap_len < NUM_RX_SAMPS:
        print(f"NOTE: only a partial frame was captured ({overlap_len}/{NUM_RX_SAMPS}); "
              "raise RECV_BUFFERING to verify a full frame")

    # Characterize the captured-vs-golden relationship (rotation / I-Q swap /
    # gain) and apply the testbench +-TOL_LSB criterion after gain correction.
    best = analyze(valid, offset, overlap_len, expected)

    # Digital loopback: the captured I/Q should match the golden output raw,
    # within the testbench tolerance, with no gain/phase correction.
    passed = best["n_fail"] == 0 and lock_ratio >= 3.0
    print(f"Best match: '{best['name']}' variant, EVM={best['evm'] * 100:.2f}%")
    print(f"max deviation = {best['max_dev']:.0f} LSB (tol {TOL_LSB}), "
          f"{best['n_fail']}/{overlap_len} samples out of tolerance")
    if passed:
        print(f"PASS: {overlap_len} captured OFDM samples match the MATLAB reference "
              f"within tolerance")
    else:
        print("FAIL: captured OFDM output does not match the MATLAB reference within tolerance")
        # Help interpret why, from the magnitude-vs-complex EVM split.
        if best["mag_evm"] < 0.05 and best["evm"] > 0.05:
            print("  Diagnosis: the envelope matches but the phase does not -- the loopback "
                  "applies more than a constant rotation (likely a DDC frequency offset). "
                  "The block waveform itself looks correct; tune the radio DSP freq to 0 or "
                  "compensate the residual frequency before the exact-I/Q check can pass.")
        elif best["mag_evm"] >= 0.05:
            print("  Diagnosis: even the magnitude envelope does not match -- the capture is "
                  "not the golden OFDM waveform (check payload, alignment lock, and that the "
                  "block is the signal source).")

    if SHOW_PLOTS:
        try:
            plot(best, overlap_len)
        except Exception as exc:  # plotting is diagnostic only; never fail on it
            print(f"(plot skipped: {exc})")

    sys.exit(0 if passed else 1)


if __name__ == "__main__":
    # `--plot-expected` just visualizes the golden output in sfix1,16,15 and
    # exits -- no USRP / RFNoC graph needed.
    if "--plot-expected" in sys.argv:
        plot_expected_output(load_expected_output(EXPECTED_HEX))
        sys.exit(0)
    main()
