// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Channel_Equalization.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Channel_Equalization
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Channel Equalization
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Channel_Equalization
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] rxSym_re  /* sfix16_En15 */,
             input logic signed [15:0] rxSym_im  /* sfix16_En15 */,
             input logic validIn,
             input logic signed [15:0] hEst_re  /* sfix16_En15 */,
             input logic signed [15:0] hEst_im  /* sfix16_En15 */,
             output logic signed [31:0] eqData_re  /* sfix32_En15 */,
             output logic signed [31:0] eqData_im  /* sfix32_En15 */,
             output logic validOut);


  logic signed [15:0] Delay12_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay12_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay13_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay13_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay13_out1_re_1;  /* sfix16_En15 */
  logic signed [15:0] Delay13_out1_im_1;  /* sfix16_En15 */
  logic signed [15:0] Delay11_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay11_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay11_out1_re_1;  /* sfix16_En15 */
  logic signed [15:0] Delay11_out1_im_1;  /* sfix16_En15 */
  logic signed [16:0] conj_cast;  /* sfix17_En15 */
  logic signed [16:0] conj_cast_1;  /* sfix17_En15 */
  logic signed [15:0] Conjugate1_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Conjugate1_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay14_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay14_out1_im;  /* sfix16_En15 */
  logic signed [31:0] Product1_mul_temp;  /* sfix32_En30 */
  logic signed [31:0] Product1_mul_temp_1;  /* sfix32_En30 */
  logic signed [31:0] Product1_mul_temp_2;  /* sfix32_En30 */
  logic signed [31:0] Product1_mul_temp_3;  /* sfix32_En30 */
  logic signed [31:0] Product1_out1_re;  /* sfix32_En30 */
  logic signed [31:0] Product1_out1_im;  /* sfix32_En30 */
  logic Delay16_out1_timer;
  logic Delay16_out1_timer_1;
  logic signed [15:0] Delay16_out1_default;  /* sfix16_En15 */
  logic signed [31:0] Magnitude_Square_real_square;  /* sfix32_En30 */
  logic signed [31:0] Magnitude_Square_imag_square;  /* sfix32_En30 */
  logic signed [15:0] adder_add_cast;  /* sfix16_En15 */
  logic signed [16:0] adder_add_cast_1;  /* sfix17_En15 */
  logic signed [15:0] adder_add_cast_2;  /* sfix16_En15 */
  logic signed [16:0] adder_add_cast_3;  /* sfix17_En15 */
  logic signed [16:0] adder_add_temp;  /* sfix17_En15 */
  logic signed [15:0] Magnitude_Square_out1;  /* sfix16_En15 */
  logic signed [15:0] Delay16_out1;  /* sfix16_En15 */
  logic signed [15:0] Delay16_out1_1;  /* sfix16_En15 */
  logic signed [15:0] Delay16_out1_zp;  /* sfix16_En15 */
  logic signed [31:0] Product2_out1;  /* sfix32_En15 */
  logic Delay16_out1_timer_2;
  logic Delay16_out1_timer_3;
  logic signed [15:0] Delay16_out1_default_1;  /* sfix16_En15 */
  logic signed [15:0] Delay16_out1_zp_1;  /* sfix16_En15 */
  logic signed [31:0] Product3_out1;  /* sfix32_En15 */
  logic Delay10_out1;
  logic Delay15_out1;
  logic Delay9_out1;


  always_ff @(posedge clk)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1_re <= 16'sb0000000000000000;
        Delay12_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay12_out1_re <= rxSym_re;
          Delay12_out1_im <= rxSym_im;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay13_in_pipe_process
      if (reset == 1'b1) begin
        Delay13_out1_re <= 16'sb0000000000000000;
        Delay13_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay13_out1_re <= Delay12_out1_re;
          Delay13_out1_im <= Delay12_out1_im;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay13_out_pipe_process
      if (reset == 1'b1) begin
        Delay13_out1_re_1 <= 16'sb0000000000000000;
        Delay13_out1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay13_out1_re_1 <= Delay13_out1_re;
          Delay13_out1_im_1 <= Delay13_out1_im;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1_re <= 16'sb0000000000000000;
        Delay11_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay11_out1_re <= hEst_re;
          Delay11_out1_im <= hEst_im;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Conjugate1_in_pipe_process
      if (reset == 1'b1) begin
        Delay11_out1_re_1 <= 16'sb0000000000000000;
        Delay11_out1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay11_out1_re_1 <= Delay11_out1_re;
          Delay11_out1_im_1 <= Delay11_out1_im;
        end
      end
    end

  assign Conjugate1_out1_re = Delay11_out1_re_1;
  assign conj_cast = {Delay11_out1_im_1[15], Delay11_out1_im_1};
  assign conj_cast_1 =  - (conj_cast);
  assign Conjugate1_out1_im = ((conj_cast_1[16] == 1'b0) && (conj_cast_1[15] != 1'b0) ? 16'sb0111111111111111 :
              ((conj_cast_1[16] == 1'b1) && (conj_cast_1[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(conj_cast_1[15:0])));

  always_ff @(posedge clk)
    begin : Conjugate1_out_pipe_process
      if (reset == 1'b1) begin
        Delay14_out1_re <= 16'sb0000000000000000;
        Delay14_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay14_out1_re <= Conjugate1_out1_re;
          Delay14_out1_im <= Conjugate1_out1_im;
        end
      end
    end

  assign Product1_mul_temp = Delay13_out1_re_1 * Delay14_out1_re;
  assign Product1_mul_temp_1 = Delay13_out1_im_1 * Delay14_out1_im;
  assign Product1_out1_re = Product1_mul_temp - Product1_mul_temp_1;
  assign Product1_mul_temp_2 = Delay13_out1_im_1 * Delay14_out1_re;
  assign Product1_mul_temp_3 = Delay13_out1_re_1 * Delay14_out1_im;
  assign Product1_out1_im = Product1_mul_temp_2 + Product1_mul_temp_3;

  assign Delay16_out1_timer = 1'b1;

  always_ff @(posedge clk)
    begin : delayMatch1_process
      if (reset == 1'b1) begin
        Delay16_out1_timer_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay16_out1_timer_1 <= Delay16_out1_timer;
        end
      end
    end

  assign Delay16_out1_default = 16'sb0111111111111111;

  assign Magnitude_Square_real_square = Delay11_out1_re * Delay11_out1_re;

  assign Magnitude_Square_imag_square = Delay11_out1_im * Delay11_out1_im;

  assign adder_add_cast = ((Magnitude_Square_real_square[31] == 1'b0) && (Magnitude_Square_real_square[30] != 1'b0) ? 16'sb0111111111111111 :
              ((Magnitude_Square_real_square[31] == 1'b1) && (Magnitude_Square_real_square[30] != 1'b1) ? 16'sb1000000000000000 :
              Magnitude_Square_real_square[30:15] + $signed({1'b0, Magnitude_Square_real_square[31] & (|Magnitude_Square_real_square[14:0])})));
  assign adder_add_cast_1 = {adder_add_cast[15], adder_add_cast};
  assign adder_add_cast_2 = ((Magnitude_Square_imag_square[31] == 1'b0) && (Magnitude_Square_imag_square[30] != 1'b0) ? 16'sb0111111111111111 :
              ((Magnitude_Square_imag_square[31] == 1'b1) && (Magnitude_Square_imag_square[30] != 1'b1) ? 16'sb1000000000000000 :
              Magnitude_Square_imag_square[30:15] + $signed({1'b0, Magnitude_Square_imag_square[31] & (|Magnitude_Square_imag_square[14:0])})));
  assign adder_add_cast_3 = {adder_add_cast_2[15], adder_add_cast_2};
  assign adder_add_temp = adder_add_cast_1 + adder_add_cast_3;
  assign Magnitude_Square_out1 = ((adder_add_temp[16] == 1'b0) && (adder_add_temp[15] != 1'b0) ? 16'sb0111111111111111 :
              ((adder_add_temp[16] == 1'b1) && (adder_add_temp[15] != 1'b1) ? 16'sb1000000000000000 :
              $signed(adder_add_temp[15:0])));

  always_ff @(posedge clk)
    begin : Magnitude_Square_out_pipe_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= Magnitude_Square_out1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : reduced_process
      if (reset == 1'b1) begin
        Delay16_out1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay16_out1_1 <= Delay16_out1;
        end
      end
    end

  assign Delay16_out1_zp = (Delay16_out1_timer_1 == 1'b0 ? Delay16_out1_default :
              Delay16_out1_1);

  Product2 u_Product2 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dividend_in(Product1_out1_re),  /* sfix32_En30 */
                       .divisor_in(Delay16_out1_zp),  /* sfix16_En15 */
                       .quotient(Product2_out1)  /* sfix32_En15 */
                       );

  assign eqData_re = Product2_out1;

  assign Delay16_out1_timer_2 = 1'b1;

  always_ff @(posedge clk)
    begin : delayMatch3_process
      if (reset == 1'b1) begin
        Delay16_out1_timer_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay16_out1_timer_3 <= Delay16_out1_timer_2;
        end
      end
    end

  assign Delay16_out1_default_1 = 16'sb0111111111111111;

  assign Delay16_out1_zp_1 = (Delay16_out1_timer_3 == 1'b0 ? Delay16_out1_default_1 :
              Delay16_out1_1);

  Product3 u_Product3 (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dividend_in(Product1_out1_im),  /* sfix32_En30 */
                       .divisor_in(Delay16_out1_zp_1),  /* sfix16_En15 */
                       .quotient(Product3_out1)  /* sfix32_En15 */
                       );

  assign eqData_im = Product3_out1;

  always_ff @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= validIn;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay15_in_pipe_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= Delay10_out1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay15_out_pipe_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= Delay15_out1;
        end
      end
    end

  assign validOut = Delay9_out1;

endmodule  // Channel_Equalization

