// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Channel_Estimation.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Channel_Estimation
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Channel Estimation
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Channel_Estimation
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] rxSym_re  /* sfix16_En15 */,
             input logic signed [15:0] rxSym_im  /* sfix16_En15 */,
             input logic isRef,
             input logic frameStart,
             input logic readyIn,
             output logic signed [15:0] hEst_re  /* sfix16_En15 */,
             output logic signed [15:0] hEst_im  /* sfix16_En15 */,
             output logic hEstValid);


  rxsl_vector_of_signed_logic_16 Delay7_reg_re [0:3];  /* sfix16_En15 [4] */
  rxsl_vector_of_signed_logic_16 Delay7_reg_im [0:3];  /* sfix16_En15 [4] */
  logic signed [15:0] Delay7_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay7_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Reference_Symbols_refSym_re;  /* sfix16_En15 */
  logic signed [15:0] Reference_Symbols_refSym_im;  /* sfix16_En15 */
  logic Reference_Symbols_validOut;
  logic signed [15:0] Channel_Estimator_hEst_re;  /* sfix16_En15 */
  logic signed [15:0] Channel_Estimator_hEst_im;  /* sfix16_En15 */
  logic Channel_Estimator_hEstValid;


  always_ff @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_reg_re <= '{default :16'sb0000000000000000};
        Delay7_reg_im <= '{default :16'sb0000000000000000};
      end
      else begin
        if (enb) begin
          Delay7_reg_im[0] <= rxSym_im;
          Delay7_reg_im[32'sd1:32'sd3] <= Delay7_reg_im[32'sd0:32'sd2];
          Delay7_reg_re[0] <= rxSym_re;
          Delay7_reg_re[32'sd1:32'sd3] <= Delay7_reg_re[32'sd0:32'sd2];
        end
      end
    end

  assign Delay7_out1_re = Delay7_reg_re[3];
  assign Delay7_out1_im = Delay7_reg_im[3];

  Reference_Symbols u_Reference_Symbols (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .isRef(isRef),
                                         .frameStart(frameStart),
                                         .refSym_re(Reference_Symbols_refSym_re),  /* sfix16_En15 */
                                         .refSym_im(Reference_Symbols_refSym_im),  /* sfix16_En15 */
                                         .validOut(Reference_Symbols_validOut)
                                         );

  Channel_Estimator u_Channel_Estimator (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .rxSym_re(Delay7_out1_re),  /* sfix16_En15 */
                                         .rxSym_im(Delay7_out1_im),  /* sfix16_En15 */
                                         .refSym_re(Reference_Symbols_refSym_re),  /* sfix16_En15 */
                                         .refSym_im(Reference_Symbols_refSym_im),  /* sfix16_En15 */
                                         .refValid(Reference_Symbols_validOut),
                                         .readyIn(readyIn),
                                         .hEst_re(Channel_Estimator_hEst_re),  /* sfix16_En15 */
                                         .hEst_im(Channel_Estimator_hEst_im),  /* sfix16_En15 */
                                         .hEstValid(Channel_Estimator_hEstValid)
                                         );

  assign hEst_re = Channel_Estimator_hEst_re;

  assign hEst_im = Channel_Estimator_hEst_im;

  assign hEstValid = Channel_Estimator_hEstValid;

endmodule  // Channel_Estimation

