// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/CordicKernelMag.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CordicKernelMag
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Frequency Offset/CP Correlation to Frequency/HDL_CMA_core/CordicKernelMag
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CordicKernelMag
          (  input logic signed [32:0] xin  /* sfix33_En24 */,
             input logic signed [32:0] yin  /* sfix33_En24 */,
             input logic signed [34:0] zin  /* sfix35_En34 */,
             input logic [31:0] lut_value  /* ufix32_En34 */,
             input logic [5:0] idx  /* ufix6 */,
             output logic signed [32:0] xout  /* sfix33_En24 */,
             output logic signed [32:0] yout  /* sfix33_En24 */,
             output logic signed [34:0] zout  /* sfix35_En34 */);


  logic yLessThanZero;
  logic [7:0] dynamic_shift_cast;  /* uint8 */
  logic signed [32:0] yShifted;  /* sfix33_En24 */
  logic signed [32:0] xout2;  /* sfix33_En24 */
  logic signed [32:0] xout1;  /* sfix33_En24 */
  logic [7:0] dynamic_shift_cast_1;  /* uint8 */
  logic signed [32:0] xShifted;  /* sfix33_En24 */
  logic signed [32:0] yout2;  /* sfix33_En24 */
  logic signed [32:0] yout1;  /* sfix33_En24 */
  logic signed [34:0] ZAdder_add_cast;  /* sfix35_En34 */
  logic signed [34:0] zout2;  /* sfix35_En34 */
  logic signed [34:0] ZSub_sub_cast;  /* sfix35_En34 */
  logic signed [34:0] zout1;  /* sfix35_En34 */


  assign yLessThanZero = yin < 33'sh000000000;

  assign dynamic_shift_cast = {2'b0, idx};
  assign yShifted = yin >>> dynamic_shift_cast;

  assign xout2 = xin + yShifted;

  assign xout1 = xin - yShifted;

  assign xout = (yLessThanZero == 1'b0 ? xout2 :
              xout1);

  assign dynamic_shift_cast_1 = {2'b0, idx};
  assign xShifted = xin >>> dynamic_shift_cast_1;

  assign yout2 = yin - xShifted;

  assign yout1 = yin + xShifted;

  assign yout = (yLessThanZero == 1'b0 ? yout2 :
              yout1);

  assign ZAdder_add_cast = {3'b0, lut_value};
  assign zout2 = zin + ZAdder_add_cast;

  assign ZSub_sub_cast = {3'b0, lut_value};
  assign zout1 = zin - ZSub_sub_cast;

  assign zout = (yLessThanZero == 1'b0 ? zout2 :
              zout1);

endmodule  // CordicKernelMag

