// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/CP_Correlation_to_Frequency.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: CP_Correlation_to_Frequency
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Frequency Offset/CP Correlation to Frequency
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module CP_Correlation_to_Frequency
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [31:0] cpCorr_re  /* sfix32_En24 */,
             input logic signed [31:0] cpCorr_im  /* sfix32_En24 */,
             input logic cpCorrValid,
             output logic signed [31:0] cpFreqOffset  /* int32 */,
             output logic cpFreqOffsetValid);


  logic signed [34:0] Complex_to_Magnitude_Angle_out1;  /* sfix35_En34 */
  logic Complex_to_Magnitude_Angle_out2;
  logic signed [69:0] Multiply_cast;  /* sfix70_En44 */
  logic signed [31:0] Multiply_out1;  /* int32 */
  logic signed [31:0] Delay9_out1;  /* int32 */
  logic Delay1_out1;


  HDL_CMA_core u_Complex_to_Magnitude_Angle (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .In_re(cpCorr_re),  /* sfix32_En24 */
                                             .In_im(cpCorr_im),  /* sfix32_En24 */
                                             .validIn(cpCorrValid),
                                             .angle(Complex_to_Magnitude_Angle_out1),  /* sfix35_En34 */
                                             .validOut(Complex_to_Magnitude_Angle_out2)
                                             );

  assign Multiply_cast = {{2{Complex_to_Magnitude_Angle_out1[34]}}, {Complex_to_Magnitude_Angle_out1, 33'b000000000000000000000000000000000}};
  assign Multiply_out1 = ({{6{Multiply_cast[69]}}, Multiply_cast[69:44]}) + $signed({1'b0, Multiply_cast[43] & (( ~ Multiply_cast[69]) | (|Multiply_cast[42:0]))});

  always_ff @(posedge clk)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= Multiply_out1;
        end
      end
    end

  assign cpFreqOffset = Delay9_out1;

  always_ff @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Complex_to_Magnitude_Angle_out2;
        end
      end
    end

  assign cpFreqOffsetValid = Delay1_out1;

endmodule  // CP_Correlation_to_Frequency

