// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Delay_Enabled_Synchronous1_block.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Delay_Enabled_Synchronous1_block
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Windowed Peak Finder/Delay Balance/Delay 
// Enabled Synchronous
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Delay_Enabled_Synchronous1_block
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] u  /* ufix32_En24 */,
             input logic E,
             output logic [31:0] y  /* ufix32_En24 */);


  logic [31:0] Synchronous_Delay_y;  /* ufix32_En24 */


  Synchronous_Delay_block2 u_Synchronous_Delay (.clk(clk),
                                                .reset(reset),
                                                .enb(enb),
                                                .u(u),  /* ufix32_En24 */
                                                .E(E),
                                                .y(Synchronous_Delay_y)  /* ufix32_En24 */
                                                );

  assign y = Synchronous_Delay_y;

endmodule  // Delay_Enabled_Synchronous1_block

