// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Discrete_FIR_Filter.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Discrete_FIR_Filter
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Thresholded Correlator/Correlator/Discrete 
// FIR Filte
// Hierarchy Level: 5
// Model version: 10.1
// 
// Discrete FIR Filter
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Discrete_FIR_Filter
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             output logic signed [17:0] dataOut_re  /* sfix18_En13 */,
             output logic signed [17:0] dataOut_im  /* sfix18_En13 */,
             output logic validOut);


  logic syncReset;


  assign syncReset = 1'b0;

  Filter u_FilterBank (.clk(clk),
                       .reset(reset),
                       .enb(enb),
                       .dataIn_re(dataIn_re),  /* sfix16_En15 */
                       .dataIn_im(dataIn_im),  /* sfix16_En15 */
                       .validIn(validIn),
                       .syncReset(syncReset),
                       .dataOut_re(dataOut_re),  /* sfix18_En13 */
                       .dataOut_im(dataOut_im),  /* sfix18_En13 */
                       .validOut(validOut)
                       );

endmodule  // Discrete_FIR_Filter

