// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/dsphdl_FFT.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: dsphdl_FFT
// Source Path: introOFDMReceiver/OFDM Receiver/OFDM Demodulation/OFDM Demodulator/dsphdl.FFT
// Hierarchy Level: 3
// Model version: 10.1
// 
// FFT
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module dsphdl_FFT
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             output logic signed [23:0] dataOut_re  /* sfix24_En15 */,
             output logic signed [23:0] dataOut_im  /* sfix24_En15 */,
             output logic startOut,
             output logic validOut);


  logic softReset;
  rxsl_vector_of_signed_logic_16 intdelay_reg [0:2];  /* sfix16 [3] */
  logic signed [15:0] din_1_1_re_dly;  /* sfix16_En15 */
  rxsl_vector_of_signed_logic_16 intdelay_reg_1 [0:2];  /* sfix16 [3] */
  logic signed [15:0] din_1_1_im_dly;  /* sfix16_En15 */
  logic [2:0] intdelay_reg_2;  /* ufix1 [3] */
  logic din_1_vld_dly;
  logic dinXTwdl_1_1_vld;
  logic [6:0] rd_1_Addr;  /* ufix7 */
  logic rd_1_Enb;
  logic proc_1_enb;
  logic signed [16:0] dout_1_1_re;  /* sfix17_En15 */
  logic signed [16:0] dout_1_1_im;  /* sfix17_En15 */
  logic dout_1_1_vld;
  logic dinXTwdl_2_1_vld;
  logic [5:0] rd_2_Addr;  /* ufix6 */
  logic rd_2_Enb;
  logic proc_2_enb;
  logic multiply_2_J;
  logic signed [17:0] dout_2_1_re;  /* sfix18_En15 */
  logic signed [17:0] dout_2_1_im;  /* sfix18_En15 */
  logic dout_2_1_vld;
  rxsl_vector_of_signed_logic_18 intdelay_reg_3 [0:2];  /* sfix18 [3] */
  logic signed [17:0] din_3_1_re_dly;  /* sfix18_En15 */
  rxsl_vector_of_signed_logic_18 intdelay_reg_4 [0:2];  /* sfix18 [3] */
  logic signed [17:0] din_3_1_im_dly;  /* sfix18_En15 */
  logic [2:0] intdelay_reg_5;  /* ufix1 [3] */
  logic din_3_vld_dly;
  logic signed [15:0] twdl_3_1_re;  /* sfix16_En14 */
  logic signed [15:0] twdl_3_1_im;  /* sfix16_En14 */
  logic dinXTwdl_3_1_vld;
  logic [4:0] rd_3_Addr;  /* ufix5 */
  logic rd_3_Enb;
  logic proc_3_enb;
  logic signed [18:0] dout_3_1_re;  /* sfix19_En15 */
  logic signed [18:0] dout_3_1_im;  /* sfix19_En15 */
  logic dout_3_1_vld;
  logic dinXTwdl_4_1_vld;
  logic [3:0] rd_4_Addr;  /* ufix4 */
  logic rd_4_Enb;
  logic proc_4_enb;
  logic multiply_4_J;
  logic signed [19:0] dout_4_1_re;  /* sfix20_En15 */
  logic signed [19:0] dout_4_1_im;  /* sfix20_En15 */
  logic dout_4_1_vld;
  rxsl_vector_of_signed_logic_20 intdelay_reg_6 [0:2];  /* sfix20 [3] */
  logic signed [19:0] din_5_1_re_dly;  /* sfix20_En15 */
  rxsl_vector_of_signed_logic_20 intdelay_reg_7 [0:2];  /* sfix20 [3] */
  logic signed [19:0] din_5_1_im_dly;  /* sfix20_En15 */
  logic [2:0] intdelay_reg_8;  /* ufix1 [3] */
  logic din_5_vld_dly;
  logic signed [15:0] twdl_5_1_re;  /* sfix16_En14 */
  logic signed [15:0] twdl_5_1_im;  /* sfix16_En14 */
  logic dinXTwdl_5_1_vld;
  logic [2:0] rd_5_Addr;  /* ufix3 */
  logic rd_5_Enb;
  logic proc_5_enb;
  logic signed [20:0] dout_5_1_re;  /* sfix21_En15 */
  logic signed [20:0] dout_5_1_im;  /* sfix21_En15 */
  logic dout_5_1_vld;
  logic dinXTwdl_6_1_vld;
  logic [1:0] rd_6_Addr;  /* ufix2 */
  logic rd_6_Enb;
  logic proc_6_enb;
  logic multiply_6_J;
  logic signed [21:0] dout_6_1_re;  /* sfix22_En15 */
  logic signed [21:0] dout_6_1_im;  /* sfix22_En15 */
  logic dout_6_1_vld;
  rxsl_vector_of_signed_logic_22 intdelay_reg_9 [0:2];  /* sfix22 [3] */
  logic signed [21:0] din_7_1_re_dly;  /* sfix22_En15 */
  rxsl_vector_of_signed_logic_22 intdelay_reg_10 [0:2];  /* sfix22 [3] */
  logic signed [21:0] din_7_1_im_dly;  /* sfix22_En15 */
  logic [2:0] intdelay_reg_11;  /* ufix1 [3] */
  logic din_7_vld_dly;
  logic signed [15:0] twdl_7_1_re;  /* sfix16_En14 */
  logic signed [15:0] twdl_7_1_im;  /* sfix16_En14 */
  logic dinXTwdl_7_1_vld;
  logic rd_7_Addr;  /* ufix1 */
  logic rd_7_Enb;
  logic proc_7_enb;
  logic signed [22:0] dout_7_1_re;  /* sfix23_En15 */
  logic signed [22:0] dout_7_1_im;  /* sfix23_En15 */
  logic dout_7_1_vld;
  logic dinXTwdl_8_1_vld;
  logic rd_8_Addr;
  logic rd_8_Enb;
  logic proc_8_enb;
  logic multiply_8_J;
  logic signed [23:0] dout_8_1_re;  /* sfix24_En15 */
  logic signed [23:0] dout_8_1_im;  /* sfix24_En15 */
  logic dout_8_1_vld;
  logic signed [23:0] dout_re1;  /* sfix24_En15 */
  logic signed [23:0] dout_im1;  /* sfix24_En15 */
  logic dout_vld1;
  logic startOutS;


  assign softReset = 1'b0;

  always_ff @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        intdelay_reg <= '{default :16'sb0000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg <= '{default :16'sb0000000000000000};
          end
          else begin
            intdelay_reg[0] <= dataIn_re;
            intdelay_reg[32'sd1:32'sd2] <= intdelay_reg[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_1_1_re_dly = intdelay_reg[2];

  always_ff @(posedge clk)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        intdelay_reg_1 <= '{default :16'sb0000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_1 <= '{default :16'sb0000000000000000};
          end
          else begin
            intdelay_reg_1[0] <= dataIn_im;
            intdelay_reg_1[32'sd1:32'sd2] <= intdelay_reg_1[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_1_1_im_dly = intdelay_reg_1[2];

  always_ff @(posedge clk)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        intdelay_reg_2 <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_2 <= '{default :1'b0};
          end
          else begin
            intdelay_reg_2[0] <= validIn;
            intdelay_reg_2[32'sd2:32'sd1] <= intdelay_reg_2[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_1_vld_dly = intdelay_reg_2[2];

  rxsl_RADIX22FFT_CTRL1_1 u_CTRL1_1_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld),
                                  .dinXTwdl_1_1_vld_1(dinXTwdl_1_1_vld),
                                  .rd_1_Addr(rd_1_Addr),  /* ufix7 */
                                  .rd_1_Enb(rd_1_Enb),
                                  .proc_1_enb(proc_1_enb)
                                  );

  rxsl_RADIX22FFT_SDF1_1 u_SDF1_1_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .din_1_1_re_dly(din_1_1_re_dly),  /* sfix16_En15 */
                                .din_1_1_im_dly(din_1_1_im_dly),  /* sfix16_En15 */
                                .din_1_vld_dly(din_1_vld_dly),
                                .rd_1_Addr(rd_1_Addr),  /* ufix7 */
                                .rd_1_Enb(rd_1_Enb),
                                .proc_1_enb(proc_1_enb),
                                .dout_1_1_re(dout_1_1_re),  /* sfix17_En15 */
                                .dout_1_1_im(dout_1_1_im),  /* sfix17_En15 */
                                .dout_1_1_vld(dout_1_1_vld),
                                .dinXTwdl_1_1_vld(dinXTwdl_1_1_vld)
                                );

  rxsl_RADIX22FFT_CTRL1_2 u_CTRL2_2_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dout_1_1_vld(dout_1_1_vld),
                                  .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld),
                                  .rd_2_Addr(rd_2_Addr),  /* ufix6 */
                                  .rd_2_Enb(rd_2_Enb),
                                  .proc_2_enb(proc_2_enb),
                                  .multiply_2_J(multiply_2_J)
                                  );

  rxsl_RADIX22FFT_SDF2_2 u_SDF2_2_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .dout_1_1_re(dout_1_1_re),  /* sfix17_En15 */
                                .dout_1_1_im(dout_1_1_im),  /* sfix17_En15 */
                                .dout_1_1_vld(dout_1_1_vld),
                                .rd_2_Addr(rd_2_Addr),  /* ufix6 */
                                .rd_2_Enb(rd_2_Enb),
                                .proc_2_enb(proc_2_enb),
                                .multiply_2_J(multiply_2_J),
                                .dout_2_1_re(dout_2_1_re),  /* sfix18_En15 */
                                .dout_2_1_im(dout_2_1_im),  /* sfix18_En15 */
                                .dout_2_1_vld(dout_2_1_vld),
                                .dinXTwdl_2_1_vld(dinXTwdl_2_1_vld)
                                );

  always_ff @(posedge clk)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        intdelay_reg_3 <= '{default :18'sb000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_3 <= '{default :18'sb000000000000000000};
          end
          else begin
            intdelay_reg_3[0] <= dout_2_1_re;
            intdelay_reg_3[32'sd1:32'sd2] <= intdelay_reg_3[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_3_1_re_dly = intdelay_reg_3[2];

  always_ff @(posedge clk)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        intdelay_reg_4 <= '{default :18'sb000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_4 <= '{default :18'sb000000000000000000};
          end
          else begin
            intdelay_reg_4[0] <= dout_2_1_im;
            intdelay_reg_4[32'sd1:32'sd2] <= intdelay_reg_4[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_3_1_im_dly = intdelay_reg_4[2];

  always_ff @(posedge clk)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        intdelay_reg_5 <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_5 <= '{default :1'b0};
          end
          else begin
            intdelay_reg_5[0] <= dout_2_1_vld;
            intdelay_reg_5[32'sd2:32'sd1] <= intdelay_reg_5[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_3_vld_dly = intdelay_reg_5[2];

  rxsl_TWDLROM_3_1 u_twdlROM_3_1 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .dout_2_1_vld(dout_2_1_vld),
                             .twdl_3_1_re(twdl_3_1_re),  /* sfix16_En14 */
                             .twdl_3_1_im(twdl_3_1_im)  /* sfix16_En14 */
                             );

  rxsl_RADIX22FFT_CTRL1_3 u_CTRL1_3_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld),
                                  .dinXTwdl_3_1_vld_1(dinXTwdl_3_1_vld),
                                  .rd_3_Addr(rd_3_Addr),  /* ufix5 */
                                  .rd_3_Enb(rd_3_Enb),
                                  .proc_3_enb(proc_3_enb)
                                  );

  rxsl_RADIX22FFT_SDF1_3 u_SDF1_3_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .din_3_1_re_dly(din_3_1_re_dly),  /* sfix18_En15 */
                                .din_3_1_im_dly(din_3_1_im_dly),  /* sfix18_En15 */
                                .din_3_vld_dly(din_3_vld_dly),
                                .rd_3_Addr(rd_3_Addr),  /* ufix5 */
                                .rd_3_Enb(rd_3_Enb),
                                .twdl_3_1_re(twdl_3_1_re),  /* sfix16_En14 */
                                .twdl_3_1_im(twdl_3_1_im),  /* sfix16_En14 */
                                .proc_3_enb(proc_3_enb),
                                .dout_3_1_re(dout_3_1_re),  /* sfix19_En15 */
                                .dout_3_1_im(dout_3_1_im),  /* sfix19_En15 */
                                .dout_3_1_vld(dout_3_1_vld),
                                .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                                );

  rxsl_RADIX22FFT_CTRL1_4 u_CTRL2_4_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dout_3_1_vld(dout_3_1_vld),
                                  .dinXTwdl_4_1_vld(dinXTwdl_4_1_vld),
                                  .rd_4_Addr(rd_4_Addr),  /* ufix4 */
                                  .rd_4_Enb(rd_4_Enb),
                                  .proc_4_enb(proc_4_enb),
                                  .multiply_4_J(multiply_4_J)
                                  );

  rxsl_RADIX22FFT_SDF2_4 u_SDF2_4_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .dout_3_1_re(dout_3_1_re),  /* sfix19_En15 */
                                .dout_3_1_im(dout_3_1_im),  /* sfix19_En15 */
                                .dout_3_1_vld(dout_3_1_vld),
                                .rd_4_Addr(rd_4_Addr),  /* ufix4 */
                                .rd_4_Enb(rd_4_Enb),
                                .proc_4_enb(proc_4_enb),
                                .multiply_4_J(multiply_4_J),
                                .dout_4_1_re(dout_4_1_re),  /* sfix20_En15 */
                                .dout_4_1_im(dout_4_1_im),  /* sfix20_En15 */
                                .dout_4_1_vld(dout_4_1_vld),
                                .dinXTwdl_4_1_vld(dinXTwdl_4_1_vld)
                                );

  always_ff @(posedge clk)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        intdelay_reg_6 <= '{default :20'sb00000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_6 <= '{default :20'sb00000000000000000000};
          end
          else begin
            intdelay_reg_6[0] <= dout_4_1_re;
            intdelay_reg_6[32'sd1:32'sd2] <= intdelay_reg_6[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_5_1_re_dly = intdelay_reg_6[2];

  always_ff @(posedge clk)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        intdelay_reg_7 <= '{default :20'sb00000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_7 <= '{default :20'sb00000000000000000000};
          end
          else begin
            intdelay_reg_7[0] <= dout_4_1_im;
            intdelay_reg_7[32'sd1:32'sd2] <= intdelay_reg_7[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_5_1_im_dly = intdelay_reg_7[2];

  always_ff @(posedge clk)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        intdelay_reg_8 <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_8 <= '{default :1'b0};
          end
          else begin
            intdelay_reg_8[0] <= dout_4_1_vld;
            intdelay_reg_8[32'sd2:32'sd1] <= intdelay_reg_8[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_5_vld_dly = intdelay_reg_8[2];

  rxsl_TWDLROM_5_1 u_twdlROM_5_1 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .dout_4_1_vld(dout_4_1_vld),
                             .twdl_5_1_re(twdl_5_1_re),  /* sfix16_En14 */
                             .twdl_5_1_im(twdl_5_1_im)  /* sfix16_En14 */
                             );

  rxsl_RADIX22FFT_CTRL1_5 u_CTRL1_5_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dinXTwdl_5_1_vld(dinXTwdl_5_1_vld),
                                  .dinXTwdl_5_1_vld_1(dinXTwdl_5_1_vld),
                                  .rd_5_Addr(rd_5_Addr),  /* ufix3 */
                                  .rd_5_Enb(rd_5_Enb),
                                  .proc_5_enb(proc_5_enb)
                                  );

  rxsl_RADIX22FFT_SDF1_5 u_SDF1_5_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .din_5_1_re_dly(din_5_1_re_dly),  /* sfix20_En15 */
                                .din_5_1_im_dly(din_5_1_im_dly),  /* sfix20_En15 */
                                .din_5_vld_dly(din_5_vld_dly),
                                .rd_5_Addr(rd_5_Addr),  /* ufix3 */
                                .rd_5_Enb(rd_5_Enb),
                                .twdl_5_1_re(twdl_5_1_re),  /* sfix16_En14 */
                                .twdl_5_1_im(twdl_5_1_im),  /* sfix16_En14 */
                                .proc_5_enb(proc_5_enb),
                                .dout_5_1_re(dout_5_1_re),  /* sfix21_En15 */
                                .dout_5_1_im(dout_5_1_im),  /* sfix21_En15 */
                                .dout_5_1_vld(dout_5_1_vld),
                                .dinXTwdl_5_1_vld(dinXTwdl_5_1_vld)
                                );

  rxsl_RADIX22FFT_CTRL1_6 u_CTRL2_6_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dout_5_1_vld(dout_5_1_vld),
                                  .dinXTwdl_6_1_vld(dinXTwdl_6_1_vld),
                                  .rd_6_Addr(rd_6_Addr),  /* ufix2 */
                                  .rd_6_Enb(rd_6_Enb),
                                  .proc_6_enb(proc_6_enb),
                                  .multiply_6_J(multiply_6_J)
                                  );

  rxsl_RADIX22FFT_SDF2_6 u_SDF2_6_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .dout_5_1_re(dout_5_1_re),  /* sfix21_En15 */
                                .dout_5_1_im(dout_5_1_im),  /* sfix21_En15 */
                                .dout_5_1_vld(dout_5_1_vld),
                                .rd_6_Addr(rd_6_Addr),  /* ufix2 */
                                .rd_6_Enb(rd_6_Enb),
                                .proc_6_enb(proc_6_enb),
                                .multiply_6_J(multiply_6_J),
                                .dout_6_1_re(dout_6_1_re),  /* sfix22_En15 */
                                .dout_6_1_im(dout_6_1_im),  /* sfix22_En15 */
                                .dout_6_1_vld(dout_6_1_vld),
                                .dinXTwdl_6_1_vld(dinXTwdl_6_1_vld)
                                );

  always_ff @(posedge clk)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        intdelay_reg_9 <= '{default :22'sb0000000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_9 <= '{default :22'sb0000000000000000000000};
          end
          else begin
            intdelay_reg_9[0] <= dout_6_1_re;
            intdelay_reg_9[32'sd1:32'sd2] <= intdelay_reg_9[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_7_1_re_dly = intdelay_reg_9[2];

  always_ff @(posedge clk)
    begin : intdelay_10_process
      if (reset == 1'b1) begin
        intdelay_reg_10 <= '{default :22'sb0000000000000000000000};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_10 <= '{default :22'sb0000000000000000000000};
          end
          else begin
            intdelay_reg_10[0] <= dout_6_1_im;
            intdelay_reg_10[32'sd1:32'sd2] <= intdelay_reg_10[32'sd0:32'sd1];
          end
        end
      end
    end

  assign din_7_1_im_dly = intdelay_reg_10[2];

  always_ff @(posedge clk)
    begin : intdelay_11_process
      if (reset == 1'b1) begin
        intdelay_reg_11 <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          if (softReset == 1'b1) begin
            intdelay_reg_11 <= '{default :1'b0};
          end
          else begin
            intdelay_reg_11[0] <= dout_6_1_vld;
            intdelay_reg_11[32'sd2:32'sd1] <= intdelay_reg_11[32'sd1:32'sd0];
          end
        end
      end
    end

  assign din_7_vld_dly = intdelay_reg_11[2];

  rxsl_TWDLROM_7_1 u_twdlROM_7_1 (.clk(clk),
                             .reset(reset),
                             .enb(enb),
                             .dout_6_1_vld(dout_6_1_vld),
                             .twdl_7_1_re(twdl_7_1_re),  /* sfix16_En14 */
                             .twdl_7_1_im(twdl_7_1_im)  /* sfix16_En14 */
                             );

  rxsl_RADIX22FFT_CTRL1_7 u_CTRL1_7_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld),
                                  .dinXTwdl_7_1_vld_1(dinXTwdl_7_1_vld),
                                  .rd_7_Addr(rd_7_Addr),  /* ufix1 */
                                  .rd_7_Enb(rd_7_Enb),
                                  .proc_7_enb(proc_7_enb)
                                  );

  rxsl_RADIX22FFT_SDF1_7 u_SDF1_7_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .din_7_1_re_dly(din_7_1_re_dly),  /* sfix22_En15 */
                                .din_7_1_im_dly(din_7_1_im_dly),  /* sfix22_En15 */
                                .din_7_vld_dly(din_7_vld_dly),
                                .rd_7_Addr(rd_7_Addr),  /* ufix1 */
                                .rd_7_Enb(rd_7_Enb),
                                .twdl_7_1_re(twdl_7_1_re),  /* sfix16_En14 */
                                .twdl_7_1_im(twdl_7_1_im),  /* sfix16_En14 */
                                .proc_7_enb(proc_7_enb),
                                .dout_7_1_re(dout_7_1_re),  /* sfix23_En15 */
                                .dout_7_1_im(dout_7_1_im),  /* sfix23_En15 */
                                .dout_7_1_vld(dout_7_1_vld),
                                .dinXTwdl_7_1_vld(dinXTwdl_7_1_vld)
                                );

  rxsl_RADIX22FFT_CTRL1_8 u_CTRL2_8_1 (.clk(clk),
                                  .reset(reset),
                                  .enb(enb),
                                  .dout_7_1_vld(dout_7_1_vld),
                                  .dinXTwdl_8_1_vld(dinXTwdl_8_1_vld),
                                  .rd_8_Addr(rd_8_Addr),
                                  .rd_8_Enb(rd_8_Enb),
                                  .proc_8_enb(proc_8_enb),
                                  .multiply_8_J(multiply_8_J)
                                  );

  rxsl_RADIX22FFT_SDF2_8 u_SDF2_8_1 (.clk(clk),
                                .reset(reset),
                                .enb(enb),
                                .dout_7_1_re(dout_7_1_re),  /* sfix23_En15 */
                                .dout_7_1_im(dout_7_1_im),  /* sfix23_En15 */
                                .dout_7_1_vld(dout_7_1_vld),
                                .rd_8_Addr(rd_8_Addr),
                                .rd_8_Enb(rd_8_Enb),
                                .proc_8_enb(proc_8_enb),
                                .multiply_8_J(multiply_8_J),
                                .dout_8_1_re(dout_8_1_re),  /* sfix24_En15 */
                                .dout_8_1_im(dout_8_1_im),  /* sfix24_En15 */
                                .dout_8_1_vld(dout_8_1_vld),
                                .dinXTwdl_8_1_vld(dinXTwdl_8_1_vld)
                                );

  rxsl_RADIX2FFT_bitNatural u_NaturalOrder_Stage (.clk(clk),
                                             .reset(reset),
                                             .enb(enb),
                                             .dout_8_1_re(dout_8_1_re),  /* sfix24_En15 */
                                             .dout_8_1_im(dout_8_1_im),  /* sfix24_En15 */
                                             .dout_8_1_vld(dout_8_1_vld),
                                             .dout_re1(dout_re1),  /* sfix24_En15 */
                                             .dout_im1(dout_im1),  /* sfix24_En15 */
                                             .dout_vld1(dout_vld1),
                                             .startOutS(startOutS)
                                             );

  assign dataOut_re = dout_re1;

  assign dataOut_im = dout_im1;

  assign startOut = startOutS;

  assign validOut = dout_vld1;

endmodule  // dsphdl_FFT

