// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_FIFO.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: rxsl_FIFO
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Two Data Stream Synchronizer/FWFT 
// rxsl_FIFO/FIF
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_FIFO
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] In_re  /* sfix16_En15 */,
             input logic signed [15:0] In_im  /* sfix16_En15 */,
             input logic Push,
             input logic Pop,
             output logic signed [15:0] Out_re  /* sfix16_En15 */,
             output logic signed [15:0] Out_im  /* sfix16_En15 */,
             output logic Empty,
             output logic Full);


  logic [3:0] count_step;  /* ufix4 */
  logic [3:0] num_out1;  /* ufix4 */
  logic [3:0] count;  /* ufix4 */
  logic [3:0] count_1;  /* ufix4 */
  logic Logical_Operator2_out1;
  logic [3:0] count_value;  /* ufix4 */
  logic Compare_To_Constant_out1;
  logic not_full;
  logic Logical_Operator1_out1;
  logic Logical_Operator_out1;
  logic [3:0] count_2;  /* ufix4 */
  logic Compare_To_Zero1_out1;
  logic not_empty;
  logic read_prev_out1;
  logic [2:0] count_step_1;  /* ufix3 */
  logic [2:0] count_from;  /* ufix3 */
  logic [2:0] wrPtr_out1;  /* ufix3 */
  logic [2:0] count_3;  /* ufix3 */
  logic need_to_wrap;
  logic [2:0] count_value_1;  /* ufix3 */
  logic [2:0] count_4;  /* ufix3 */
  logic [2:0] count_step_2;  /* ufix3 */
  logic [2:0] count_from_1;  /* ufix3 */
  logic [2:0] rdPtr_out1;  /* ufix3 */
  logic [2:0] count_5;  /* ufix3 */
  logic need_to_wrap_1;
  logic [2:0] count_value_2;  /* ufix3 */
  logic [2:0] count_6;  /* ufix3 */
  logic signed [15:0] Simple_Dual_Port_RAM_System_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Simple_Dual_Port_RAM_System_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Switch_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Switch_out1_im;  /* sfix16_En15 */
  logic signed [15:0] out_prev_out1_re;  /* sfix16_En15 */
  logic signed [15:0] out_prev_out1_im;  /* sfix16_En15 */

  // rxsl_FIFO buffer
  // don't write if full
  // count entries in rxsl_FIFO
  // write address counter
  // read address counter
  // don't read if empty


  // Free running, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  assign count_step = 4'b0001;

  assign count = num_out1 + count_step;

  assign count_1 = num_out1 - count_step;

  assign count_value = (Logical_Operator2_out1 == 1'b0 ? count_1 :
              count);

  assign Compare_To_Constant_out1 = num_out1 == 4'b1000;

  assign not_full =  ~ Compare_To_Constant_out1;

  assign Logical_Operator2_out1 = Push & not_full;

  assign Logical_Operator_out1 = Logical_Operator2_out1 ^ Logical_Operator1_out1;

  assign count_2 = (Logical_Operator_out1 == 1'b0 ? num_out1 :
              count_value);

  always_ff @(posedge clk)
    begin : num_process
      if (reset == 1'b1) begin
        num_out1 <= 4'b0000;
      end
      else begin
        if (enb) begin
          num_out1 <= count_2;
        end
      end
    end

  assign Compare_To_Zero1_out1 = num_out1 == 4'b0000;

  assign not_empty =  ~ Compare_To_Zero1_out1;

  assign Logical_Operator1_out1 = not_empty & Pop;

  always_ff @(posedge clk)
    begin : read_prev_process
      if (reset == 1'b1) begin
        read_prev_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          read_prev_out1 <= Logical_Operator1_out1;
        end
      end
    end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  assign count_step_1 = 3'b001;

  assign count_from = 3'b000;

  assign count_3 = wrPtr_out1 + count_step_1;

  assign need_to_wrap = wrPtr_out1 == 3'b111;

  assign count_value_1 = (need_to_wrap == 1'b0 ? count_3 :
              count_from);

  assign count_4 = (Logical_Operator2_out1 == 1'b0 ? wrPtr_out1 :
              count_value_1);

  always_ff @(posedge clk)
    begin : wrPtr_process
      if (reset == 1'b1) begin
        wrPtr_out1 <= 3'b000;
      end
      else begin
        if (enb) begin
          wrPtr_out1 <= count_4;
        end
      end
    end

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 7
  assign count_step_2 = 3'b001;

  assign count_from_1 = 3'b000;

  assign count_5 = rdPtr_out1 + count_step_2;

  assign need_to_wrap_1 = rdPtr_out1 == 3'b111;

  assign count_value_2 = (need_to_wrap_1 == 1'b0 ? count_5 :
              count_from_1);

  assign count_6 = (Logical_Operator1_out1 == 1'b0 ? rdPtr_out1 :
              count_value_2);

  always_ff @(posedge clk)
    begin : rdPtr_process
      if (reset == 1'b1) begin
        rdPtr_out1 <= 3'b000;
      end
      else begin
        if (enb) begin
          rdPtr_out1 <= count_6;
        end
      end
    end

  rxsl_SimpleDualPortRAM_generic #(.AddrWidth(3),
                              .DataWidth(16)
                              )
                            u_Simple_Dual_Port_RAM_System (.clk(clk),
                                                           .enb(enb),
                                                           .wr_din_re(In_re),
                                                           .wr_din_im(In_im),
                                                           .wr_addr(wrPtr_out1),
                                                           .wr_en(Logical_Operator2_out1),
                                                           .rd_addr(rdPtr_out1),
                                                           .dout_re(Simple_Dual_Port_RAM_System_out1_re),
                                                           .dout_im(Simple_Dual_Port_RAM_System_out1_im)
                                                           );

  always_ff @(posedge clk)
    begin : out_prev_process
      if (reset == 1'b1) begin
        out_prev_out1_re <= 16'sb0000000000000000;
        out_prev_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          out_prev_out1_re <= Switch_out1_re;
          out_prev_out1_im <= Switch_out1_im;
        end
      end
    end

  assign Switch_out1_re = (read_prev_out1 == 1'b0 ? out_prev_out1_re :
              Simple_Dual_Port_RAM_System_out1_re);
  assign Switch_out1_im = (read_prev_out1 == 1'b0 ? out_prev_out1_im :
              Simple_Dual_Port_RAM_System_out1_im);

  assign Out_re = Switch_out1_re;

  assign Out_im = Switch_out1_im;

  assign Empty = Compare_To_Zero1_out1;

  assign Full = Compare_To_Constant_out1;

endmodule  // rxsl_FIFO

