// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_Frame_Counter.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rxsl_Frame_Counter
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Grid Structure/Frame Counter
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_Frame_Counter
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic validIn,
             output logic frameStart,
             output logic validOut,
             output logic [8:0] symNum  /* ufix9 */);


  logic [7:0] count_step;  /* uint8 */
  logic [7:0] count_from;  /* uint8 */
  logic [7:0] subcarrier_counter_out1;  /* uint8 */
  logic [7:0] count;  /* uint8 */
  logic need_to_wrap;
  logic [7:0] count_value;  /* uint8 */
  logic [7:0] count_1;  /* uint8 */
  logic Compare_To_Constant1_out1;
  logic range_hit;
  logic subcarrier_counter_out2;
  logic AND2_out1;
  logic [8:0] count_step_1;  /* ufix9 */
  logic [8:0] count_from_1;  /* ufix9 */
  logic [8:0] ofdm_symbol_counter_out1;  /* ufix9 */
  logic [8:0] count_2;  /* ufix9 */
  logic need_to_wrap_1;
  logic [8:0] count_value_1;  /* ufix9 */
  logic [8:0] count_3;  /* ufix9 */
  logic Compare_To_Constant2_out1;
  logic AND1_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 227
  assign count_step = 8'b00000001;

  assign count_from = 8'b00000000;

  assign count = subcarrier_counter_out1 + count_step;

  assign need_to_wrap = subcarrier_counter_out1 == 8'b11100011;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? subcarrier_counter_out1 :
              count_value);

  always_ff @(posedge clk)
    begin : subcarrier_counter_process
      if (reset == 1'b1) begin
        subcarrier_counter_out1 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          subcarrier_counter_out1 <= count_1;
        end
      end
    end

  assign Compare_To_Constant1_out1 = subcarrier_counter_out1 == 8'b00000000;

  assign range_hit = subcarrier_counter_out1 > 8'b11111110;

  assign subcarrier_counter_out2 = need_to_wrap | range_hit;

  assign AND2_out1 = subcarrier_counter_out2 & validIn;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 27
  assign count_step_1 = 9'b000000001;

  assign count_from_1 = 9'b000000000;

  assign count_2 = ofdm_symbol_counter_out1 + count_step_1;

  assign need_to_wrap_1 = ofdm_symbol_counter_out1 == 9'b000011011;

  assign count_value_1 = (need_to_wrap_1 == 1'b0 ? count_2 :
              count_from_1);

  assign count_3 = (AND2_out1 == 1'b0 ? ofdm_symbol_counter_out1 :
              count_value_1);

  always_ff @(posedge clk)
    begin : ofdm_symbol_counter_process
      if (reset == 1'b1) begin
        ofdm_symbol_counter_out1 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          ofdm_symbol_counter_out1 <= count_3;
        end
      end
    end

  assign Compare_To_Constant2_out1 = ofdm_symbol_counter_out1 == 9'b000000000;

  assign AND1_out1 = Compare_To_Constant2_out1 & (validIn & Compare_To_Constant1_out1);

  assign frameStart = AND1_out1;

  assign validOut = validIn;

  assign symNum = ofdm_symbol_counter_out1;

endmodule  // rxsl_Frame_Counter

