// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Frequency_Correction.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Frequency_Correction
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Synchronize/Frequency Correction
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Frequency_Correction
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic freqCorrectionEn,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             input logic signed [31:0] frequencyOffset  /* int32 */,
             output logic signed [15:0] dataOut_re  /* sfix16_En15 */,
             output logic signed [15:0] dataOut_im  /* sfix16_En15 */,
             output logic validOut);


  rxsl_vector_of_signed_logic_16 Delay6_reg_re [0:5];  /* sfix16_En15 [6] */
  rxsl_vector_of_signed_logic_16 Delay6_reg_im [0:5];  /* sfix16_En15 [6] */
  logic signed [15:0] Delay6_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay6_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay1_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay1_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Constant_out1_re;  /* sfix16_En14 */
  logic signed [15:0] Constant_out1_im;  /* sfix16_En14 */
  logic signed [32:0] Gain_in0;  /* sfix33 */
  logic signed [32:0] Gain_1;  /* sfix33 */
  logic signed [31:0] Gain_out1;  /* int32 */
  logic signed [15:0] NCO_HDL_Optimized_out1_re;  /* sfix16_En14 */
  logic signed [15:0] NCO_HDL_Optimized_out1_im;  /* sfix16_En14 */
  logic NCO_HDL_Optimized_out2;
  logic signed [15:0] Multiport_Switch_out1_re;  /* sfix16_En14 */
  logic signed [15:0] Multiport_Switch_out1_im;  /* sfix16_En14 */
  logic signed [15:0] Delay2_out1_re;  /* sfix16_En14 */
  logic signed [15:0] Delay2_out1_im;  /* sfix16_En14 */
  logic signed [31:0] Product_mul_temp;  /* sfix32_En29 */
  logic signed [31:0] Product_mul_temp_1;  /* sfix32_En29 */
  logic signed [31:0] Product_mul_temp_2;  /* sfix32_En29 */
  logic signed [31:0] Product_mul_temp_3;  /* sfix32_En29 */
  logic signed [31:0] Product_out1_re;  /* sfix32_En29 */
  logic signed [31:0] Product_out1_im;  /* sfix32_En29 */
  logic signed [31:0] Delay4_out1_re;  /* sfix32_En29 */
  logic signed [31:0] Delay4_out1_im;  /* sfix32_En29 */
  logic signed [15:0] Data_Type_Conversion_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Data_Type_Conversion_out1_im;  /* sfix16_En15 */
  logic signed [15:0] Delay7_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay7_out1_im;  /* sfix16_En15 */
  logic Delay3_out1;
  logic Delay5_out1;
  logic Delay8_out1;


  always_ff @(posedge clk)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_reg_re <= '{default :16'sb0000000000000000};
        Delay6_reg_im <= '{default :16'sb0000000000000000};
      end
      else begin
        if (enb) begin
          Delay6_reg_im[0] <= dataIn_im;
          Delay6_reg_im[32'sd1:32'sd5] <= Delay6_reg_im[32'sd0:32'sd4];
          Delay6_reg_re[0] <= dataIn_re;
          Delay6_reg_re[32'sd1:32'sd5] <= Delay6_reg_re[32'sd0:32'sd4];
        end
      end
    end

  assign Delay6_out1_re = Delay6_reg_re[5];
  assign Delay6_out1_im = Delay6_reg_im[5];

  always_ff @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1_re <= 16'sb0000000000000000;
        Delay1_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1_re <= Delay6_out1_re;
          Delay1_out1_im <= Delay6_out1_im;
        end
      end
    end

  assign Constant_out1_re = 16'sb0100000000000000;
  assign Constant_out1_im = 16'sb0000000000000000;

  assign Gain_1 = {frequencyOffset[31], frequencyOffset};
  assign Gain_in0 =  - (Gain_1);
  assign Gain_out1 = Gain_in0[31:0];

  NCO_HDL_Optimized u_NCO_HDL_Optimized (.clk(clk),
                                         .reset(reset),
                                         .enb(enb),
                                         .inc(Gain_out1),  /* int32 */
                                         .validIn(validIn),
                                         .complexexp_re(NCO_HDL_Optimized_out1_re),  /* sfix16_En14 */
                                         .complexexp_im(NCO_HDL_Optimized_out1_im),  /* sfix16_En14 */
                                         .validOut(NCO_HDL_Optimized_out2)
                                         );

  assign Multiport_Switch_out1_re = (freqCorrectionEn == 1'b0 ? Constant_out1_re :
              NCO_HDL_Optimized_out1_re);
  assign Multiport_Switch_out1_im = (freqCorrectionEn == 1'b0 ? Constant_out1_im :
              NCO_HDL_Optimized_out1_im);

  always_ff @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1_re <= 16'sb0000000000000000;
        Delay2_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_re <= Multiport_Switch_out1_re;
          Delay2_out1_im <= Multiport_Switch_out1_im;
        end
      end
    end

  assign Product_mul_temp = Delay1_out1_re * Delay2_out1_re;
  assign Product_mul_temp_1 = Delay1_out1_im * Delay2_out1_im;
  assign Product_out1_re = Product_mul_temp - Product_mul_temp_1;
  assign Product_mul_temp_2 = Delay1_out1_im * Delay2_out1_re;
  assign Product_mul_temp_3 = Delay1_out1_re * Delay2_out1_im;
  assign Product_out1_im = Product_mul_temp_2 + Product_mul_temp_3;

  always_ff @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1_re <= 32'sb00000000000000000000000000000000;
        Delay4_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1_re <= Product_out1_re;
          Delay4_out1_im <= Product_out1_im;
        end
      end
    end

  assign Data_Type_Conversion_out1_re = Delay4_out1_re[29:14] + $signed({1'b0, Delay4_out1_re[13] & (( ~ Delay4_out1_re[31]) | (|Delay4_out1_re[12:0]))});
  assign Data_Type_Conversion_out1_im = Delay4_out1_im[29:14] + $signed({1'b0, Delay4_out1_im[13] & (( ~ Delay4_out1_im[31]) | (|Delay4_out1_im[12:0]))});

  always_ff @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1_re <= 16'sb0000000000000000;
        Delay7_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1_re <= Data_Type_Conversion_out1_re;
          Delay7_out1_im <= Data_Type_Conversion_out1_im;
        end
      end
    end

  assign dataOut_re = Delay7_out1_re;

  assign dataOut_im = Delay7_out1_im;

  always_ff @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= NCO_HDL_Optimized_out2;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= Delay3_out1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= Delay5_out1;
        end
      end
    end

  assign validOut = Delay8_out1;

endmodule  // Frequency_Correction

