// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Frequency_Offset.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Frequency_Offset
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Frequency Offset
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Frequency_Offset
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             output logic signed [31:0] frequencyOffset  /* int32 */,
             output logic validOut);


  logic signed [31:0] Cyclic_Prefix_Correlation_corrOut_re;  /* sfix32_En24 */
  logic signed [31:0] Cyclic_Prefix_Correlation_corrOut_im;  /* sfix32_En24 */
  logic Cyclic_Prefix_Correlation_validOut;
  logic signed [31:0] CP_Correlation_to_Frequency_cpFreqOffset;  /* int32 */
  logic CP_Correlation_to_Frequency_cpFreqOffsetValid;


  Cyclic_Prefix_Correlation u_Cyclic_Prefix_Correlation (.clk(clk),
                                                         .reset(reset),
                                                         .enb(enb),
                                                         .dataIn_re(dataIn_re),  /* sfix16_En15 */
                                                         .dataIn_im(dataIn_im),  /* sfix16_En15 */
                                                         .validIn(validIn),
                                                         .corrOut_re(Cyclic_Prefix_Correlation_corrOut_re),  /* sfix32_En24 */
                                                         .corrOut_im(Cyclic_Prefix_Correlation_corrOut_im),  /* sfix32_En24 */
                                                         .validOut(Cyclic_Prefix_Correlation_validOut)
                                                         );

  CP_Correlation_to_Frequency u_CP_Correlation_to_Frequency (.clk(clk),
                                                             .reset(reset),
                                                             .enb(enb),
                                                             .cpCorr_re(Cyclic_Prefix_Correlation_corrOut_re),  /* sfix32_En24 */
                                                             .cpCorr_im(Cyclic_Prefix_Correlation_corrOut_im),  /* sfix32_En24 */
                                                             .cpCorrValid(Cyclic_Prefix_Correlation_validOut),
                                                             .cpFreqOffset(CP_Correlation_to_Frequency_cpFreqOffset),  /* int32 */
                                                             .cpFreqOffsetValid(CP_Correlation_to_Frequency_cpFreqOffsetValid)
                                                             );

  assign frequencyOffset = CP_Correlation_to_Frequency_cpFreqOffset;

  assign validOut = CP_Correlation_to_Frequency_cpFreqOffsetValid;

endmodule  // Frequency_Offset

