// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Frequency_Stream_Synchronizer.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Frequency_Stream_Synchronizer
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Synchronize/Frequency Stream Synchronizer
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Frequency_Stream_Synchronizer
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic pop,
             input logic signed [31:0] dataIn  /* int32 */,
             input logic push,
             output logic signed [31:0] dataOut  /* int32 */,
             output logic validOut);


  logic [8:0] wrAddr;  /* ufix9 */
  logic wrEn;
  logic [8:0] rdAddr;  /* ufix9 */
  logic signed [31:0] Simple_Dual_Port_RAM_System_out1;  /* int32 */


  dataSync_block1 u_dataSync (.clk(clk),
                              .reset(reset),
                              .enb(enb),
                              .pop(pop),
                              .push(push),
                              .wrAddr(wrAddr),  /* ufix9 */
                              .wrEn(wrEn),
                              .rdAddr(rdAddr),  /* ufix9 */
                              .validOut(validOut)
                              );

  rxsl_SimpleDualPortRAM_generic_block #(.AddrWidth(9),
                                    .DataWidth(32)
                                    )
                                  u_Simple_Dual_Port_RAM_System (.clk(clk),
                                                                 .enb(enb),
                                                                 .wr_din(dataIn),
                                                                 .wr_addr(wrAddr),
                                                                 .wr_en(wrEn),
                                                                 .rd_addr(rdAddr),
                                                                 .dout(Simple_Dual_Port_RAM_System_out1)
                                                                 );

  assign dataOut = Simple_Dual_Port_RAM_System_out1;

endmodule  // Frequency_Stream_Synchronizer

