// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_Grid_Structure.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rxsl_Grid_Structure
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Grid Structure
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_Grid_Structure
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic validIn,
             output logic isData,
             output logic isRef,
             output logic frameStart);


  logic Frame_Counter_frameStart;
  logic Frame_Counter_validOut;
  logic [8:0] Frame_Counter_symNum;  /* ufix9 */
  logic Resource_Element_Type_isData;
  logic Resource_Element_Type_isRef;


  rxsl_Frame_Counter u_Frame_Counter (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .validIn(validIn),
                                 .frameStart(Frame_Counter_frameStart),
                                 .validOut(Frame_Counter_validOut),
                                 .symNum(Frame_Counter_symNum)  /* ufix9 */
                                 );

  rxsl_Resource_Element_Type u_Resource_Element_Type (.validIn(Frame_Counter_validOut),
                                                 .symNum(Frame_Counter_symNum),  /* ufix9 */
                                                 .isData(Resource_Element_Type_isData),
                                                 .isRef(Resource_Element_Type_isRef)
                                                 );

  assign isData = Resource_Element_Type_isData;

  assign isRef = Resource_Element_Type_isRef;

  assign frameStart = Frame_Counter_frameStart;

endmodule  // rxsl_Grid_Structure

