// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Interpolation_Control.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Interpolation_Control
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Channel Estimation/Channel Estimator/Interpolation 
// Contro
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Interpolation_Control
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic refValid,
             input logic readyIn,
             output logic wrEn,
             output logic [7:0] wrAddr  /* uint8 */,
             output logic bankWrAddr  /* ufix1 */,
             output logic [7:0] rdAddr  /* uint8 */,
             output logic bankRdAddr  /* ufix1 */,
             output logic hEstValid,
             output logic [1:0] interpFactor  /* ufix2 */,
             output logic replicateSym);


  logic Delay10_out1;
  logic HestValid_1;


  always_ff @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= refValid;
        end
      end
    end

  channelEstimationControl u_channelEstimationControl (.clk(clk),
                                                       .reset(reset),
                                                       .enb(enb),
                                                       .refValidIn(Delay10_out1),
                                                       .readyIn(readyIn),
                                                       .wrAddr(wrAddr),  /* uint8 */
                                                       .wrEn(wrEn),
                                                       .bankWrAddr(bankWrAddr),  /* ufix1 */
                                                       .rdAddr(rdAddr),  /* uint8 */
                                                       .bankRdAddr(bankRdAddr),  /* ufix1 */
                                                       .HestValid(HestValid_1),
                                                       .interpFactor(interpFactor),  /* ufix2 */
                                                       .replicateSym(replicateSym)
                                                       );

  assign hEstValid = HestValid_1;

endmodule  // Interpolation_Control

