// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Magnitude_Squared_Thresh.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Magnitude_Squared_Thresh
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Thresholded Correlator/Threshold/Magnitude 
// Squared Thres
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Magnitude_Squared_Thresh
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [17:0] dataIn_re  /* sfix18_En17 */,
             input logic signed [17:0] dataIn_im  /* sfix18_En17 */,
             input logic validIn,
             output logic [35:0] dataOut  /* ufix36_En34 */,
             output logic validOut);


  logic signed [17:0] Delay6_out1;  /* sfix18_En17 */
  logic signed [35:0] Product4_out1;  /* sfix36_En34 */
  logic signed [17:0] Delay3_out1;  /* sfix18_En17 */
  logic signed [35:0] Product1_out1;  /* sfix36_En34 */
  logic signed [35:0] Delay2_out1;  /* sfix36_En34 */
  logic [35:0] Data_Type_Conversion_out1;  /* ufix36_En34 */
  logic signed [35:0] Delay1_out1;  /* sfix36_En34 */
  logic [35:0] Data_Type_Conversion1_out1;  /* ufix36_En34 */
  logic [35:0] Add_out1;  /* ufix36_En34 */
  logic [35:0] Delay4_out1;  /* ufix36_En34 */
  logic Delay5_out1;
  logic Delay7_out1;
  logic Delay8_out1;


  always_ff @(posedge clk)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= dataIn_re;
        end
      end
    end

  assign Product4_out1 = Delay6_out1 * Delay6_out1;

  always_ff @(posedge clk)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= dataIn_im;
        end
      end
    end

  assign Product1_out1 = Delay3_out1 * Delay3_out1;

  always_ff @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= Product4_out1;
        end
      end
    end

  assign Data_Type_Conversion_out1 = Delay2_out1;

  always_ff @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 36'sh000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Product1_out1;
        end
      end
    end

  assign Data_Type_Conversion1_out1 = Delay1_out1;

  assign Add_out1 = Data_Type_Conversion_out1 + Data_Type_Conversion1_out1;

  always_ff @(posedge clk)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 36'h000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= Add_out1;
        end
      end
    end

  assign dataOut = Delay4_out1;

  always_ff @(posedge clk)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= validIn;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Delay5_out1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= Delay7_out1;
        end
      end
    end

  assign validOut = Delay8_out1;

endmodule  // Magnitude_Squared_Thresh

