// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/OFDM_Receiver.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.6e-08
// Target subsystem base rate: 1.6e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1.6e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// rxPayload_0                   ce_out        1.6e-08
// rxPayload_1                   ce_out        1.6e-08
// rxPayloadValid                ce_out        1.6e-08
// peakInfo_correlation          ce_out        1.6e-08
// peakInfo_threshold            ce_out        1.6e-08
// peakInfo_tOffset              ce_out        1.6e-08
// peakInfo_fOffset              ce_out        1.6e-08
// peakInfoValid                 ce_out        1.6e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: OFDM_Receiver
// Source Path: introOFDMReceiver/OFDM Receiver
// Hierarchy Level: 0
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module OFDM_Receiver
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input logic signed [15:0] rxData_re  /* sfix16_En15 */,
             input logic signed [15:0] rxData_im  /* sfix16_En15 */,
             input logic rxValid,
             input logic start,
             input logic freqCorrectionEn,
             output logic ce_out,
             output logic rxPayload_0  /* boolean */,
             output logic rxPayload_1  /* boolean */,
             output logic rxPayloadValid,
             output logic [31:0] peakInfo_correlation  /* ufix32_En24 */,
             output logic [31:0] peakInfo_threshold  /* ufix32_En24 */,
             output logic [13:0] peakInfo_tOffset  /* ufix14 */,
             output logic signed [31:0] peakInfo_fOffset  /* int32 */,
             output logic peakInfoValid);


  logic enb;
  logic signed [15:0] Input_Scaling_dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] Input_Scaling_dataOut_im;  /* sfix16_En15 */
  logic Input_Scaling_validOut;
  logic signed [15:0] Synchronization_dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] Synchronization_dataOut_im;  /* sfix16_En15 */
  logic Synchronization_validOut;
  logic signed [1:0] Synchronization_tDelta;  /* sfix2 */
  logic Synchronization_strobe;
  logic [31:0] Synchronization_peakInfo_correlation;  /* ufix32_En24 */
  logic [31:0] Synchronization_peakInfo_threshold;  /* ufix32_En24 */
  logic [13:0] Synchronization_peakInfo_tOffset;  /* ufix14 */
  logic signed [31:0] Synchronization_peakInfo_fOffset;  /* int32 */
  logic Synchronization_peakInfoValid;
  logic signed [15:0] OFDM_Demodulation_dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] OFDM_Demodulation_dataOut_im;  /* sfix16_En15 */
  logic OFDM_Demodulation_validOut;
  logic signed [31:0] Channel_Estimation_and_Equalization_eqData_re;  /* sfix32_En15 */
  logic signed [31:0] Channel_Estimation_and_Equalization_eqData_im;  /* sfix32_En15 */
  logic Channel_Estimation_and_Equalization_validOut;
  logic QPSK_Demodulation_dataOut_0;
  logic QPSK_Demodulation_dataOut_1;
  logic QPSK_Demodulation_validOut;
  logic [34:0] delayMatch_reg;  /* ufix1 [35] */
  logic QPSK_Demodulation_validOut_1;
  rxsl_vector_of_unsigned_logic_32 alpha_reg [0:34];  /* ufix32 [35] */
  logic [31:0] Synchronization_peakInfo_correlation_1;  /* ufix32_En24 */
  rxsl_vector_of_unsigned_logic_32 alpha_reg_1 [0:34];  /* ufix32 [35] */
  logic [31:0] Synchronization_peakInfo_threshold_1;  /* ufix32_En24 */
  rxsl_vector_of_unsigned_logic_14 alpha_reg_2 [0:34];  /* ufix14 [35] */
  logic [13:0] Synchronization_peakInfo_tOffset_1;  /* ufix14 */
  rxsl_vector_of_signed_logic_32 alpha_reg_3 [0:34];  /* sfix32 [35] */
  logic signed [31:0] Synchronization_peakInfo_fOffset_1;  /* int32 */
  logic [34:0] delayMatch2_reg;  /* ufix1 [35] */
  logic Synchronization_peakInfoValid_1;


  Input_Scaling u_Input_Scaling (.clk(clk),
                                 .reset(reset),
                                 .enb(clk_enable),
                                 .dataIn_re(rxData_re),  /* sfix16_En15 */
                                 .dataIn_im(rxData_im),  /* sfix16_En15 */
                                 .validIn(rxValid),
                                 .dataOut_re(Input_Scaling_dataOut_re),  /* sfix16_En15 */
                                 .dataOut_im(Input_Scaling_dataOut_im),  /* sfix16_En15 */
                                 .validOut(Input_Scaling_validOut)
                                 );

  Synchronization u_Synchronization (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .dataIn_re(Input_Scaling_dataOut_re),  /* sfix16_En15 */
                                     .dataIn_im(Input_Scaling_dataOut_im),  /* sfix16_En15 */
                                     .validIn(Input_Scaling_validOut),
                                     .start(start),
                                     .freqCorrectionEn(freqCorrectionEn),
                                     .dataOut_re(Synchronization_dataOut_re),  /* sfix16_En15 */
                                     .dataOut_im(Synchronization_dataOut_im),  /* sfix16_En15 */
                                     .validOut(Synchronization_validOut),
                                     .tDelta(Synchronization_tDelta),  /* sfix2 */
                                     .strobe(Synchronization_strobe),
                                     .peakInfo_correlation(Synchronization_peakInfo_correlation),  /* ufix32_En24 */
                                     .peakInfo_threshold(Synchronization_peakInfo_threshold),  /* ufix32_En24 */
                                     .peakInfo_tOffset(Synchronization_peakInfo_tOffset),  /* ufix14 */
                                     .peakInfo_fOffset(Synchronization_peakInfo_fOffset),  /* int32 */
                                     .peakInfoValid(Synchronization_peakInfoValid)
                                     );

  OFDM_Demodulation u_OFDM_Demodulation (.clk(clk),
                                         .reset(reset),
                                         .enb(clk_enable),
                                         .dataIn_re(Synchronization_dataOut_re),  /* sfix16_En15 */
                                         .dataIn_im(Synchronization_dataOut_im),  /* sfix16_En15 */
                                         .validIn(Synchronization_validOut),
                                         .tDelta(Synchronization_tDelta),  /* sfix2 */
                                         .strobe(Synchronization_strobe),
                                         .dataOut_re(OFDM_Demodulation_dataOut_re),  /* sfix16_En15 */
                                         .dataOut_im(OFDM_Demodulation_dataOut_im),  /* sfix16_En15 */
                                         .validOut(OFDM_Demodulation_validOut)
                                         );

  Channel_Estimation_and_Equalization u_Channel_Estimation_and_Equalization (.clk(clk),
                                                                             .reset(reset),
                                                                             .enb(clk_enable),
                                                                             .dataIn_re(OFDM_Demodulation_dataOut_re),  /* sfix16_En15 */
                                                                             .dataIn_im(OFDM_Demodulation_dataOut_im),  /* sfix16_En15 */
                                                                             .validIn(OFDM_Demodulation_validOut),
                                                                             .eqData_re(Channel_Estimation_and_Equalization_eqData_re),  /* sfix32_En15 */
                                                                             .eqData_im(Channel_Estimation_and_Equalization_eqData_im),  /* sfix32_En15 */
                                                                             .validOut(Channel_Estimation_and_Equalization_validOut)
                                                                             );

  QPSK_Demodulation u_QPSK_Demodulation (.clk(clk),
                                         .reset(reset),
                                         .enb(clk_enable),
                                         .eqData_re(Channel_Estimation_and_Equalization_eqData_re),  /* sfix32_En15 */
                                         .eqData_im(Channel_Estimation_and_Equalization_eqData_im),  /* sfix32_En15 */
                                         .validIn(Channel_Estimation_and_Equalization_validOut),
                                         .dataOut_0(QPSK_Demodulation_dataOut_0),  /* boolean */
                                         .dataOut_1(QPSK_Demodulation_dataOut_1),  /* boolean */
                                         .validOut(QPSK_Demodulation_validOut)
                                         );

  assign rxPayload_0 = QPSK_Demodulation_dataOut_0;

  assign rxPayload_1 = QPSK_Demodulation_dataOut_1;

  assign enb = clk_enable;

  always_ff @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= QPSK_Demodulation_validOut;
          delayMatch_reg[32'sd34:32'sd1] <= delayMatch_reg[32'sd33:32'sd0];
        end
      end
    end

  assign QPSK_Demodulation_validOut_1 = delayMatch_reg[34];

  assign rxPayloadValid = QPSK_Demodulation_validOut_1;

  always_ff @(posedge clk)
    begin : c_process
      if (reset == 1'b1) begin
        alpha_reg <= '{default :32'b00000000000000000000000000000000};
      end
      else begin
        if (enb) begin
          alpha_reg[0] <= Synchronization_peakInfo_correlation;
          alpha_reg[32'sd1:32'sd34] <= alpha_reg[32'sd0:32'sd33];
        end
      end
    end

  assign Synchronization_peakInfo_correlation_1 = alpha_reg[34];

  assign peakInfo_correlation = Synchronization_peakInfo_correlation_1;

  always_ff @(posedge clk)
    begin : c_1_process
      if (reset == 1'b1) begin
        alpha_reg_1 <= '{default :32'b00000000000000000000000000000000};
      end
      else begin
        if (enb) begin
          alpha_reg_1[0] <= Synchronization_peakInfo_threshold;
          alpha_reg_1[32'sd1:32'sd34] <= alpha_reg_1[32'sd0:32'sd33];
        end
      end
    end

  assign Synchronization_peakInfo_threshold_1 = alpha_reg_1[34];

  assign peakInfo_threshold = Synchronization_peakInfo_threshold_1;

  always_ff @(posedge clk)
    begin : c_2_process
      if (reset == 1'b1) begin
        alpha_reg_2 <= '{default :14'b00000000000000};
      end
      else begin
        if (enb) begin
          alpha_reg_2[0] <= Synchronization_peakInfo_tOffset;
          alpha_reg_2[32'sd1:32'sd34] <= alpha_reg_2[32'sd0:32'sd33];
        end
      end
    end

  assign Synchronization_peakInfo_tOffset_1 = alpha_reg_2[34];

  assign peakInfo_tOffset = Synchronization_peakInfo_tOffset_1;

  always_ff @(posedge clk)
    begin : c_3_process
      if (reset == 1'b1) begin
        alpha_reg_3 <= '{default :32'sb00000000000000000000000000000000};
      end
      else begin
        if (enb) begin
          alpha_reg_3[0] <= Synchronization_peakInfo_fOffset;
          alpha_reg_3[32'sd1:32'sd34] <= alpha_reg_3[32'sd0:32'sd33];
        end
      end
    end

  assign Synchronization_peakInfo_fOffset_1 = alpha_reg_3[34];

  assign peakInfo_fOffset = Synchronization_peakInfo_fOffset_1;

  always_ff @(posedge clk)
    begin : delayMatch2_process
      if (reset == 1'b1) begin
        delayMatch2_reg <= '{default :1'b0};
      end
      else begin
        if (enb) begin
          delayMatch2_reg[0] <= Synchronization_peakInfoValid;
          delayMatch2_reg[32'sd34:32'sd1] <= delayMatch2_reg[32'sd33:32'sd0];
        end
      end
    end

  assign Synchronization_peakInfoValid_1 = delayMatch2_reg[34];

  assign peakInfoValid = Synchronization_peakInfoValid_1;

  assign ce_out = clk_enable;

endmodule  // OFDM_Receiver

