// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Peak_Diagnostics.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Peak_Diagnostics
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Peak Diagnostics
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Peak_Diagnostics
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] correlation  /* ufix32_En24 */,
             input logic [31:0] threshold  /* ufix32_En24 */,
             input logic validIn,
             input logic signed [31:0] fOffset  /* int32 */,
             input logic peakStrobe,
             output logic [31:0] peakInfo_correlation  /* ufix32_En24 */,
             output logic [31:0] peakInfo_threshold  /* ufix32_En24 */,
             output logic [13:0] peakInfo_tOffset  /* ufix14 */,
             output logic signed [31:0] peakInfo_fOffset  /* int32 */,
             output logic validOut);


  logic [31:0] correlation_1;  /* ufix32_En24 */
  logic [31:0] threshold_1;  /* ufix32_En24 */
  logic [13:0] count_step;  /* ufix14 */
  logic [13:0] count_from;  /* ufix14 */
  logic [13:0] HDL_Counter1_out1;  /* ufix14 */
  logic [13:0] count;  /* ufix14 */
  logic need_to_wrap;
  logic [13:0] count_value;  /* ufix14 */
  logic [13:0] count_1;  /* ufix14 */
  logic [13:0] tOffset;  /* ufix14 */
  logic signed [31:0] fOffset_1;  /* int32 */
  logic Delay_out1;


  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        correlation_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && peakStrobe) begin
          correlation_1 <= correlation;
        end
      end
    end

  assign peakInfo_correlation = correlation_1;

  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous1_process
      if (reset == 1'b1) begin
        threshold_1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && peakStrobe) begin
          threshold_1 <= threshold;
        end
      end
    end

  assign peakInfo_threshold = threshold_1;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 8959
  assign count_step = 14'b00000000000001;

  assign count_from = 14'b00000000000000;

  assign count = HDL_Counter1_out1 + count_step;

  assign need_to_wrap = HDL_Counter1_out1 == 14'b10001011111111;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (validIn == 1'b0 ? HDL_Counter1_out1 :
              count_value);

  always_ff @(posedge clk)
    begin : HDL_Counter1_process
      if (reset == 1'b1) begin
        HDL_Counter1_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous3_process
      if (reset == 1'b1) begin
        tOffset <= 14'b00000000000000;
      end
      else begin
        if (enb && peakStrobe) begin
          tOffset <= HDL_Counter1_out1;
        end
      end
    end

  assign peakInfo_tOffset = tOffset;

  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous2_process
      if (reset == 1'b1) begin
        fOffset_1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb && peakStrobe) begin
          fOffset_1 <= fOffset;
        end
      end
    end

  assign peakInfo_fOffset = fOffset_1;

  always_ff @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= peakStrobe;
        end
      end
    end

  assign validOut = Delay_out1;

endmodule  // Peak_Diagnostics

