// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_RADIX22FFT_SDF1_5.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: rxsl_RADIX22FFT_SDF1_5
// Source Path: introOFDMReceiver/OFDM Receiver/OFDM Demodulation/OFDM Demodulator/dsphdl.FFT/rxsl_RADIX22FFT_SDF1_5
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_RADIX22FFT_SDF1_5
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [19:0] din_5_1_re_dly  /* sfix20_En15 */,
             input logic signed [19:0] din_5_1_im_dly  /* sfix20_En15 */,
             input logic din_5_vld_dly,
             input logic [2:0] rd_5_Addr  /* ufix3 */,
             input logic rd_5_Enb,
             input logic signed [15:0] twdl_5_1_re  /* sfix16_En14 */,
             input logic signed [15:0] twdl_5_1_im  /* sfix16_En14 */,
             input logic proc_5_enb,
             output logic signed [20:0] dout_5_1_re  /* sfix21_En15 */,
             output logic signed [20:0] dout_5_1_im  /* sfix21_En15 */,
             output logic dout_5_1_vld,
             output logic dinXTwdl_5_1_vld);


  logic signed [20:0] din_re;  /* sfix21_En15 */
  logic signed [20:0] din_im;  /* sfix21_En15 */
  logic signed [20:0] dinXTwdl_re;  /* sfix21_En15 */
  logic signed [20:0] dinXTwdl_im;  /* sfix21_En15 */
  logic x_vld;
  logic signed [20:0] wrData_im;  /* sfix21_En15 */
  logic [2:0] wrAddr;  /* ufix3 */
  logic wrEnb;
  logic signed [20:0] x_im;  /* sfix21_En15 */
  logic signed [20:0] wrData_re;  /* sfix21_En15 */
  logic signed [20:0] x_re;  /* sfix21_En15 */
  logic signed [21:0] Radix22ButterflyG1_btf1_re_reg;  /* sfix22 */
  logic signed [21:0] Radix22ButterflyG1_btf1_im_reg;  /* sfix22 */
  logic signed [21:0] Radix22ButterflyG1_btf2_re_reg;  /* sfix22 */
  logic signed [21:0] Radix22ButterflyG1_btf2_im_reg;  /* sfix22 */
  logic signed [20:0] Radix22ButterflyG1_x_re_dly1;  /* sfix21 */
  logic signed [20:0] Radix22ButterflyG1_x_im_dly1;  /* sfix21 */
  logic Radix22ButterflyG1_x_vld_dly1;
  logic signed [20:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  /* sfix21 */
  logic signed [20:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  /* sfix21 */
  logic signed [20:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  /* sfix21 */
  logic signed [20:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  /* sfix21 */
  logic Radix22ButterflyG1_dinXtwdl_vld_dly1;
  logic Radix22ButterflyG1_dinXtwdl_vld_dly2;
  logic signed [21:0] Radix22ButterflyG1_btf1_re_reg_next;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_btf1_im_reg_next;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_btf2_re_reg_next;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_btf2_im_reg_next;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_add_cast;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_add_cast_1;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_sub_cast;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_sub_cast_1;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_add_cast_2;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_add_cast_3;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_sub_cast_2;  /* sfix22_En15 */
  logic signed [21:0] Radix22ButterflyG1_sub_cast_3;  /* sfix22_En15 */
  logic signed [20:0] xf_re;  /* sfix21_En15 */
  logic signed [20:0] xf_im;  /* sfix21_En15 */
  logic xf_vld;
  logic signed [20:0] dinXTwdlf_re;  /* sfix21_En15 */
  logic signed [20:0] dinXTwdlf_im;  /* sfix21_En15 */
  logic dinxTwdlf_vld;
  logic signed [20:0] btf1_re;  /* sfix21_En15 */
  logic signed [20:0] btf1_im;  /* sfix21_En15 */
  logic signed [20:0] btf2_re;  /* sfix21_En15 */
  logic signed [20:0] btf2_im;  /* sfix21_En15 */
  logic btf_vld;


  assign din_re = {din_5_1_re_dly[19], din_5_1_re_dly};

  assign din_im = {din_5_1_im_dly[19], din_5_1_im_dly};

  rxsl_Complex4Multiply_block u_MUL4 (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .din_re(din_re),  /* sfix21_En15 */
                                 .din_im(din_im),  /* sfix21_En15 */
                                 .din_5_vld_dly(din_5_vld_dly),
                                 .twdl_5_1_re(twdl_5_1_re),  /* sfix16_En14 */
                                 .twdl_5_1_im(twdl_5_1_im),  /* sfix16_En14 */
                                 .dinXTwdl_re(dinXTwdl_re),  /* sfix21_En15 */
                                 .dinXTwdl_im(dinXTwdl_im),  /* sfix21_En15 */
                                 .dinXTwdl_5_1_vld(dinXTwdl_5_1_vld)
                                 );

  always_ff @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_5_Enb;
        end
      end
    end

  rxsl_SimpleDualPortRAM_generic_block #(.AddrWidth(3),
                                    .DataWidth(21)
                                    )
                                  u_dataMEM_im_0_5 (.clk(clk),
                                                    .enb(enb),
                                                    .wr_din(wrData_im),
                                                    .wr_addr(wrAddr),
                                                    .wr_en(wrEnb),
                                                    .rd_addr(rd_5_Addr),
                                                    .dout(x_im)
                                                    );

  rxsl_SimpleDualPortRAM_generic_block #(.AddrWidth(3),
                                    .DataWidth(21)
                                    )
                                  u_dataMEM_re_0_5 (.clk(clk),
                                                    .enb(enb),
                                                    .wr_din(wrData_re),
                                                    .wr_addr(wrAddr),
                                                    .wr_en(wrEnb),
                                                    .rd_addr(rd_5_Addr),
                                                    .dout(x_re)
                                                    );

  // Radix22ButterflyG1
  always_ff @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 22'sb0000000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 21'sb000000000000000000000;
        xf_im <= 21'sb000000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 21'sb000000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_5_enb && dinXTwdl_5_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_5_enb) && dinXTwdl_5_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[20], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[20], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[20], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[20], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[20], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[20], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[20], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[20], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[20:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[20:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[20:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[20:0];

  rxsl_SDFCommutator5 u_SDFCOMMUTATOR_5 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_5_vld_dly(din_5_vld_dly),
                                    .xf_re(xf_re),  /* sfix21_En15 */
                                    .xf_im(xf_im),  /* sfix21_En15 */
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  /* sfix21_En15 */
                                    .dinXTwdlf_im(dinXTwdlf_im),  /* sfix21_En15 */
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  /* sfix21_En15 */
                                    .btf1_im(btf1_im),  /* sfix21_En15 */
                                    .btf2_re(btf2_re),  /* sfix21_En15 */
                                    .btf2_im(btf2_im),  /* sfix21_En15 */
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  /* sfix21_En15 */
                                    .wrData_im(wrData_im),  /* sfix21_En15 */
                                    .wrAddr(wrAddr),  /* ufix3 */
                                    .wrEnb(wrEnb),
                                    .dout_5_1_re(dout_5_1_re),  /* sfix21_En15 */
                                    .dout_5_1_im(dout_5_1_im),  /* sfix21_En15 */
                                    .dout_5_1_vld(dout_5_1_vld)
                                    );

endmodule  // rxsl_RADIX22FFT_SDF1_5

