// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_RADIX22FFT_SDF1_3.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: rxsl_RADIX22FFT_SDF1_3
// Source Path: introOFDMReceiver/OFDM Receiver/OFDM Demodulation/OFDM Demodulator/dsphdl.FFT/rxsl_RADIX22FFT_SDF1_3
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_RADIX22FFT_SDF1_3
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [17:0] din_3_1_re_dly  /* sfix18_En15 */,
             input logic signed [17:0] din_3_1_im_dly  /* sfix18_En15 */,
             input logic din_3_vld_dly,
             input logic [4:0] rd_3_Addr  /* ufix5 */,
             input logic rd_3_Enb,
             input logic signed [15:0] twdl_3_1_re  /* sfix16_En14 */,
             input logic signed [15:0] twdl_3_1_im  /* sfix16_En14 */,
             input logic proc_3_enb,
             output logic signed [18:0] dout_3_1_re  /* sfix19_En15 */,
             output logic signed [18:0] dout_3_1_im  /* sfix19_En15 */,
             output logic dout_3_1_vld,
             output logic dinXTwdl_3_1_vld);


  logic signed [18:0] din_re;  /* sfix19_En15 */
  logic signed [18:0] din_im;  /* sfix19_En15 */
  logic signed [18:0] dinXTwdl_re;  /* sfix19_En15 */
  logic signed [18:0] dinXTwdl_im;  /* sfix19_En15 */
  logic x_vld;
  logic signed [18:0] wrData_im;  /* sfix19_En15 */
  logic [4:0] wrAddr;  /* ufix5 */
  logic wrEnb;
  logic signed [18:0] x_im;  /* sfix19_En15 */
  logic signed [18:0] wrData_re;  /* sfix19_En15 */
  logic signed [18:0] x_re;  /* sfix19_En15 */
  logic signed [19:0] Radix22ButterflyG1_btf1_re_reg;  /* sfix20 */
  logic signed [19:0] Radix22ButterflyG1_btf1_im_reg;  /* sfix20 */
  logic signed [19:0] Radix22ButterflyG1_btf2_re_reg;  /* sfix20 */
  logic signed [19:0] Radix22ButterflyG1_btf2_im_reg;  /* sfix20 */
  logic signed [18:0] Radix22ButterflyG1_x_re_dly1;  /* sfix19 */
  logic signed [18:0] Radix22ButterflyG1_x_im_dly1;  /* sfix19 */
  logic Radix22ButterflyG1_x_vld_dly1;
  logic signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly1;  /* sfix19 */
  logic signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly1;  /* sfix19 */
  logic signed [18:0] Radix22ButterflyG1_dinXtwdl_re_dly2;  /* sfix19 */
  logic signed [18:0] Radix22ButterflyG1_dinXtwdl_im_dly2;  /* sfix19 */
  logic Radix22ButterflyG1_dinXtwdl_vld_dly1;
  logic Radix22ButterflyG1_dinXtwdl_vld_dly2;
  logic signed [19:0] Radix22ButterflyG1_btf1_re_reg_next;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_btf1_im_reg_next;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_btf2_re_reg_next;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_btf2_im_reg_next;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_add_cast;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_add_cast_1;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_sub_cast;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_sub_cast_1;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_add_cast_2;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_add_cast_3;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_sub_cast_2;  /* sfix20_En15 */
  logic signed [19:0] Radix22ButterflyG1_sub_cast_3;  /* sfix20_En15 */
  logic signed [18:0] xf_re;  /* sfix19_En15 */
  logic signed [18:0] xf_im;  /* sfix19_En15 */
  logic xf_vld;
  logic signed [18:0] dinXTwdlf_re;  /* sfix19_En15 */
  logic signed [18:0] dinXTwdlf_im;  /* sfix19_En15 */
  logic dinxTwdlf_vld;
  logic signed [18:0] btf1_re;  /* sfix19_En15 */
  logic signed [18:0] btf1_im;  /* sfix19_En15 */
  logic signed [18:0] btf2_re;  /* sfix19_En15 */
  logic signed [18:0] btf2_im;  /* sfix19_En15 */
  logic btf_vld;


  assign din_re = {din_3_1_re_dly[17], din_3_1_re_dly};

  assign din_im = {din_3_1_im_dly[17], din_3_1_im_dly};

  rxsl_Complex4Multiply u_MUL4 (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .din_re(din_re),  /* sfix19_En15 */
                           .din_im(din_im),  /* sfix19_En15 */
                           .din_3_vld_dly(din_3_vld_dly),
                           .twdl_3_1_re(twdl_3_1_re),  /* sfix16_En14 */
                           .twdl_3_1_im(twdl_3_1_im),  /* sfix16_En14 */
                           .dinXTwdl_re(dinXTwdl_re),  /* sfix19_En15 */
                           .dinXTwdl_im(dinXTwdl_im),  /* sfix19_En15 */
                           .dinXTwdl_3_1_vld(dinXTwdl_3_1_vld)
                           );

  always_ff @(posedge clk)
    begin : intdelay_process
      if (reset == 1'b1) begin
        x_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          x_vld <= rd_3_Enb;
        end
      end
    end

  rxsl_SimpleDualPortRAM_generic_block #(.AddrWidth(5),
                                    .DataWidth(19)
                                    )
                                  u_dataMEM_im_0_3 (.clk(clk),
                                                    .enb(enb),
                                                    .wr_din(wrData_im),
                                                    .wr_addr(wrAddr),
                                                    .wr_en(wrEnb),
                                                    .rd_addr(rd_3_Addr),
                                                    .dout(x_im)
                                                    );

  rxsl_SimpleDualPortRAM_generic_block #(.AddrWidth(5),
                                    .DataWidth(19)
                                    )
                                  u_dataMEM_re_0_3 (.clk(clk),
                                                    .enb(enb),
                                                    .wr_din(wrData_re),
                                                    .wr_addr(wrAddr),
                                                    .wr_en(wrEnb),
                                                    .rd_addr(rd_3_Addr),
                                                    .dout(x_re)
                                                    );

  // Radix22ButterflyG1
  always_ff @(posedge clk)
    begin : Radix22ButterflyG1_process
      if (reset == 1'b1) begin
        Radix22ButterflyG1_btf1_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf1_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_re_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_btf2_im_reg <= 20'sb00000000000000000000;
        Radix22ButterflyG1_x_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_x_vld_dly1 <= 1'b0;
        xf_re <= 19'sb0000000000000000000;
        xf_im <= 19'sb0000000000000000000;
        xf_vld <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_re_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly1 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_re_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_im_dly2 <= 19'sb0000000000000000000;
        Radix22ButterflyG1_dinXtwdl_vld_dly1 <= 1'b0;
        Radix22ButterflyG1_dinXtwdl_vld_dly2 <= 1'b0;
        btf_vld <= 1'b0;
      end
      else begin
        if (enb) begin
          Radix22ButterflyG1_btf1_re_reg <= Radix22ButterflyG1_btf1_re_reg_next;
          Radix22ButterflyG1_btf1_im_reg <= Radix22ButterflyG1_btf1_im_reg_next;
          Radix22ButterflyG1_btf2_re_reg <= Radix22ButterflyG1_btf2_re_reg_next;
          Radix22ButterflyG1_btf2_im_reg <= Radix22ButterflyG1_btf2_im_reg_next;
          xf_re <= Radix22ButterflyG1_x_re_dly1;
          xf_im <= Radix22ButterflyG1_x_im_dly1;
          xf_vld <= Radix22ButterflyG1_x_vld_dly1;
          btf_vld <= Radix22ButterflyG1_dinXtwdl_vld_dly2;
          Radix22ButterflyG1_dinXtwdl_vld_dly2 <= Radix22ButterflyG1_dinXtwdl_vld_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly2 <= Radix22ButterflyG1_dinXtwdl_re_dly1;
          Radix22ButterflyG1_dinXtwdl_im_dly2 <= Radix22ButterflyG1_dinXtwdl_im_dly1;
          Radix22ButterflyG1_dinXtwdl_re_dly1 <= dinXTwdl_re;
          Radix22ButterflyG1_dinXtwdl_im_dly1 <= dinXTwdl_im;
          Radix22ButterflyG1_x_re_dly1 <= x_re;
          Radix22ButterflyG1_x_im_dly1 <= x_im;
          Radix22ButterflyG1_x_vld_dly1 <= x_vld;
          Radix22ButterflyG1_dinXtwdl_vld_dly1 <= proc_3_enb && dinXTwdl_3_1_vld;
        end
      end
    end

  assign dinxTwdlf_vld = ( ! proc_3_enb) && dinXTwdl_3_1_vld;
  assign Radix22ButterflyG1_add_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_add_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf1_re_reg_next = Radix22ButterflyG1_add_cast + Radix22ButterflyG1_add_cast_1;
  assign Radix22ButterflyG1_sub_cast = {Radix22ButterflyG1_x_re_dly1[18], Radix22ButterflyG1_x_re_dly1};
  assign Radix22ButterflyG1_sub_cast_1 = {Radix22ButterflyG1_dinXtwdl_re_dly2[18], Radix22ButterflyG1_dinXtwdl_re_dly2};
  assign Radix22ButterflyG1_btf2_re_reg_next = Radix22ButterflyG1_sub_cast - Radix22ButterflyG1_sub_cast_1;
  assign Radix22ButterflyG1_add_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_add_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf1_im_reg_next = Radix22ButterflyG1_add_cast_2 + Radix22ButterflyG1_add_cast_3;
  assign Radix22ButterflyG1_sub_cast_2 = {Radix22ButterflyG1_x_im_dly1[18], Radix22ButterflyG1_x_im_dly1};
  assign Radix22ButterflyG1_sub_cast_3 = {Radix22ButterflyG1_dinXtwdl_im_dly2[18], Radix22ButterflyG1_dinXtwdl_im_dly2};
  assign Radix22ButterflyG1_btf2_im_reg_next = Radix22ButterflyG1_sub_cast_2 - Radix22ButterflyG1_sub_cast_3;
  assign dinXTwdlf_re = dinXTwdl_re;
  assign dinXTwdlf_im = dinXTwdl_im;
  assign btf1_re = Radix22ButterflyG1_btf1_re_reg[18:0];
  assign btf1_im = Radix22ButterflyG1_btf1_im_reg[18:0];
  assign btf2_re = Radix22ButterflyG1_btf2_re_reg[18:0];
  assign btf2_im = Radix22ButterflyG1_btf2_im_reg[18:0];

  rxsl_SDFCommutator3 u_SDFCOMMUTATOR_3 (.clk(clk),
                                    .reset(reset),
                                    .enb(enb),
                                    .din_3_vld_dly(din_3_vld_dly),
                                    .xf_re(xf_re),  /* sfix19_En15 */
                                    .xf_im(xf_im),  /* sfix19_En15 */
                                    .xf_vld(xf_vld),
                                    .dinXTwdlf_re(dinXTwdlf_re),  /* sfix19_En15 */
                                    .dinXTwdlf_im(dinXTwdlf_im),  /* sfix19_En15 */
                                    .dinxTwdlf_vld(dinxTwdlf_vld),
                                    .btf1_re(btf1_re),  /* sfix19_En15 */
                                    .btf1_im(btf1_im),  /* sfix19_En15 */
                                    .btf2_re(btf2_re),  /* sfix19_En15 */
                                    .btf2_im(btf2_im),  /* sfix19_En15 */
                                    .btf_vld(btf_vld),
                                    .wrData_re(wrData_re),  /* sfix19_En15 */
                                    .wrData_im(wrData_im),  /* sfix19_En15 */
                                    .wrAddr(wrAddr),  /* ufix5 */
                                    .wrEnb(wrEnb),
                                    .dout_3_1_re(dout_3_1_re),  /* sfix19_En15 */
                                    .dout_3_1_im(dout_3_1_im),  /* sfix19_En15 */
                                    .dout_3_1_vld(dout_3_1_vld)
                                    );

endmodule  // rxsl_RADIX22FFT_SDF1_3

