// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/SamplesRepetition.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: SamplesRepetition
// Source Path: 
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module SamplesRepetition
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] varargin_1_re  /* sfix16_En15 */,
             input logic signed [15:0] varargin_1_im  /* sfix16_En15 */,
             input logic varargin_2,
             input logic [8:0] varargin_3  /* ufix9 */,
             input logic [8:0] varargin_4  /* ufix9 */,
             input logic [8:0] varargin_5  /* ufix9 */,
             output logic signed [15:0] varargout_1_re  /* sfix16_En15 */,
             output logic signed [15:0] varargout_1_im  /* sfix16_En15 */,
             output logic varargout_2,
             output logic [8:0] varargout_3  /* ufix9 */,
             output logic [8:0] varargout_4  /* ufix9 */,
             output logic [8:0] varargout_5  /* ufix9 */);


  logic obj_SamplesRepetitionObj_resetSig;
  logic obj_SamplesRepetitionObj_resetSig_1;
  logic tmp;
  logic obj_SamplesRepetitionObj_validInReg;
  logic tmp_1;
  logic obj_SamplesRepetitionObj_validInReg_1;
  logic [8:0] obj_SamplesRepetitionObj_currFFTLength;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLenReg;  /* ufix9 */
  logic [8:0] tmp_2;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLenReg_1;  /* ufix9 */
  logic [8:0] tmp_3;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_inCount;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_inCount_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_inCount_2;  /* ufix9 */
  logic [8:0] tmp_4;  /* ufix9 */
  logic [8:0] tmp_5;  /* ufix9 */
  logic [8:0] tmp_6;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_currFFTLength_1;  /* ufix9 */
  logic s;
  logic a0;
  logic [8:0] tmp_7;  /* ufix9 */
  logic [8:0] tmp_8;  /* ufix9 */
  logic [8:0] tmp_9;  /* ufix9 */
  logic a0_1;
  logic obj_SamplesRepetitionObj_flag;
  logic a0_2;
  logic obj_SamplesRepetitionObj_flag_1;
  logic obj_SamplesRepetitionObj_flag_2;
  logic obj_SamplesRepetitionObj_flag_3;
  logic tmp_10;
  logic tmp_11;
  logic tmp_12;
  logic tmp_13;
  logic tmp_14;
  logic tmp_15;
  logic obj_SamplesRepetitionObj_sym2Done;
  logic obj_SamplesRepetitionObj_sym2Done_1;
  logic obj_SamplesRepetitionObj_sym2Done_2;
  logic obj_SamplesRepetitionObj_startRead2;
  logic obj_SamplesRepetitionObj_startRead2_1;
  logic obj_SamplesRepetitionObj_startRead2_2;
  logic [8:0] obj_SamplesRepetitionObj_outCount;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_outCount_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_outCount_2;  /* ufix9 */
  logic obj_SamplesRepetitionObj_startRead2_3;
  logic obj_SamplesRepetitionObj_sym1Done;
  logic obj_SamplesRepetitionObj_sym1Done_1;
  logic obj_SamplesRepetitionObj_sym1Done_2;
  logic obj_SamplesRepetitionObj_startRead1;
  logic obj_SamplesRepetitionObj_startRead1_1;
  logic obj_SamplesRepetitionObj_startRead1_2;
  logic obj_SamplesRepetitionObj_startRead1_3;
  logic tmp_16;
  logic tmp_17;
  logic s_1;
  logic obj_SamplesRepetitionObj_startRead1_4;
  logic tmp_18;
  logic s_2;
  logic tmp_19;
  logic tmp_20;
  logic tmp_21;
  logic [8:0] obj_SamplesRepetitionObj_outCount_3;  /* ufix9 */
  logic [8:0] tmp_22;  /* ufix9 */
  logic [9:0] p391_1;  /* ufix10 */
  logic [8:0] tmp_23;  /* ufix9 */
  logic [8:0] tmp_24;  /* ufix9 */
  logic s_3;
  logic [8:0] tmp_25;  /* ufix9 */
  logic s_4;
  logic [8:0] tmp_26;  /* ufix9 */
  logic [8:0] tmp_27;  /* ufix9 */
  logic [8:0] tmp_28;  /* ufix9 */
  logic [9:0] p381_1;  /* ufix10 */
  logic obj_SamplesRepetitionObj_startRead2_4;
  logic tmp_29;
  logic tmp_30;
  logic tmp_31;
  logic tmp_32;
  logic tmp_33;
  logic tmp_34;
  logic tmp_35;
  logic obj_SamplesRepetitionObj_sym2Done_3;
  logic tmp_36;
  logic tmp_37;
  logic tmp_38;
  logic tmp_39;
  logic tmp_40;
  logic obj_SamplesRepetitionObj_sym1Done_3;
  logic tmp_41;
  logic tmp_42;
  logic tmp_43;
  logic tmp_44;
  logic tmp_45;
  logic obj_SamplesRepetitionObj_strtRd1Reg;
  logic tmp_46;
  logic obj_SamplesRepetitionObj_strtRd1Reg_1;
  logic obj_SamplesRepetitionObj_strtRd1Reg1;
  logic tmp_47;
  logic obj_SamplesRepetitionObj_strtRd1Reg1_1;
  logic obj_SamplesRepetitionObj_strtRd2Reg;
  logic tmp_48;
  logic obj_SamplesRepetitionObj_strtRd2Reg_1;
  logic obj_SamplesRepetitionObj_strtRd2Reg1;
  logic tmp_49;
  logic obj_SamplesRepetitionObj_strtRd2Reg1_1;
  logic s_5;
  logic s_6;
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_re;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_im;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg_re;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg_im;  /* sfix16_En15 */
  logic signed [15:0] tmp_re;  /* sfix16_En15 */
  logic signed [15:0] tmp_im;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg_re_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg_im_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg1_re;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg1_im;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_1;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg1_re_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataInReg1_im_1;  /* sfix16_En15 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr2;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr2_1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr2_2;  /* ufix8 */
  logic [7:0] tmp_50;  /* ufix8 */
  logic [7:0] tmp_51;  /* ufix8 */
  logic [7:0] tmp_52;  /* ufix8 */
  logic [7:0] tmp_53;  /* ufix8 */
  logic [7:0] tmp_54;  /* ufix8 */
  logic s_7;
  logic s_8;
  logic s_9;
  logic tmp_55;
  logic obj_SamplesRepetitionObj_wrEn2;
  logic tmp_56;
  logic obj_SamplesRepetitionObj_wrEn2_1;
  logic s_10;
  logic tmp_57;
  logic [8:0] obj_SamplesRepetitionObj_prevFFTLength;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_prevFFTLength_1;  /* ufix9 */
  logic [8:0] tmp_58;  /* ufix9 */
  logic [8:0] tmp_59;  /* ufix9 */
  logic [8:0] tmp_60;  /* ufix9 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr2;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr2_1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr2_2;  /* ufix8 */
  logic [7:0] tmp_61;  /* ufix8 */
  logic [7:0] tmp_62;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr2_3;  /* ufix8 */
  logic [7:0] tmp_63;  /* ufix8 */
  logic s_11;
  logic [8:0] p375_1;  /* ufix9 */
  logic [7:0] tmp_64;  /* ufix8 */
  logic [7:0] tmp_65;  /* ufix8 */
  logic [7:0] tmp_66;  /* ufix8 */
  logic [7:0] tmp_67;  /* ufix8 */
  logic signed [15:0] varargout_1_re_1;  /* sfix16_En15 */
  logic signed [15:0] varargout_1_im_1;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_2;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_2;  /* sfix16_En15 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr1_1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_wrAddr1_2;  /* ufix8 */
  logic [7:0] tmp_68;  /* ufix8 */
  logic [7:0] tmp_69;  /* ufix8 */
  logic [7:0] tmp_70;  /* ufix8 */
  logic [7:0] tmp_71;  /* ufix8 */
  logic [7:0] tmp_72;  /* ufix8 */
  logic s_12;
  logic s_13;
  logic s_14;
  logic tmp_73;
  logic obj_SamplesRepetitionObj_wrEn1;
  logic tmp_74;
  logic obj_SamplesRepetitionObj_wrEn1_1;
  logic [7:0] obj_SamplesRepetitionObj_rdAddr1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr1_1;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr1_2;  /* ufix8 */
  logic [7:0] tmp_75;  /* ufix8 */
  logic [7:0] tmp_76;  /* ufix8 */
  logic [7:0] obj_SamplesRepetitionObj_rdAddr1_3;  /* ufix8 */
  logic [7:0] tmp_77;  /* ufix8 */
  logic s_15;
  logic [8:0] p385_1;  /* ufix9 */
  logic [7:0] tmp_78;  /* ufix8 */
  logic [7:0] tmp_79;  /* ufix8 */
  logic [7:0] tmp_80;  /* ufix8 */
  logic signed [15:0] varargout_1_re_2;  /* sfix16_En15 */
  logic signed [15:0] varargout_1_im_2;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_3;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_3;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_re_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_im_1;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_4;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_4;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_re_2;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg_im_2;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg1_re;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg1_im;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_5;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_5;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg1_re_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOutReg1_im_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOut_im;  /* sfix16_En15 */
  logic signed [15:0] tmp_re_6;  /* sfix16_En15 */
  logic signed [15:0] tmp_im_6;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOut_re_1;  /* sfix16_En15 */
  logic signed [15:0] obj_SamplesRepetitionObj_dataOut_im_1;  /* sfix16_En15 */
  logic obj_SamplesRepetitionObj_validOutReg;
  logic obj_SamplesRepetitionObj_validOutReg_1;
  logic tmp_81;
  logic obj_SamplesRepetitionObj_validOutReg_2;
  logic tmp_82;
  logic obj_SamplesRepetitionObj_validOutReg_3;
  logic tmp_83;
  logic obj_SamplesRepetitionObj_validOutReg_4;
  logic obj_SamplesRepetitionObj_validOutReg1;
  logic tmp_84;
  logic obj_SamplesRepetitionObj_validOutReg1_1;
  logic obj_SamplesRepetitionObj_validOutReg2;
  logic tmp_85;
  logic obj_SamplesRepetitionObj_validOutReg2_1;
  logic obj_SamplesRepetitionObj_validOutReg3;
  logic tmp_86;
  logic obj_SamplesRepetitionObj_validOutReg3_1;
  logic obj_SamplesRepetitionObj_validOut;
  logic tmp_87;
  logic obj_SamplesRepetitionObj_validOut_1;
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg_1;  /* ufix9 */
  logic [8:0] tmp_88;  /* ufix9 */
  logic [8:0] tmp_89;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg1_1;  /* ufix9 */
  logic [8:0] tmp_90;  /* ufix9 */
  logic [8:0] tmp_91;  /* ufix9 */
  logic [8:0] tmp_92;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg2;  /* ufix9 */
  logic [8:0] tmp_93;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg2_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg3;  /* ufix9 */
  logic [8:0] tmp_94;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthReg3_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthRegOut;  /* ufix9 */
  logic [8:0] tmp_95;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_FFTLengthRegOut_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdReg;  /* ufix9 */
  logic [8:0] tmp_96;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdReg_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg_1;  /* ufix9 */
  logic [8:0] tmp_97;  /* ufix9 */
  logic [8:0] tmp_98;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg1_1;  /* ufix9 */
  logic [8:0] tmp_99;  /* ufix9 */
  logic [8:0] tmp_100;  /* ufix9 */
  logic [8:0] tmp_101;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg2;  /* ufix9 */
  logic [8:0] tmp_102;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg2_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg3;  /* ufix9 */
  logic [8:0] tmp_103;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubReg3_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubRegOut;  /* ufix9 */
  logic [8:0] tmp_104;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_LGaurdSubRegOut_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdReg;  /* ufix9 */
  logic [8:0] tmp_105;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdReg_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg_1;  /* ufix9 */
  logic [8:0] tmp_106;  /* ufix9 */
  logic [8:0] tmp_107;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg1_1;  /* ufix9 */
  logic [8:0] tmp_108;  /* ufix9 */
  logic [8:0] tmp_109;  /* ufix9 */
  logic [8:0] tmp_110;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg2;  /* ufix9 */
  logic [8:0] tmp_111;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg2_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg3;  /* ufix9 */
  logic [8:0] tmp_112;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubReg3_1;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubRegOut;  /* ufix9 */
  logic [8:0] tmp_113;  /* ufix9 */
  logic [8:0] obj_SamplesRepetitionObj_RGaurdSubRegOut_1;  /* ufix9 */


  assign obj_SamplesRepetitionObj_resetSig = 1'b0;

  assign tmp = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_resetSig_1 :
              obj_SamplesRepetitionObj_resetSig);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_resetSig_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_resetSig_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_resetSig_1 <= tmp;
        end
      end
    end

  assign obj_SamplesRepetitionObj_validInReg = 1'b0;

  assign tmp_1 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_2 :
              obj_SamplesRepetitionObj_validInReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validInReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validInReg_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validInReg_1 <= tmp_1;
        end
      end
    end

  assign obj_SamplesRepetitionObj_currFFTLength = 9'b100000000;

  assign obj_SamplesRepetitionObj_FFTLenReg = 9'b100000000;

  assign tmp_2 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_3 :
              obj_SamplesRepetitionObj_FFTLenReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLenReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLenReg_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLenReg_1 <= tmp_2;
        end
      end
    end

  assign tmp_3 = obj_SamplesRepetitionObj_FFTLenReg_1 - 9'b000000001;

  assign obj_SamplesRepetitionObj_inCount = 9'b000000000;

  assign obj_SamplesRepetitionObj_inCount_1 = 9'b000000000;

  assign tmp_4 = obj_SamplesRepetitionObj_inCount_2 + 9'b000000001;

  assign tmp_6 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_5 :
              obj_SamplesRepetitionObj_currFFTLength);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_currFFTLength_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_currFFTLength_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_currFFTLength_1 <= tmp_6;
        end
      end
    end

  assign s = (obj_SamplesRepetitionObj_inCount_2 == 9'b000000000) && obj_SamplesRepetitionObj_validInReg_1;

  assign tmp_5 = (s == 1'b0 ? obj_SamplesRepetitionObj_currFFTLength_1 :
              tmp_3);

  assign a0 = obj_SamplesRepetitionObj_inCount_2 == tmp_5;

  assign tmp_7 = (a0 == 1'b0 ? tmp_4 :
              obj_SamplesRepetitionObj_inCount);

  assign tmp_8 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? obj_SamplesRepetitionObj_inCount_2 :
              tmp_7);

  assign tmp_9 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_8 :
              obj_SamplesRepetitionObj_inCount_1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_inCount_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_inCount_2 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_inCount_2 <= tmp_9;
        end
      end
    end

  assign a0_1 = obj_SamplesRepetitionObj_inCount_2 == tmp_5;

  assign obj_SamplesRepetitionObj_flag = 1'b1;

  assign a0_2 = obj_SamplesRepetitionObj_inCount_2 == tmp_5;

  assign obj_SamplesRepetitionObj_flag_1 = 1'b0;

  assign obj_SamplesRepetitionObj_flag_2 = 1'b0;

  assign tmp_10 = (a0_2 == 1'b0 ? obj_SamplesRepetitionObj_flag_3 :
              obj_SamplesRepetitionObj_flag_1);

  assign tmp_11 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? obj_SamplesRepetitionObj_flag_3 :
              tmp_10);

  assign tmp_12 = (a0_1 == 1'b0 ? obj_SamplesRepetitionObj_flag_3 :
              obj_SamplesRepetitionObj_flag);

  assign tmp_13 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? obj_SamplesRepetitionObj_flag_3 :
              tmp_12);

  assign tmp_14 = (obj_SamplesRepetitionObj_flag_3 == 1'b0 ? tmp_13 :
              tmp_11);

  assign tmp_15 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_14 :
              obj_SamplesRepetitionObj_flag_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_flag_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_flag_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_flag_3 <= tmp_15;
        end
      end
    end

  assign obj_SamplesRepetitionObj_sym2Done = 1'b0;

  assign obj_SamplesRepetitionObj_sym2Done_1 = 1'b1;

  assign obj_SamplesRepetitionObj_sym2Done_2 = 1'b0;

  assign obj_SamplesRepetitionObj_startRead2 = 1'b1;

  assign obj_SamplesRepetitionObj_startRead2_1 = 1'b0;

  assign obj_SamplesRepetitionObj_startRead2_2 = 1'b0;

  assign obj_SamplesRepetitionObj_outCount = 9'b000000000;

  assign obj_SamplesRepetitionObj_outCount_1 = 9'b000000000;

  assign obj_SamplesRepetitionObj_outCount_2 = 9'b000000000;

  assign obj_SamplesRepetitionObj_startRead2_3 = 1'b0;

  assign obj_SamplesRepetitionObj_sym1Done = 1'b0;

  assign obj_SamplesRepetitionObj_sym1Done_1 = 1'b1;

  assign obj_SamplesRepetitionObj_sym1Done_2 = 1'b0;

  assign obj_SamplesRepetitionObj_startRead1 = 1'b0;

  assign obj_SamplesRepetitionObj_startRead1_1 = 1'b1;

  assign obj_SamplesRepetitionObj_startRead1_2 = 1'b0;

  assign obj_SamplesRepetitionObj_startRead1_3 = 1'b0;

  assign tmp_17 = (tmp_16 == 1'b0 ? obj_SamplesRepetitionObj_startRead1_1 :
              obj_SamplesRepetitionObj_startRead1_2);

  assign tmp_18 = (s_1 == 1'b0 ? obj_SamplesRepetitionObj_startRead1_4 :
              obj_SamplesRepetitionObj_startRead1);

  assign tmp_19 = (s_2 == 1'b0 ? obj_SamplesRepetitionObj_startRead1_4 :
              tmp_18);

  assign tmp_21 = (a0_1 == 1'b0 ? tmp_20 :
              obj_SamplesRepetitionObj_sym1Done_1);

  assign tmp_22 = obj_SamplesRepetitionObj_outCount_3 + 9'b000000001;

  assign p391_1 = {1'b0, obj_SamplesRepetitionObj_outCount_3};
  assign s_1 = p391_1 == 10'b0011111111;

  assign tmp_23 = (s_1 == 1'b0 ? tmp_22 :
              obj_SamplesRepetitionObj_outCount_1);

  assign tmp_24 = obj_SamplesRepetitionObj_outCount_3 + 9'b000000001;

  assign tmp_25 = (s_3 == 1'b0 ? tmp_24 :
              obj_SamplesRepetitionObj_outCount);

  assign tmp_26 = (s_4 == 1'b0 ? obj_SamplesRepetitionObj_outCount_3 :
              tmp_25);

  assign tmp_27 = (s_2 == 1'b0 ? tmp_26 :
              tmp_23);

  assign tmp_28 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_27 :
              obj_SamplesRepetitionObj_outCount_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_outCount_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_outCount_3 <= 9'b000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_outCount_3 <= tmp_28;
        end
      end
    end

  assign p381_1 = {1'b0, obj_SamplesRepetitionObj_outCount_3};
  assign s_3 = p381_1 == 10'b0011111111;

  assign tmp_29 = (s_3 == 1'b0 ? obj_SamplesRepetitionObj_startRead2_4 :
              obj_SamplesRepetitionObj_startRead2_3);

  assign s_4 = obj_SamplesRepetitionObj_startRead2_4 && ( ! obj_SamplesRepetitionObj_startRead1_4);

  assign tmp_30 = (s_4 == 1'b0 ? obj_SamplesRepetitionObj_startRead2_4 :
              tmp_29);

  assign tmp_32 = (tmp_31 == 1'b0 ? obj_SamplesRepetitionObj_startRead2 :
              obj_SamplesRepetitionObj_startRead2_1);

  assign tmp_34 = (a0_2 == 1'b0 ? tmp_33 :
              obj_SamplesRepetitionObj_sym2Done_1);

  assign tmp_35 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? tmp_33 :
              tmp_34);

  assign tmp_36 = (tmp_31 == 1'b0 ? obj_SamplesRepetitionObj_sym2Done :
              obj_SamplesRepetitionObj_sym2Done_3);

  assign tmp_33 = (obj_SamplesRepetitionObj_sym2Done_3 == 1'b0 ? obj_SamplesRepetitionObj_sym2Done_3 :
              tmp_36);

  assign tmp_37 = (obj_SamplesRepetitionObj_flag_3 == 1'b0 ? tmp_33 :
              tmp_35);

  assign tmp_38 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_37 :
              obj_SamplesRepetitionObj_sym2Done_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_sym2Done_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_sym2Done_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_sym2Done_3 <= tmp_38;
        end
      end
    end

  assign tmp_39 = (obj_SamplesRepetitionObj_sym2Done_3 == 1'b0 ? tmp_16 :
              tmp_32);

  assign tmp_40 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_39 :
              obj_SamplesRepetitionObj_startRead2_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_startRead2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_startRead2_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_startRead2_4 <= tmp_40;
        end
      end
    end

  assign s_2 = obj_SamplesRepetitionObj_startRead1_4 && ( ! obj_SamplesRepetitionObj_startRead2_4);

  assign tmp_16 = (s_2 == 1'b0 ? tmp_30 :
              obj_SamplesRepetitionObj_startRead2_4);

  assign tmp_41 = (tmp_16 == 1'b0 ? obj_SamplesRepetitionObj_sym1Done :
              obj_SamplesRepetitionObj_sym1Done_3);

  assign tmp_20 = (obj_SamplesRepetitionObj_sym1Done_3 == 1'b0 ? obj_SamplesRepetitionObj_sym1Done_3 :
              tmp_41);

  assign tmp_42 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? tmp_20 :
              tmp_21);

  assign tmp_43 = (obj_SamplesRepetitionObj_flag_3 == 1'b0 ? tmp_42 :
              tmp_20);

  assign tmp_44 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_43 :
              obj_SamplesRepetitionObj_sym1Done_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_sym1Done_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_sym1Done_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_sym1Done_3 <= tmp_44;
        end
      end
    end

  assign tmp_31 = (obj_SamplesRepetitionObj_sym1Done_3 == 1'b0 ? tmp_19 :
              tmp_17);

  assign tmp_45 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_31 :
              obj_SamplesRepetitionObj_startRead1_3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_startRead1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_startRead1_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_startRead1_4 <= tmp_45;
        end
      end
    end

  assign obj_SamplesRepetitionObj_strtRd1Reg = 1'b0;

  assign tmp_46 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_startRead1_4 :
              obj_SamplesRepetitionObj_strtRd1Reg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_strtRd1Reg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_strtRd1Reg_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_strtRd1Reg_1 <= tmp_46;
        end
      end
    end

  assign obj_SamplesRepetitionObj_strtRd1Reg1 = 1'b0;

  assign tmp_47 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_strtRd1Reg_1 :
              obj_SamplesRepetitionObj_strtRd1Reg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_strtRd1Reg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_strtRd1Reg1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_strtRd1Reg1_1 <= tmp_47;
        end
      end
    end

  assign obj_SamplesRepetitionObj_strtRd2Reg = 1'b0;

  assign tmp_48 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_startRead2_4 :
              obj_SamplesRepetitionObj_strtRd2Reg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_strtRd2Reg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_strtRd2Reg_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_strtRd2Reg_1 <= tmp_48;
        end
      end
    end

  assign obj_SamplesRepetitionObj_strtRd2Reg1 = 1'b0;

  assign tmp_49 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_strtRd2Reg_1 :
              obj_SamplesRepetitionObj_strtRd2Reg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_strtRd2Reg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_strtRd2Reg1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_strtRd2Reg1_1 <= tmp_49;
        end
      end
    end

  assign s_5 = obj_SamplesRepetitionObj_strtRd1Reg1_1 && ( ! obj_SamplesRepetitionObj_strtRd2Reg1_1);

  assign s_6 = ( ! obj_SamplesRepetitionObj_strtRd1Reg1_1) && obj_SamplesRepetitionObj_strtRd2Reg1_1;

  assign obj_SamplesRepetitionObj_dataOutReg_re = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataOutReg_im = 16'sb0000000000000000;

  assign obj_SamplesRepetitionObj_dataInReg_re = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataInReg_im = 16'sb0000000000000000;

  assign tmp_re = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_1_re :
              obj_SamplesRepetitionObj_dataInReg_re);
  assign tmp_im = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_1_im :
              obj_SamplesRepetitionObj_dataInReg_im);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_dataInReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_dataInReg_re_1 <= 16'sb0000000000000000;
        obj_SamplesRepetitionObj_dataInReg_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_dataInReg_re_1 <= tmp_re;
          obj_SamplesRepetitionObj_dataInReg_im_1 <= tmp_im;
        end
      end
    end

  assign obj_SamplesRepetitionObj_dataInReg1_re = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataInReg1_im = 16'sb0000000000000000;

  assign tmp_re_1 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataInReg_re_1 :
              obj_SamplesRepetitionObj_dataInReg1_re);
  assign tmp_im_1 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataInReg_im_1 :
              obj_SamplesRepetitionObj_dataInReg1_im);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_dataInReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_dataInReg1_re_1 <= 16'sb0000000000000000;
        obj_SamplesRepetitionObj_dataInReg1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_dataInReg1_re_1 <= tmp_re_1;
          obj_SamplesRepetitionObj_dataInReg1_im_1 <= tmp_im_1;
        end
      end
    end

  assign obj_SamplesRepetitionObj_wrAddr2 = 8'b00000000;

  assign obj_SamplesRepetitionObj_wrAddr2_1 = 8'b00000000;

  assign tmp_50 = obj_SamplesRepetitionObj_wrAddr2_2 + 8'b00000001;

  assign tmp_51 = (a0_2 == 1'b0 ? tmp_50 :
              obj_SamplesRepetitionObj_wrAddr2);

  assign tmp_52 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? obj_SamplesRepetitionObj_wrAddr2_2 :
              tmp_51);

  assign tmp_53 = (obj_SamplesRepetitionObj_flag_3 == 1'b0 ? obj_SamplesRepetitionObj_wrAddr2_2 :
              tmp_52);

  assign tmp_54 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_53 :
              obj_SamplesRepetitionObj_wrAddr2_1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_wrAddr2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_wrAddr2_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_wrAddr2_2 <= tmp_54;
        end
      end
    end

  assign s_7 = obj_SamplesRepetitionObj_validInReg_1 && obj_SamplesRepetitionObj_flag_3;

  assign s_8 = 1'b0;

  assign s_9 = 1'b1;

  assign tmp_55 = (s_7 == 1'b0 ? s_8 :
              s_9);

  assign obj_SamplesRepetitionObj_wrEn2 = 1'b0;

  assign tmp_56 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_55 :
              obj_SamplesRepetitionObj_wrEn2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_wrEn2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_wrEn2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_wrEn2_1 <= tmp_56;
        end
      end
    end

  assign s_10 = obj_SamplesRepetitionObj_inCount_2 == 9'b000000000;

  assign tmp_57 = tmp_27 == 9'b000000000;

  assign obj_SamplesRepetitionObj_prevFFTLength = 9'b100000000;

  assign tmp_58 = (tmp_57 == 1'b0 ? obj_SamplesRepetitionObj_prevFFTLength_1 :
              obj_SamplesRepetitionObj_currFFTLength_1);

  assign tmp_59 = (s_10 == 1'b0 ? obj_SamplesRepetitionObj_prevFFTLength_1 :
              tmp_58);

  assign tmp_60 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_59 :
              obj_SamplesRepetitionObj_prevFFTLength);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_prevFFTLength_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_prevFFTLength_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_prevFFTLength_1 <= tmp_60;
        end
      end
    end

  assign obj_SamplesRepetitionObj_rdAddr2 = 8'b00000000;

  assign obj_SamplesRepetitionObj_rdAddr2_1 = 8'b00000000;

  assign obj_SamplesRepetitionObj_rdAddr2_2 = 8'b00000000;

  assign tmp_62 = (tmp_57 == 1'b0 ? tmp_61 :
              obj_SamplesRepetitionObj_rdAddr2_1);

  assign tmp_63 = obj_SamplesRepetitionObj_rdAddr2_3 + 8'b00000001;

  assign p375_1 = {1'b0, obj_SamplesRepetitionObj_rdAddr2_3};
  assign s_11 = p375_1 == obj_SamplesRepetitionObj_prevFFTLength_1;

  assign tmp_64 = (s_11 == 1'b0 ? tmp_63 :
              obj_SamplesRepetitionObj_rdAddr2);

  assign tmp_65 = (s_4 == 1'b0 ? obj_SamplesRepetitionObj_rdAddr2_3 :
              tmp_64);

  assign tmp_61 = (s_2 == 1'b0 ? tmp_65 :
              obj_SamplesRepetitionObj_rdAddr2_3);

  assign tmp_66 = (s_10 == 1'b0 ? tmp_61 :
              tmp_62);

  assign tmp_67 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_66 :
              obj_SamplesRepetitionObj_rdAddr2_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_rdAddr2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_rdAddr2_3 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_rdAddr2_3 <= tmp_67;
        end
      end
    end

  rxsl_SimpleDualPortRAM_generic #(.AddrWidth(8),
                              .DataWidth(16)
                              )
                            u_simpleDualPortRam (.clk(clk),
                                                 .enb(enb),
                                                 .wr_din_re(obj_SamplesRepetitionObj_dataInReg1_re_1),
                                                 .wr_din_im(obj_SamplesRepetitionObj_dataInReg1_im_1),
                                                 .wr_addr(obj_SamplesRepetitionObj_wrAddr2_2),
                                                 .wr_en(obj_SamplesRepetitionObj_wrEn2_1),
                                                 .rd_addr(obj_SamplesRepetitionObj_rdAddr2_3),
                                                 .dout_re(varargout_1_re_1),
                                                 .dout_im(varargout_1_im_1)
                                                 );

  assign tmp_re_2 = (s_6 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg_re :
              varargout_1_re_1);
  assign tmp_im_2 = (s_6 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg_im :
              varargout_1_im_1);

  assign obj_SamplesRepetitionObj_wrAddr1 = 8'b00000000;

  assign obj_SamplesRepetitionObj_wrAddr1_1 = 8'b00000000;

  assign tmp_68 = obj_SamplesRepetitionObj_wrAddr1_2 + 8'b00000001;

  assign tmp_69 = (a0_1 == 1'b0 ? tmp_68 :
              obj_SamplesRepetitionObj_wrAddr1);

  assign tmp_70 = (obj_SamplesRepetitionObj_validInReg_1 == 1'b0 ? obj_SamplesRepetitionObj_wrAddr1_2 :
              tmp_69);

  assign tmp_71 = (obj_SamplesRepetitionObj_flag_3 == 1'b0 ? tmp_70 :
              obj_SamplesRepetitionObj_wrAddr1_2);

  assign tmp_72 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_71 :
              obj_SamplesRepetitionObj_wrAddr1_1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_wrAddr1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_wrAddr1_2 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_wrAddr1_2 <= tmp_72;
        end
      end
    end

  assign s_12 = obj_SamplesRepetitionObj_validInReg_1 && ( ! obj_SamplesRepetitionObj_flag_3);

  assign s_13 = 1'b0;

  assign s_14 = 1'b1;

  assign tmp_73 = (s_12 == 1'b0 ? s_13 :
              s_14);

  assign obj_SamplesRepetitionObj_wrEn1 = 1'b0;

  assign tmp_74 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_73 :
              obj_SamplesRepetitionObj_wrEn1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_wrEn1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_wrEn1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_wrEn1_1 <= tmp_74;
        end
      end
    end

  assign obj_SamplesRepetitionObj_rdAddr1 = 8'b00000000;

  assign obj_SamplesRepetitionObj_rdAddr1_1 = 8'b00000000;

  assign obj_SamplesRepetitionObj_rdAddr1_2 = 8'b00000000;

  assign tmp_76 = (tmp_57 == 1'b0 ? tmp_75 :
              obj_SamplesRepetitionObj_rdAddr1_1);

  assign tmp_77 = obj_SamplesRepetitionObj_rdAddr1_3 + 8'b00000001;

  assign p385_1 = {1'b0, obj_SamplesRepetitionObj_rdAddr1_3};
  assign s_15 = p385_1 == obj_SamplesRepetitionObj_prevFFTLength_1;

  assign tmp_78 = (s_15 == 1'b0 ? tmp_77 :
              obj_SamplesRepetitionObj_rdAddr1);

  assign tmp_75 = (s_2 == 1'b0 ? obj_SamplesRepetitionObj_rdAddr1_3 :
              tmp_78);

  assign tmp_79 = (s_10 == 1'b0 ? tmp_75 :
              tmp_76);

  assign tmp_80 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_79 :
              obj_SamplesRepetitionObj_rdAddr1_2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_rdAddr1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_rdAddr1_3 <= 8'b00000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_rdAddr1_3 <= tmp_80;
        end
      end
    end

  rxsl_SimpleDualPortRAM_generic #(.AddrWidth(8),
                              .DataWidth(16)
                              )
                            u_simpleDualPortRam_1 (.clk(clk),
                                                   .enb(enb),
                                                   .wr_din_re(obj_SamplesRepetitionObj_dataInReg1_re_1),
                                                   .wr_din_im(obj_SamplesRepetitionObj_dataInReg1_im_1),
                                                   .wr_addr(obj_SamplesRepetitionObj_wrAddr1_2),
                                                   .wr_en(obj_SamplesRepetitionObj_wrEn1_1),
                                                   .rd_addr(obj_SamplesRepetitionObj_rdAddr1_3),
                                                   .dout_re(varargout_1_re_2),
                                                   .dout_im(varargout_1_im_2)
                                                   );

  assign tmp_re_3 = (s_5 == 1'b0 ? tmp_re_2 :
              varargout_1_re_2);
  assign tmp_im_3 = (s_5 == 1'b0 ? tmp_im_2 :
              varargout_1_im_2);

  assign obj_SamplesRepetitionObj_dataOutReg_re_1 = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataOutReg_im_1 = 16'sb0000000000000000;

  assign tmp_re_4 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_re_3 :
              obj_SamplesRepetitionObj_dataOutReg_re_1);
  assign tmp_im_4 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_im_3 :
              obj_SamplesRepetitionObj_dataOutReg_im_1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_dataOutReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_dataOutReg_re_2 <= 16'sb0000000000000000;
        obj_SamplesRepetitionObj_dataOutReg_im_2 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_dataOutReg_re_2 <= tmp_re_4;
          obj_SamplesRepetitionObj_dataOutReg_im_2 <= tmp_im_4;
        end
      end
    end

  assign obj_SamplesRepetitionObj_dataOutReg1_re = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataOutReg1_im = 16'sb0000000000000000;

  assign tmp_re_5 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg_re_2 :
              obj_SamplesRepetitionObj_dataOutReg1_re);
  assign tmp_im_5 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg_im_2 :
              obj_SamplesRepetitionObj_dataOutReg1_im);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_dataOutReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_dataOutReg1_re_1 <= 16'sb0000000000000000;
        obj_SamplesRepetitionObj_dataOutReg1_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_dataOutReg1_re_1 <= tmp_re_5;
          obj_SamplesRepetitionObj_dataOutReg1_im_1 <= tmp_im_5;
        end
      end
    end

  assign obj_SamplesRepetitionObj_dataOut_re = 16'sb0000000000000000;
  assign obj_SamplesRepetitionObj_dataOut_im = 16'sb0000000000000000;

  assign tmp_re_6 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg1_re_1 :
              obj_SamplesRepetitionObj_dataOut_re);
  assign tmp_im_6 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_dataOutReg1_im_1 :
              obj_SamplesRepetitionObj_dataOut_im);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_dataOut_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_dataOut_re_1 <= 16'sb0000000000000000;
        obj_SamplesRepetitionObj_dataOut_im_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_dataOut_re_1 <= tmp_re_6;
          obj_SamplesRepetitionObj_dataOut_im_1 <= tmp_im_6;
        end
      end
    end

  assign varargout_1_re = obj_SamplesRepetitionObj_dataOut_re_1;

  assign varargout_1_im = obj_SamplesRepetitionObj_dataOut_im_1;

  assign obj_SamplesRepetitionObj_validOutReg = 1'b0;

  assign obj_SamplesRepetitionObj_validOutReg_1 = 1'b1;

  assign tmp_81 = (s_4 == 1'b0 ? obj_SamplesRepetitionObj_validOutReg :
              obj_SamplesRepetitionObj_validOutReg_1);

  assign obj_SamplesRepetitionObj_validOutReg_2 = 1'b1;

  assign tmp_82 = (s_2 == 1'b0 ? tmp_81 :
              obj_SamplesRepetitionObj_validOutReg_2);

  assign obj_SamplesRepetitionObj_validOutReg_3 = 1'b0;

  assign tmp_83 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_82 :
              obj_SamplesRepetitionObj_validOutReg_3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validOutReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validOutReg_4 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validOutReg_4 <= tmp_83;
        end
      end
    end

  assign obj_SamplesRepetitionObj_validOutReg1 = 1'b0;

  assign tmp_84 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_validOutReg_4 :
              obj_SamplesRepetitionObj_validOutReg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validOutReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validOutReg1_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validOutReg1_1 <= tmp_84;
        end
      end
    end

  assign obj_SamplesRepetitionObj_validOutReg2 = 1'b0;

  assign tmp_85 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_validOutReg1_1 :
              obj_SamplesRepetitionObj_validOutReg2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validOutReg2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validOutReg2_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validOutReg2_1 <= tmp_85;
        end
      end
    end

  assign obj_SamplesRepetitionObj_validOutReg3 = 1'b0;

  assign tmp_86 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_validOutReg2_1 :
              obj_SamplesRepetitionObj_validOutReg3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validOutReg3_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validOutReg3_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validOutReg3_1 <= tmp_86;
        end
      end
    end

  assign obj_SamplesRepetitionObj_validOut = 1'b0;

  assign tmp_87 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_validOutReg3_1 :
              obj_SamplesRepetitionObj_validOut);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_validOut_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_validOut_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_validOut_1 <= tmp_87;
        end
      end
    end

  assign varargout_2 = obj_SamplesRepetitionObj_validOut_1;

  assign obj_SamplesRepetitionObj_FFTLengthReg = 9'b100000000;

  assign tmp_88 = (s == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg_1 :
              obj_SamplesRepetitionObj_FFTLenReg_1);

  assign tmp_89 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_88 :
              obj_SamplesRepetitionObj_FFTLengthReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLengthReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLengthReg_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLengthReg_1 <= tmp_89;
        end
      end
    end

  assign obj_SamplesRepetitionObj_FFTLengthReg1 = 9'b100000000;

  assign tmp_90 = (tmp_57 == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg1_1 :
              obj_SamplesRepetitionObj_FFTLengthReg_1);

  assign tmp_91 = (s_10 == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg1_1 :
              tmp_90);

  assign tmp_92 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_91 :
              obj_SamplesRepetitionObj_FFTLengthReg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLengthReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLengthReg1_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLengthReg1_1 <= tmp_92;
        end
      end
    end

  assign obj_SamplesRepetitionObj_FFTLengthReg2 = 9'b100000000;

  assign tmp_93 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg1_1 :
              obj_SamplesRepetitionObj_FFTLengthReg2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLengthReg2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLengthReg2_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLengthReg2_1 <= tmp_93;
        end
      end
    end

  assign obj_SamplesRepetitionObj_FFTLengthReg3 = 9'b100000000;

  assign tmp_94 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg2_1 :
              obj_SamplesRepetitionObj_FFTLengthReg3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLengthReg3_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLengthReg3_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLengthReg3_1 <= tmp_94;
        end
      end
    end

  assign obj_SamplesRepetitionObj_FFTLengthRegOut = 9'b100000000;

  assign tmp_95 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_FFTLengthReg3_1 :
              obj_SamplesRepetitionObj_FFTLengthRegOut);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_FFTLengthRegOut_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_FFTLengthRegOut_1 <= 9'b100000000;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_FFTLengthRegOut_1 <= tmp_95;
        end
      end
    end

  assign varargout_3 = obj_SamplesRepetitionObj_FFTLengthRegOut_1;

  assign obj_SamplesRepetitionObj_LGaurdReg = 9'b000000110;

  assign tmp_96 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_4 :
              obj_SamplesRepetitionObj_LGaurdReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdReg_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdReg_1 <= tmp_96;
        end
      end
    end

  assign obj_SamplesRepetitionObj_LGaurdSubReg = 9'b000000110;

  assign tmp_97 = (s == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg_1 :
              obj_SamplesRepetitionObj_LGaurdReg_1);

  assign tmp_98 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_97 :
              obj_SamplesRepetitionObj_LGaurdSubReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdSubReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdSubReg_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdSubReg_1 <= tmp_98;
        end
      end
    end

  assign obj_SamplesRepetitionObj_LGaurdSubReg1 = 9'b000000110;

  assign tmp_99 = (tmp_57 == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg1_1 :
              obj_SamplesRepetitionObj_LGaurdSubReg_1);

  assign tmp_100 = (s_10 == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg1_1 :
              tmp_99);

  assign tmp_101 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_100 :
              obj_SamplesRepetitionObj_LGaurdSubReg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdSubReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdSubReg1_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdSubReg1_1 <= tmp_101;
        end
      end
    end

  assign obj_SamplesRepetitionObj_LGaurdSubReg2 = 9'b000000110;

  assign tmp_102 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg1_1 :
              obj_SamplesRepetitionObj_LGaurdSubReg2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdSubReg2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdSubReg2_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdSubReg2_1 <= tmp_102;
        end
      end
    end

  assign obj_SamplesRepetitionObj_LGaurdSubReg3 = 9'b000000110;

  assign tmp_103 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg2_1 :
              obj_SamplesRepetitionObj_LGaurdSubReg3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdSubReg3_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdSubReg3_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdSubReg3_1 <= tmp_103;
        end
      end
    end

  assign obj_SamplesRepetitionObj_LGaurdSubRegOut = 9'b000000110;

  assign tmp_104 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_LGaurdSubReg3_1 :
              obj_SamplesRepetitionObj_LGaurdSubRegOut);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_LGaurdSubRegOut_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_LGaurdSubRegOut_1 <= 9'b000000110;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_LGaurdSubRegOut_1 <= tmp_104;
        end
      end
    end

  assign varargout_4 = obj_SamplesRepetitionObj_LGaurdSubRegOut_1;

  assign obj_SamplesRepetitionObj_RGaurdReg = 9'b000000101;

  assign tmp_105 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? varargin_5 :
              obj_SamplesRepetitionObj_RGaurdReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdReg_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdReg_1 <= tmp_105;
        end
      end
    end

  assign obj_SamplesRepetitionObj_RGaurdSubReg = 9'b000000101;

  assign tmp_106 = (s == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg_1 :
              obj_SamplesRepetitionObj_RGaurdReg_1);

  assign tmp_107 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_106 :
              obj_SamplesRepetitionObj_RGaurdSubReg);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdSubReg_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdSubReg_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdSubReg_1 <= tmp_107;
        end
      end
    end

  assign obj_SamplesRepetitionObj_RGaurdSubReg1 = 9'b000000101;

  assign tmp_108 = (tmp_57 == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg1_1 :
              obj_SamplesRepetitionObj_RGaurdSubReg_1);

  assign tmp_109 = (s_10 == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg1_1 :
              tmp_108);

  assign tmp_110 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? tmp_109 :
              obj_SamplesRepetitionObj_RGaurdSubReg1);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdSubReg1_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdSubReg1_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdSubReg1_1 <= tmp_110;
        end
      end
    end

  assign obj_SamplesRepetitionObj_RGaurdSubReg2 = 9'b000000101;

  assign tmp_111 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg1_1 :
              obj_SamplesRepetitionObj_RGaurdSubReg2);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdSubReg2_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdSubReg2_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdSubReg2_1 <= tmp_111;
        end
      end
    end

  assign obj_SamplesRepetitionObj_RGaurdSubReg3 = 9'b000000101;

  assign tmp_112 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg2_1 :
              obj_SamplesRepetitionObj_RGaurdSubReg3);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdSubReg3_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdSubReg3_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdSubReg3_1 <= tmp_112;
        end
      end
    end

  assign obj_SamplesRepetitionObj_RGaurdSubRegOut = 9'b000000101;

  assign tmp_113 = (obj_SamplesRepetitionObj_resetSig_1 == 1'b0 ? obj_SamplesRepetitionObj_RGaurdSubReg3_1 :
              obj_SamplesRepetitionObj_RGaurdSubRegOut);

  always_ff @(posedge clk)
    begin : obj_SamplesRepetitionObj_RGaurdSubRegOut_reg_process
      if (reset == 1'b1) begin
        obj_SamplesRepetitionObj_RGaurdSubRegOut_1 <= 9'b000000101;
      end
      else begin
        if (enb) begin
          obj_SamplesRepetitionObj_RGaurdSubRegOut_1 <= tmp_113;
        end
      end
    end

  assign varargout_5 = obj_SamplesRepetitionObj_RGaurdSubRegOut_1;

endmodule  // SamplesRepetition

