// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/searchCtrl.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: searchCtrl
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Windowed Peak Finder/Window Max/searchCtrl
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module searchCtrl
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic validIn,
             input logic startIn,
             output logic endOut,
             output logic [1:0] countOut  /* ufix2 */,
             output logic startOut,
             output logic enableOut);


  logic endOut_1;
  logic [1:0] countOut_1;  /* ufix2 */
  logic startOut_1;
  logic enableOut_1;
  logic reg_enable;
  logic [1:0] reg_count;  /* ufix2 */
  logic reg_enable_next;
  logic [1:0] reg_count_next;  /* ufix2 */
  logic next_enable;
  logic [1:0] next_count;  /* ufix2 */


  always_ff @(posedge clk)
    begin : searchCtrl_1_process
      if (reset == 1'b1) begin
        reg_enable <= 1'b0;
        reg_count <= 2'b00;
      end
      else begin
        if (enb) begin
          reg_enable <= reg_enable_next;
          reg_count <= reg_count_next;
        end
      end
    end

  always_comb begin
    next_enable = reg_enable;
    next_count = reg_count;
    startOut_1 = 1'b0;
    endOut_1 = 1'b0;
    if ( ! reg_enable) begin
      if (startIn) begin
        next_count = 2'b00;
        next_enable = 1'b1;
        startOut_1 = 1'b1;
      end
    end
    else if (validIn) begin
      if (reg_count != 2'b10) begin
        next_count = reg_count + 2'b01;
      end
      else begin
        endOut_1 = 1'b1;
        next_count = 2'b00;
        next_enable = 1'b0;
      end
    end
    reg_enable_next = next_enable;
    reg_count_next = next_count;
    countOut_1 = next_count;
    enableOut_1 = next_enable;
  end

  assign endOut = endOut_1;

  assign countOut = countOut_1;

  assign startOut = startOut_1;

  assign enableOut = enableOut_1;

endmodule  // searchCtrl

