// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_shiftMasks.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: rxsl_shiftMasks
// Source Path: introOFDMReceiver/OFDM Receiver/Channel Estimation and Equalization/Channel Estimation/Reference 
// Symbols/Reference Generation/Gold Sequence Generator/shiftMask
// Hierarchy Level: 6
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_shiftMasks
          (  output logic [30:0] mask1  /* ufix31 */,
             output logic [30:0] mask2  /* ufix31 */);


  logic [30:0] shiftMasksConst_mask1;  /* ufix31 */
  logic [30:0] shiftMasksConst_mask2;  /* ufix31 */


  rxsl_shiftMasksConst u_shiftMasksConst (.mask1(shiftMasksConst_mask1),  /* ufix31 */
                                     .mask2(shiftMasksConst_mask2)  /* ufix31 */
                                     );

  assign mask1 = shiftMasksConst_mask1;

  assign mask2 = shiftMasksConst_mask2;

endmodule  // rxsl_shiftMasks

