// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/rxsl_SimpleDualPortRAM_generic_block.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: rxsl_SimpleDualPortRAM_generic_block
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Synchronize/Frequency Stream Synchronizer/rxsl_SimpleDualPortRAM_generic
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rxsl_SimpleDualPortRAM_generic_block
          #(  parameter logic [31:0] AddrWidth  = 1,
              parameter logic [31:0] DataWidth  = 1)
          (  input logic clk,
             input logic enb,
             input logic [DataWidth - 1:0] wr_din  /* parameterized width */,
             input logic [AddrWidth - 1:0] wr_addr  /* parameterized width */,
             input logic wr_en  /* ufix1 */,
             input logic [AddrWidth - 1:0] rd_addr  /* parameterized width */,
             output logic [DataWidth - 1:0] dout  /* parameterized width */);


  reg  [DataWidth - 1:0] ram [2**AddrWidth - 1:0];
  reg  [DataWidth - 1:0] data_int;
  integer i;

  initial begin
    for (i=0; i<=2**AddrWidth - 1; i=i+1) begin
      ram[i] = 0;
    end
    data_int = 0;
  end


  always @(posedge clk)
    begin : SimpleDualPortRAM_generic_process
      if (enb == 1'b1) begin
        if (wr_en == 1'b1) begin
          ram[wr_addr] <= wr_din;
        end
        data_int <= ram[rd_addr];
      end
    end

  assign dout = data_int;

endmodule  // rxsl_SimpleDualPortRAM_generic_block

