// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/strobeCounter.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: strobeCounter
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Windowed Peak Finder/Window Max/strobeCounter
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module strobeCounter
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic validIn,
             input logic startIn,
             output logic enableOut,
             output logic [1:0] countOut  /* ufix2 */);


  logic enableOut_1;
  logic [1:0] countOut_1;  /* ufix2 */
  logic reg_enable;
  logic [1:0] reg_count;  /* ufix2 */
  logic reg_enable_next;
  logic [1:0] reg_count_next;  /* ufix2 */
  logic next_enable;
  logic [1:0] next_count;  /* ufix2 */


  always_ff @(posedge clk)
    begin : strobeCounter_1_process
      if (reset == 1'b1) begin
        reg_enable <= 1'b0;
        reg_count <= 2'b00;
      end
      else begin
        if (enb) begin
          reg_enable <= reg_enable_next;
          reg_count <= reg_count_next;
        end
      end
    end

  always_comb begin
    next_enable = reg_enable;
    next_count = reg_count;
    if ( ! reg_enable) begin
      if (startIn) begin
        next_count = 2'b00;
        next_enable = 1'b1;
      end
    end
    else if (validIn) begin
      if (reg_count != 2'b10) begin
        next_count = reg_count + 2'b01;
      end
      else begin
        next_count = 2'b00;
        next_enable = 1'b0;
      end
    end
    reg_enable_next = next_enable;
    reg_count_next = next_count;
    enableOut_1 = next_enable;
    countOut_1 = next_count;
  end

  assign enableOut = enableOut_1;

  assign countOut = countOut_1;

endmodule  // strobeCounter

