// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Synchronous_Delay_block.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Synchronous_Delay_block
// Source Path: introOFDMReceiver/OFDM Receiver/OFDM Demodulation/Timing Control/Delay Balance/Delay Enabled Synchronous1/Synchronous 
// Dela
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Synchronous_Delay_block
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] u_re  /* sfix16_En15 */,
             input logic signed [15:0] u_im  /* sfix16_En15 */,
             input logic E,
             output logic signed [15:0] y_re  /* sfix16_En15 */,
             output logic signed [15:0] y_im  /* sfix16_En15 */);


  logic signed [15:0] Delay_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay_out1_im;  /* sfix16_En15 */


  always_ff @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1_re <= 16'sb0000000000000000;
        Delay_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb && E) begin
          Delay_out1_re <= u_re;
          Delay_out1_im <= u_im;
        end
      end
    end

  assign y_re = Delay_out1_re;

  assign y_im = Delay_out1_im;

endmodule  // Synchronous_Delay_block

