// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Threshold_Prescaling.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Threshold_Prescaling
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Thresholded Correlator/Threshold/Threshold 
// Prescalin
// Hierarchy Level: 5
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Threshold_Prescaling
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             output logic signed [17:0] dataOut_re  /* sfix18_En17 */,
             output logic signed [17:0] dataOut_im  /* sfix18_En17 */,
             output logic validOut);


  logic signed [15:0] Delay8_out1_re;  /* sfix16_En15 */
  logic signed [15:0] Delay8_out1_im;  /* sfix16_En15 */
  logic signed [31:0] Gain_out1_re;  /* sfix32_En30 */
  logic signed [31:0] Gain_out1_im;  /* sfix32_En30 */
  logic signed [31:0] Delay9_out1_re;  /* sfix32_En30 */
  logic signed [31:0] Delay9_out1_im;  /* sfix32_En30 */
  logic signed [17:0] Data_Type_Conversion_out1_re;  /* sfix18_En17 */
  logic signed [17:0] Data_Type_Conversion_out1_im;  /* sfix18_En17 */
  logic signed [17:0] Delay2_out1_re;  /* sfix18_En17 */
  logic signed [17:0] Delay2_out1_im;  /* sfix18_En17 */
  logic Delay10_out1;
  logic Delay11_out1;
  logic Delay1_out1;


  always_ff @(posedge clk)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1_re <= 16'sb0000000000000000;
        Delay8_out1_im <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1_re <= dataIn_re;
          Delay8_out1_im <= dataIn_im;
        end
      end
    end

  assign Gain_out1_re = 16'sb0100000000100111 * Delay8_out1_re;
  assign Gain_out1_im = 16'sb0100000000100111 * Delay8_out1_im;

  always_ff @(posedge clk)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1_re <= 32'sb00000000000000000000000000000000;
        Delay9_out1_im <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay9_out1_re <= Gain_out1_re;
          Delay9_out1_im <= Gain_out1_im;
        end
      end
    end

  assign Data_Type_Conversion_out1_re = Delay9_out1_re[30:13] + $signed({1'b0, Delay9_out1_re[12] & (( ~ Delay9_out1_re[31]) | (|Delay9_out1_re[11:0]))});
  assign Data_Type_Conversion_out1_im = Delay9_out1_im[30:13] + $signed({1'b0, Delay9_out1_im[12] & (( ~ Delay9_out1_im[31]) | (|Delay9_out1_im[11:0]))});

  always_ff @(posedge clk)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1_re <= 18'sb000000000000000000;
        Delay2_out1_im <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1_re <= Data_Type_Conversion_out1_re;
          Delay2_out1_im <= Data_Type_Conversion_out1_im;
        end
      end
    end

  assign dataOut_re = Delay2_out1_re;

  assign dataOut_im = Delay2_out1_im;

  always_ff @(posedge clk)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= validIn;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay11_out1 <= Delay10_out1;
        end
      end
    end

  always_ff @(posedge clk)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= Delay11_out1;
        end
      end
    end

  assign validOut = Delay1_out1;

endmodule  // Threshold_Prescaling

