// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Timing_Control.sv
// Created: 2026-06-22 17:26:37
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Timing_Control
// Source Path: introOFDMReceiver/OFDM Receiver/OFDM Demodulation/Timing Control
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Timing_Control
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic signed [15:0] dataIn_re  /* sfix16_En15 */,
             input logic signed [15:0] dataIn_im  /* sfix16_En15 */,
             input logic validIn,
             input logic strobe,
             input logic signed [1:0] tDelta  /* sfix2 */,
             output logic signed [15:0] dataOut_re  /* sfix16_En15 */,
             output logic signed [15:0] dataOut_im  /* sfix16_En15 */,
             output logic validOut,
             output logic [8:0] FFTLen  /* ufix9 */,
             output logic [8:0] CPLen  /* ufix9 */,
             output logic [8:0] numGSc  /* ufix9 */,
             output logic [15:0] cpFraction  /* ufix16_En15 */);


  logic signed [15:0] Delay_Balance_dataOut_re;  /* sfix16_En15 */
  logic signed [15:0] Delay_Balance_dataOut_im;  /* sfix16_En15 */
  logic Delay_Balance_validOut;
  logic Control_enable;
  logic [8:0] Control_FFTLen;  /* ufix9 */
  logic [8:0] Control_CPLen;  /* ufix9 */
  logic [8:0] Control_numGSc;  /* ufix9 */
  logic [15:0] Control_cpFraction;  /* ufix16_En15 */
  logic AND_out1;


  Delay_Balance u_Delay_Balance (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .dataIn_re(dataIn_re),  /* sfix16_En15 */
                                 .dataIn_im(dataIn_im),  /* sfix16_En15 */
                                 .validIn(validIn),
                                 .dataOut_re(Delay_Balance_dataOut_re),  /* sfix16_En15 */
                                 .dataOut_im(Delay_Balance_dataOut_im),  /* sfix16_En15 */
                                 .validOut(Delay_Balance_validOut)
                                 );

  assign dataOut_re = Delay_Balance_dataOut_re;

  assign dataOut_im = Delay_Balance_dataOut_im;

  Control u_Control (.clk(clk),
                     .reset(reset),
                     .enb(enb),
                     .validIn(validIn),
                     .strobe(strobe),
                     .tDelta(tDelta),  /* sfix2 */
                     .enable(Control_enable),
                     .FFTLen(Control_FFTLen),  /* ufix9 */
                     .CPLen(Control_CPLen),  /* ufix9 */
                     .numGSc(Control_numGSc),  /* ufix9 */
                     .cpFraction(Control_cpFraction)  /* ufix16_En15 */
                     );

  assign AND_out1 = Delay_Balance_validOut & Control_enable;

  assign validOut = AND_out1;

  assign FFTLen = Control_FFTLen;

  assign CPLen = Control_CPLen;

  assign numGSc = Control_numGSc;

  assign cpFraction = Control_cpFraction;

endmodule  // Timing_Control

