// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Timing_Track.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Timing_Track
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Timing Track
// Hierarchy Level: 3
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Timing_Track
          #(  parameter rxsl_vector_of_unsigned_logic_14 Compare_To_Constant_data [0:2] = '{8958, 8959, 0}  /* ufix14 [3] */)
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic strobeIn,
             input logic validIn,
             output logic signed [1:0] delta  /* sfix2 */,
             output logic strobeOut,
             output logic validOut);


  logic Unit_Delay_Enabled_Synchronous_out1;
  logic AND1_out1;
  logic [13:0] count_step;  /* ufix14 */
  logic [13:0] count_from;  /* ufix14 */
  logic [13:0] count_reset;  /* ufix14 */
  logic[2:0] Compare_To_Constant_out1;  /* boolean [3] */
  logic Compare_To_Constant_out1_2;
  logic Compare_To_Constant_out1_1;
  logic [13:0] HDL_Counter1_out1;  /* ufix14 */
  logic [13:0] count;  /* ufix14 */
  logic need_to_wrap;
  logic [13:0] count_value;  /* ufix14 */
  logic [13:0] count_1;  /* ufix14 */
  logic AND_out1;
  logic [13:0] count_2;  /* ufix14 */
  logic Compare_To_Constant_out1_0;
  logic OR_out1;
  logic signed [1:0] Zero_out1;  /* sfix2 */
  logic [13:0] Constant_out1;  /* ufix14 */
  logic signed [14:0] Subtract_sub_temp;  /* sfix15 */
  logic signed [14:0] Subtract_1;  /* sfix15 */
  logic signed [14:0] Subtract_2;  /* sfix15 */
  logic signed [1:0] Subtract_out1;  /* sfix2 */
  logic signed [1:0] Multiport_Switch_out1;  /* sfix2 */
  logic NOT_out1;
  logic AND2_out1;
  logic OR1_out1;


  always_ff @(posedge clk)
    begin : Unit_Delay_Enabled_Synchronous_process
      if (reset == 1'b1) begin
        Unit_Delay_Enabled_Synchronous_out1 <= 1'b0;
      end
      else begin
        if (enb && strobeIn) begin
          Unit_Delay_Enabled_Synchronous_out1 <= strobeIn;
        end
      end
    end

  assign AND1_out1 = Unit_Delay_Enabled_Synchronous_out1 & validIn;

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 8959
  assign count_step = 14'b00000000000001;

  assign count_from = 14'b00000000000000;

  assign count_reset = 14'b00000000000000;

  assign Compare_To_Constant_out1_2 = Compare_To_Constant_out1[2];

  assign Compare_To_Constant_out1_1 = Compare_To_Constant_out1[1];

  assign count = HDL_Counter1_out1 + count_step;

  assign need_to_wrap = HDL_Counter1_out1 == 14'b10001011111111;

  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);

  assign count_1 = (AND1_out1 == 1'b0 ? HDL_Counter1_out1 :
              count_value);

  assign count_2 = (AND_out1 == 1'b0 ? count_1 :
              count_reset);

  always_ff @(posedge clk)
    begin : HDL_Counter1_process
      if (reset == 1'b1) begin
        HDL_Counter1_out1 <= 14'b00000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter1_out1 <= count_2;
        end
      end
    end


  genvar t_0;
  generate
    for(t_0 = 32'sd0; t_0 <= 32'sd2; t_0 = t_0 + 32'sd1) begin:Compare_To_Constant_out1_gen
      assign Compare_To_Constant_out1[t_0] = HDL_Counter1_out1 == Compare_To_Constant_data[t_0];
    end
  endgenerate

  assign Compare_To_Constant_out1_0 = Compare_To_Constant_out1[0];

  assign OR_out1 = Compare_To_Constant_out1_2 | (Compare_To_Constant_out1_0 | Compare_To_Constant_out1_1);

  assign AND_out1 = OR_out1 & (Unit_Delay_Enabled_Synchronous_out1 & strobeIn);

  assign Zero_out1 = 2'sb00;

  assign Constant_out1 = 14'b10001011111111;

  assign Subtract_1 = {1'b0, HDL_Counter1_out1};
  assign Subtract_2 = {1'b0, Constant_out1};
  assign Subtract_sub_temp = Subtract_1 - Subtract_2;
  assign Subtract_out1 = Subtract_sub_temp[1:0];

  assign Multiport_Switch_out1 = (AND_out1 == 1'b0 ? Zero_out1 :
              Subtract_out1);

  assign delta = Multiport_Switch_out1;

  assign NOT_out1 =  ~ Unit_Delay_Enabled_Synchronous_out1;

  assign AND2_out1 = strobeIn & NOT_out1;

  assign OR1_out1 = AND2_out1 | AND_out1;

  assign strobeOut = OR1_out1;

  assign validOut = validIn;

endmodule  // Timing_Track

