// -------------------------------------------------------------
// 
// File Name: /home/peter/git/ofdm-de-modulation-and-channel-estimation/IntroductionToCustomOFDMExample/hdl_rx/introOFDMReceiver/Window_Max.sv
// Created: 2026-06-22 17:26:38
// 
// Generated by MATLAB 25.2, HDL Coder 25.2, and Simulink 25.2
// 
// -------------------------------------------------------------


import OFDM_Receiver_pkg::* ;

// -------------------------------------------------------------
// 
// Module: Window_Max
// Source Path: introOFDMReceiver/OFDM Receiver/Synchronization/Timing Offset/Windowed Peak Finder/Window Max
// Hierarchy Level: 4
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Window_Max
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [31:0] correlation  /* ufix32_En24 */,
             input logic thresholdExceeded,
             input logic validIn,
             output logic strobe);


  logic AND2_out1;
  logic endOut;
  logic [1:0] countOut;  /* ufix2 */
  logic startOut;
  logic enableOut;
  logic enableOut_1;
  logic [1:0] countOut_1;  /* ufix2 */
  logic OR_out1;
  logic [31:0] Max_Register_out1;  /* ufix32_En24 */
  logic GreaterThan_out1;
  logic AND_out1;
  logic [1:0] Index_Register_out1;  /* ufix2 */
  logic Equal_out1;
  logic AND1_out1;
  logic Delay_out1;


  assign AND2_out1 = validIn & thresholdExceeded;

  searchCtrl u_searchCtrl (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .validIn(validIn),
                           .startIn(AND2_out1),
                           .endOut(endOut),
                           .countOut(countOut),  /* ufix2 */
                           .startOut(startOut),
                           .enableOut(enableOut)
                           );

  strobeCounter u_strobeCounter (.clk(clk),
                                 .reset(reset),
                                 .enb(enb),
                                 .validIn(validIn),
                                 .startIn(endOut),
                                 .enableOut(enableOut_1),
                                 .countOut(countOut_1)  /* ufix2 */
                                 );

  always_ff @(posedge clk)
    begin : Max_Register_process
      if (reset == 1'b1) begin
        Max_Register_out1 <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb && OR_out1) begin
          Max_Register_out1 <= correlation;
        end
      end
    end

  assign GreaterThan_out1 = correlation > Max_Register_out1;

  assign AND_out1 = enableOut & GreaterThan_out1;

  assign OR_out1 = startOut | AND_out1;

  always_ff @(posedge clk)
    begin : Index_Register_process
      if (reset == 1'b1) begin
        Index_Register_out1 <= 2'b00;
      end
      else begin
        if (enb && OR_out1) begin
          Index_Register_out1 <= countOut;
        end
      end
    end

  assign Equal_out1 = countOut_1 == Index_Register_out1;

  assign AND1_out1 = Equal_out1 & (validIn & enableOut_1);

  always_ff @(posedge clk)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Delay_out1 <= AND1_out1;
        end
      end
    end

  assign strobe = Delay_out1;

endmodule  // Window_Max

